/*****************************************************************************/
/* Qedo - Quality of Service Enabled Distributed Objects                     */
/*                                                                           */
/* Copyright (c) 2002/2003 by the Qedo Team                                  */
/*                                                                           */
/* http://qedo.berlios.de                                                    */
/*                                                                           */
/* This file is part of Qedo Generator                                       */
/*                                                                           */
/* Qedo Generator is free software; you can redistribute it and/or modify    */
/* it under the terms of the GNU General Public License as published by      */
/* the Free Software Foundation; either version 2 of the License, or         */
/* (at your option) any later version.                                       */
/*                                                                           */
/* Qedo Generator is distributed in the hope that it will be useful,         */
/* but WITHOUT ANY WARRANTY; without even the implied warranty of            */
/* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the             */
/* GNU General Public License for more details.                              */
/*                                                                           */
/* You should have received a copy of the GNU General Public License         */
/* along with Foobar; if not, write to the Free Software                     */
/* Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA */
/*                                                                           */
/*****************************************************************************/

#include "GeneratorPersistenceH.h"
#include "Debug.h"
#include <map>

using namespace std;


namespace QEDO_CIDL_Generator {

GeneratorPersistenceH::GeneratorPersistenceH
( QEDO_ComponentRepository::CIDLRepository_impl *repository)
: CPPBase(repository), isAbstract(true), isASHKey(true)
{
}

GeneratorPersistenceH::~GeneratorPersistenceH
()
{
}

void
GeneratorPersistenceH::generate(std::string target, std::string fileprefix)
{
	try { initialize(target, fileprefix); }
	catch (InitializeError) { return; }
	
	filename_ = file_prefix_ + "_PSS.h";
	
	out.open(filename_.c_str());
	out << "//\n";
	out << "// generated by Qedo\n";
	out << "//\n\n";
	out << "#ifndef _" << file_prefix_ << "_PSS_H_\n";
	out << "#define _" << file_prefix_ << "_PSS_H_\n\n\n";
	out << "// BEGIN USER INSERT SECTION file_pre\n";
	out << "// END USER INSERT SECTION file_pre\n\n";
	out << "#include \"CORBADepends.h\"\n";
	out << "#include \"PSSStorageObject.h\"\n\n";
	out << "// BEGIN USER INSERT SECTION file_post\n";
	out << "// END USER INSERT SECTION file_post\n";

	doGenerate();

	out << "\n#endif\n";
	out.close();
}

void
GeneratorPersistenceH::check_for_generation(IR__::Contained_ptr item)
{
	//
	// check if item is already known
	//
	if (item_well_known(item))
		return;

	//
	// check if item is already in the list or currently processed
	//
	if ((this->m_recursion_set.find(item->id())) != m_recursion_set.end() || this->already_included (item))
		return;
	else
		m_recursion_set.insert(item->id());

	CORBA::ULong len;
	CORBA::ULong i;
	switch (item->def_kind()) {
	case CORBA__::dk_Module : {
		IR__::ModuleDef_var a_module = IR__::ModuleDef::_narrow(item);

		// modules
		IR__::ContainedSeq_var contained_seq = a_module->contents(CORBA__::dk_Module, true);
		len = contained_seq->length();
		for(i = 0; i < len; i++)
		{
			check_for_generation((*contained_seq)[i]);
		}

		// abstract storagehomes
		contained_seq = a_module->contents(CORBA__::dk_AbstractStorageHome, true);
		len = contained_seq->length();
		for(i = 0; i < len; i++)
		{
			check_for_generation((*contained_seq)[i]);
		}

		// storagehomes
		contained_seq = a_module->contents(CORBA__::dk_StorageHome, true);
		len = contained_seq->length();
		for(i = 0; i < len; i++)
		{
			check_for_generation((*contained_seq)[i]);
		}

		break; }
	case CORBA__::dk_AbstractStorageType : {
		IR__::AbstractStorageTypeDef_var abs_storagetype = IR__::AbstractStorageTypeDef::_narrow(item);

		// insert this interface in generation list
		this->insert_to_generate(item);

		break; }
	case CORBA__::dk_StorageType : {
		IR__::StorageTypeDef_var storagetype = IR__::StorageTypeDef::_narrow(item);

		// insert this interface in generation list
		this->insert_to_generate(item);

		break; }
    case CORBA__::dk_AbstractStorageHome : {
		IR__::AbstractStorageHomeDef_var abs_storagehome = IR__::AbstractStorageHomeDef::_narrow(item);
		
		// insert this interface in generation list
		this->insert_to_generate(item);

		// managed abstract storage type
		IR__::AbstractStorageTypeDef_var abs_storagetype = abs_storagehome->managed_abstract_storage_type();
		this->check_for_generation(abs_storagetype);

		break; }
	case CORBA__::dk_StorageHome : {
		IR__::StorageHomeDef_var storagehome = IR__::StorageHomeDef::_narrow(item);
		
		// insert this interface in generation list
		this->insert_to_generate(item);

		// managed storage type
		IR__::StorageTypeDef_var storagetype = storagehome->managed_storage_type();
		this->check_for_generation(storagetype);

		break; }
	default:
		break;
	};

	m_recursion_set.erase(item->id());
};

void
GeneratorPersistenceH::doAttribute(IR__::AttributeDef_ptr attribute)
{
	out << "\n//\n// " << attribute->id() << "\n//\n";
	std::string attribute_name = mapName(attribute);
	
	// read only
	if(isAbstract) out << "virtual ";
	out << map_psdl_return_type(attribute->type_def(), true) << " " << attribute_name << "() const";
	isAbstract ? out << " = 0;\n" : out << ";\n";

	// not read only
	if(attribute->mode() == IR__::ATTR_NORMAL)
	{
		if(isAbstract) out << "virtual ";
		out << map_psdl_return_type(attribute->type_def(), false) << " " << attribute_name << "(";
		out << map_psdl_parameter_type(attribute->type_def(), false) << " param)";
		isAbstract ? out << " = 0;\n" : out << ";\n";

		if(isAbstract) out << "virtual ";
		out << "void " << attribute_name << "(";
		out << map_psdl_parameter_type(attribute->type_def(), true) << " param)";
		isAbstract ? out << " = 0;\n" : out << ";\n";

		// the fourth operation only for string and wstring
		if(attribute->type_def()->type()->kind()==CORBA::tk_string)
		{
			if(isAbstract) out << "virtual ";
			out << "void " << attribute_name << "(CORBA::String_var& param)";
			isAbstract ? out << " = 0;\n" : out << ";\n";
		}
		else if(attribute->type_def()->type()->kind()==CORBA::tk_wstring)
		{
			if(isAbstract) out << "virtual ";
			out << "void " << attribute_name << "(CORBA::WString_var& param)";
			isAbstract ? out << " = 0;\n" : out << ";\n";
		}
	}
}

void
GeneratorPersistenceH::doOperation(IR__::OperationDef_ptr operation)
{
	genOperation(operation, operation->result_def());
}

void
GeneratorPersistenceH::doFactory(IR__::FactoryDef_ptr factory, IR__::InterfaceDef_ptr inf_def)
{
	if( (isAbstract==TRUE) || (isAbstract==FALSE && isASHKey==TRUE) )
	{
		IR__::AbstractStorageTypeDef_var abs_storagetype;
		IR__::AbstractStorageHomeDef_var abs_storagehome = IR__::AbstractStorageHomeDef::_narrow(inf_def);
		if(!CORBA::is_nil(abs_storagehome))
			abs_storagetype = abs_storagehome->managed_abstract_storage_type();
		if(!CORBA::is_nil(abs_storagetype))
			genOperation(factory, abs_storagetype);
	}
	else
	{
		IR__::StorageTypeDef_var storagetype;
		IR__::StorageHomeDef_var storagehome = IR__::StorageHomeDef::_narrow(inf_def);
		if(!CORBA::is_nil(storagehome))
			storagetype = storagehome->managed_storage_type();
		if(!CORBA::is_nil(storagetype))
			genOperation(factory, storagetype);
	}
}

void
GeneratorPersistenceH::doKey(IR__::KeyDef_ptr key, IR__::InterfaceDef_ptr inf_def)
{
	if( (isAbstract==TRUE) || (isAbstract==FALSE && isASHKey==TRUE) )
	{
		IR__::AbstractStorageTypeDef_var abs_storagetype;
		IR__::AbstractStorageHomeDef_var abs_storagehome = IR__::AbstractStorageHomeDef::_narrow(inf_def);
		if(!CORBA::is_nil(abs_storagehome))
			abs_storagetype = abs_storagehome->managed_abstract_storage_type();
		if(!CORBA::is_nil(abs_storagetype))
		{
			genKey(key, abs_storagetype, false);
			genKey(key, abs_storagetype, true);
		}
	}
	else
	{
		IR__::StorageTypeDef_var storagetype;
		IR__::StorageHomeDef_var storagehome = IR__::StorageHomeDef::_narrow(inf_def);
		if(!CORBA::is_nil(storagehome))
			storagetype = storagehome->managed_storage_type();
		if(!CORBA::is_nil(storagetype))
		{
			genKey(key, storagetype, false);
			genKey(key, storagetype, true);
		}
	}
}

void 
GeneratorPersistenceH::doException(IR__::ExceptionDef_ptr except)
{
	out << ", " << mapFullName(except);
}

void 
GeneratorPersistenceH::doAbstractStorageType(IR__::AbstractStorageTypeDef_ptr abs_storage_type)
{
	// achtung: wenn kein modul, sollte vielleicht PSS_ der prefix für alle pss sein?
	out << "\n\n";
	open_module(out, abs_storage_type, "");
	out << "\n\n";

	// generate normal class
	genAbstractStorageTypeBody(abs_storage_type, false);
	// generate ref class
	genAbstractStorageTypeBody(abs_storage_type, true);

	close_module(out, abs_storage_type);
}

void 
GeneratorPersistenceH::doStorageType(IR__::StorageTypeDef_ptr storage_type)
{
	// achtung: wenn kein modul, sollte vielleicht PSS_ der prefix für alle pss sein?
	out << "\n\n";	
	open_module(out, storage_type, "");
	out << "\n\n";

	// generate normal class
	genStorageTypeBody(storage_type, false);
	// generate ref class
	genStorageTypeBody(storage_type, true);

	close_module(out, storage_type);
}

void 
GeneratorPersistenceH::doAbstractStorageHome(IR__::AbstractStorageHomeDef_ptr abs_storage_home)
{
	abs_storagehome_ = IR__::AbstractStorageHomeDef::_duplicate(abs_storage_home);
	abs_storagetype_ = IR__::AbstractStorageTypeDef::_duplicate(abs_storage_home->managed_abstract_storage_type());

	// achtung: wenn kein modul, sollte vielleicht PSS_ der prefix für alle pss sein?
	out << "\n\n";
	open_module(out, abs_storagetype_, "");
	out << "\n\n";

	std::string class_name = string(abs_storage_home->name());

	out << "class " << class_name << "\n";
	out.indent();
	
	IR__::InterfaceDefSeq_var abs_storage_homes = abs_storage_home->base_abstract_storage_homes();
	if(abs_storage_homes->length()==0)
		out << ": public virtual CosPersistentState::StorageHomeBase\n";
	else
		for(CORBA::ULong i = 0; i < abs_storage_homes->length(); i++) {
			IR__::AbstractStorageHomeDef_ptr abs_storage_home_inh;
			abs_storage_home_inh = IR__::AbstractStorageHomeDef::_narrow((*abs_storage_homes)[i]);
			i==0 ? out << ": " : out << ", ";
			out << "public virtual " << abs_storage_home_inh->name() << "\n";
		};

	out.unindent();
	out << "{\n\n";
	out << "public:\n\n";
	out.indent();
    out << class_name << "();\n";
	out << "~" << class_name << "();\n";

	isAbstract = true;
	handleAttribute(abs_storage_home);
	handleOperation(abs_storage_home);
	handleFactory(abs_storage_home);
	handleKey(abs_storage_home);

	out.unindent();
	out << "};\n\n";
	out << "typedef OB::ObjVar< " << class_name << " > " << class_name << "_var;\n";
	out << "typedef OB::ObjVar< " << class_name << " > " << class_name << "_out;\n";
	out << "\n\n";

	close_module(out, abs_storagetype_);
}

void 
GeneratorPersistenceH::doStorageHome(IR__::StorageHomeDef_ptr storage_home)
{
	storagehome_ = IR__::StorageHomeDef::_duplicate(storage_home);
	storagetype_ = IR__::StorageTypeDef::_duplicate(storage_home->managed_storage_type());

	// achtung: wenn kein modul, sollte vielleicht PSS_ der prefix für alle pss sein?
	out << "\n\n";
	open_module(out, storagetype_, "");
	out << "\n\n";

	std::string class_name = string(storage_home->name());

	out << "class " << class_name << "\n";
	out.indent();
	
	IR__::InterfaceDefSeq_var supported_infs = storage_home->supported_interfaces();
	if(supported_infs->length()==0)
		out << "ERROR: NO SUPPORTED INTERFACES?\n";
	else
		for(CORBA::ULong i = 0; i < supported_infs->length(); i++) {
			IR__::AbstractStorageHomeDef_ptr abs_storage_home_inh;
			abs_storage_home_inh = IR__::AbstractStorageHomeDef::_narrow((*supported_infs)[i]);
			i==0 ? out << ": " : out << ", ";
			out << "public virtual " << abs_storage_home_inh->name() << "\n";
		};

	IR__::StorageHomeDef_ptr base_storage_home = storage_home->base_storage_home();
	if(base_storage_home)
		out << ", public virtual " << base_storage_home->name() << "\n";

	out << "// BEGIN USER INSERT SECTION INHERITANCE_" << class_name << "\n";
	out << "// END USER INSERT SECTION INHERITANCE_" << class_name << "\n";
	out.unindent();
	out << "{\n\n";
	out << "public:\n\n";
	out.indent();
    out << class_name << "();\n";
	out << "~" << class_name << "();\n\n";

	genCreateOperation(storage_home, false);
	genCreateOperation(storage_home, true);

	if(supported_infs->length()==0)
		out << "ERROR: NO SUPPORTED INTERFACES?\n";
	else
		for(CORBA::ULong i = 0; i < supported_infs->length(); i++) {
			isAbstract = false;
			isASHKey = true;
			IR__::AbstractStorageHomeDef_ptr abs_storage_home;
			abs_storage_home = IR__::AbstractStorageHomeDef::_narrow((*supported_infs)[i]);
			handleAttribute(abs_storage_home);
			handleOperation(abs_storage_home);
			handleFactory(abs_storage_home);
			handleKey(abs_storage_home);
		};

	isAbstract = false;
	isASHKey = false;
	handleAttribute(storage_home);
	handleOperation(storage_home);
	handleFactory(storage_home);
	handleKey(storage_home);

	out.unindent();
	out << "\n// BEGIN USER INSERT SECTION " << class_name << "\n";
	out << "// END USER INSERT SECTION " << class_name << "\n\n";
	out << "};\n";
	out << "\n\n";

	close_module(out, storagetype_);
}

void
GeneratorPersistenceH::genOperation(IR__::OperationDef_ptr operation, IR__::IDLType_ptr ret_type)
{
	out << "\n//\n// " << operation->id() << "\n//\n";
	if(isAbstract) out << "virtual ";
	out << map_psdl_return_type(ret_type, false) << " " << mapName(operation) << "(";

	//
	// parameters
	//
	IR__::ParDescriptionSeq* pards = operation->params();
	CORBA::ULong i;
	for( i= pards->length(); i > 0; i--)
	{
		if(i < pards->length()) { out << ", "; }
		IR__::ParameterDescription pardescr = (*pards)[i - 1];
		if (pardescr.mode == IR__::PARAM_IN) {
			out << map_in_parameter_type (pardescr.type_def) << " " << string(pardescr.name);
		};
		if (pardescr.mode == IR__::PARAM_OUT) {
			out << map_out_parameter_type (pardescr.type_def) << " " << string(pardescr.name);
		};
		if (pardescr.mode == IR__::PARAM_INOUT) {
			out << map_inout_parameter_type (pardescr.type_def) << " " << string(pardescr.name);
		};
	};

	isAbstract ? out << ") = 0;\n" : out << ");\n";
}

void
GeneratorPersistenceH::genKey(IR__::OperationDef_ptr operation, IR__::IDLType_ptr ret_type, bool isRef)
{
	if(!isRef)
		out << "\n//\n// " << operation->id() << "\n//\n";
	if(isAbstract) out << "virtual ";
	char* szReturnType = map_psdl_return_type(ret_type, false);

	//since the definition of a abstract stoage type is not yet supported, 
	//we have to replcace the "_ptr" with "&" for operation find_by_ref_... 
	if(isRef)
	{
		char* pdest = strstr( szReturnType, "*" );
		if( pdest != NULL )
			memset(pdest, '&', 1);
	}
	
	out << szReturnType;
	isRef ? out << " find_ref_by_" : out << " find_by_";
	out << mapName(operation) << "(";

	//
	// parameters
	//
	IR__::ParDescriptionSeq* pards = operation->params();
	CORBA::ULong i;
	for( i= pards->length(); i > 0; i--)
	{
		if(i < pards->length()) { out << ", "; }
		IR__::ParameterDescription pardescr = (*pards)[i - 1];
		if (pardescr.mode == IR__::PARAM_IN) {
			out << map_in_parameter_type (pardescr.type_def) << " " << string(pardescr.name);
		};
		if (pardescr.mode == IR__::PARAM_OUT) {
			out << map_out_parameter_type (pardescr.type_def) << " " << string(pardescr.name);
		};
		if (pardescr.mode == IR__::PARAM_INOUT) {
			out << map_inout_parameter_type (pardescr.type_def) << " " << string(pardescr.name);
		};
	};

	out << ")";
	
	if(!isRef)
	{
		out << "\n";
		out.indent();
		out << "throw(CosPersistentState::NotFound";
		handleException(operation);
		out << ")";
		out.unindent();
	}
	
	isAbstract ? out << " = 0;\n" : out << ";\n";
}

void 
GeneratorPersistenceH::genAbstractStorageTypeBody(IR__::AbstractStorageTypeDef_ptr abs_storage_type, bool isRef)
{
	std::string class_name = string(abs_storage_type->name());

	out << "class " << class_name;
	isRef ? out << "Ref\n" : out << "\n";
	out.indent();
	
	IR__::InterfaceDefSeq_var abs_storage_types = abs_storage_type->base_abstract_storage_types();
	if(abs_storage_types->length()==0)
	{
		out << ": public virtual CosPersistentState::StorageObject";
		isRef ? out << "Ref\n" : out << "\n";
	}
	else
		for(CORBA::ULong i = 0; i < abs_storage_types->length(); i++) {
			IR__::AbstractStorageTypeDef_ptr abs_storage_type_inh;
			abs_storage_type_inh = IR__::AbstractStorageTypeDef::_narrow((*abs_storage_types)[i]);
			i==0 ? out << ": " : out << ", ";
			out << "public virtual " << abs_storage_type_inh->name();
			isRef ? out << "Ref\n" : out << "\n";
		};

	out.unindent();
	out << "{\n\n";
	out << "public:\n\n";
	out.indent();
    out << class_name;
	isRef ? out << "Ref();\n" : out << "();\n";
	out << "~" << class_name;
	isRef ? out << "Ref();\n" : out << "();\n";

	isAbstract = true;
	handleAttribute(abs_storage_type);
	handleOperation(abs_storage_type);

	out.unindent();
	out << "};\n\n";

	out << "typedef OB::ObjVar< " << class_name;
	if(isRef) out << "Ref";
	out	<< " > " << class_name;
	if(isRef) out << "Ref"; 
	out << "_var;\n";
	out << "typedef OB::ObjVar< " << class_name;
	if(isRef) out << "Ref";
	out << " > " << class_name;
	if(isRef) out << "Ref";
	out << "_out;\n";
	out << "\n\n";
}

void 
GeneratorPersistenceH::genStorageTypeBody(IR__::StorageTypeDef_ptr storage_type, bool isRef)
{
	std::string class_name = string(storage_type->name());

	out << "class " << class_name;
	isRef ? out << "Ref\n" : out << "\n";
	out.indent();
	
	IR__::InterfaceDefSeq_var supported_infs = storage_type->supported_interfaces();
	if(supported_infs->length()==0)
		out << "ERROR: NO SUPPORTED INTERFACES?\n";
	else
		for(CORBA::ULong i = 0; i < supported_infs->length(); i++) {
			IR__::AbstractStorageTypeDef_ptr abs_storage_type_inh;
			abs_storage_type_inh = IR__::AbstractStorageTypeDef::_narrow((*supported_infs)[i]);
			i==0 ? out << ": " : out << ", ";
			out << "public virtual " << abs_storage_type_inh->name();
			isRef ? out << "Ref\n" : out << "\n";
		};

	IR__::StorageTypeDef_ptr base_storage_type = storage_type->base_storage_type();
	if(base_storage_type)
		out << ", public virtual " << base_storage_type->name() << "\n";

	out << "// BEGIN USER INSERT SECTION INHERITANCE_" << class_name;
	isRef ? out << "Ref\n" : out << "\n";
	out << "// END USER INSERT SECTION INHERITANCE_" << class_name;
	isRef ? out << "Ref\n" : out << "\n";
	out.unindent();
	out << "{\n\n";
	out << "public:\n\n";
	out.indent();
    out << class_name;
	isRef ? out << "Ref();\n" : out << "();\n";
	out << "~" << class_name;
	isRef ? out << "Ref();\n" : out << "();\n";

	if(supported_infs->length()==0)
		out << "ERROR: NO SUPPORTED INTERFACES?\n";
	else
		for(CORBA::ULong i = 0; i < supported_infs->length(); i++) {
			isAbstract = false;
			handleAttribute((*supported_infs)[i]);
			handleOperation((*supported_infs)[i]);
		};

	isAbstract = false;
	handleAttribute(storage_type);
	handleOperation(storage_type);

	out << "\nvoid setValue(map<string, CORBA::Any> valueMap);\n\n\n";
	out.unindent();

	genAttribute(storage_type);
	
	out << "\n// BEGIN USER INSERT SECTION " << class_name;
	isRef ? out << "Ref\n" : out << "\n";
	out << "// END USER INSERT SECTION " << class_name;
	isRef ? out << "Ref\n" : out << "\n\n";
	out << "};\n";
	out << "\n\n";
}

void
GeneratorPersistenceH::genCreateOperation(IR__::StorageHomeDef_ptr storage_home, bool isRef)
{
	int iLength = 0;
	string strDummy = "";
	char* szDisplay = map_psdl_return_type(storage_home->managed_storage_type(), false);
	isRef ? iLength = strlen(szDisplay) + 11 : iLength = strlen(szDisplay) + 9;
	
	if(isRef)
	{
		char* pdest = strstr( szDisplay, "*" );
		if( pdest != NULL )
		{
			memset(pdest, '\0', 1);
			strcat(szDisplay, "Ref");
		}
	}
	
	out << szDisplay << " _create(";
	
	IR__::AttributeDefSeq state_members;
	storage_home->managed_storage_type()->get_StateMembers(state_members, CORBA__::dk_Create);
	CORBA::ULong len = state_members.length();
	for(CORBA::ULong i = 0; i < len; i++)
	{
		IR__::AttributeDef_var a_attribute = IR__::AttributeDef::_narrow(state_members[i]);
		out << map_in_parameter_type(a_attribute->type_def()) << " " << mapName(a_attribute);
		if( (i+1)!=len )
		{
			out << ",\n";
			strDummy = "";
			strDummy.append(iLength, ' ');
			out << strDummy.c_str();
		}
	}
	
	if(isRef)
	{
		strDummy = "";
		strDummy.append(iLength, ' ');
		out << ",\n" << strDummy.c_str() << "CosPersistentState::YieldRef yr";
	}

	out << ");\n\n"; 
}

void
GeneratorPersistenceH::genAttribute(IR__::StorageTypeDef_ptr storagetype)
{
	IR__::AttributeDefSeq state_members;
	storagetype->get_StateMembers(state_members, CORBA__::dk_Variable);
	CORBA::ULong len = state_members.length();
	
	out << "private:\n\n";
	out.indent();

	for(CORBA::ULong i = 0; i < len; i++)
	{
		IR__::AttributeDef_var a_attribute = IR__::AttributeDef::_narrow(state_members[i]);
		std::string attribute_name = mapName(a_attribute);
		out << map_attribute_type(a_attribute->type_def()) << " m_" << attribute_name << ";\n";
	}
	
	out.unindent();
}

} // namespace
