/*****************************************************************************/
/* Qedo - Quality of Service Enabled Distributed Objects                     */
/*                                                                           */
/* Copyright (c) 2002/2003 by the Qedo Team                                  */
/*                                                                           */
/* http://qedo.berlios.de                                                    */
/*                                                                           */
/* This file is part of Qedo Generator                                       */
/*                                                                           */
/* Qedo Generator is free software; you can redistribute it and/or modify    */
/* it under the terms of the GNU General Public License as published by      */
/* the Free Software Foundation; either version 2 of the License, or         */
/* (at your option) any later version.                                       */
/*                                                                           */
/* Qedo Generator is distributed in the hope that it will be useful,         */
/* but WITHOUT ANY WARRANTY; without even the implied warranty of            */
/* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the             */
/* GNU General Public License for more details.                              */
/*                                                                           */
/* You should have received a copy of the GNU General Public License         */
/* along with Foobar; if not, write to the Free Software                     */
/* Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA */
/*                                                                           */
/*****************************************************************************/

#include "GeneratorPersistenceC.h"
#include "Debug.h"
#include <map>

using namespace std;


namespace QEDO_CIDL_Generator {

GeneratorPersistenceC::GeneratorPersistenceC
( QEDO_ComponentRepository::CIDLRepository_impl *repository)
: CPPBase(repository), isAbstract(true)
{
}

GeneratorPersistenceC::~GeneratorPersistenceC
()
{
}

void
GeneratorPersistenceC::generate(std::string target, std::string fileprefix)
{
	try { initialize(target, fileprefix); }
	catch (InitializeError) { return; }
	
	filename_ = file_prefix_ + "_PSS.cpp";
	
	out.open(filename_.c_str());
	out << "//\n";
	out << "// generated by Qedo\n";
	out << "//\n\n";
	out << "#ifndef _" << file_prefix_ << "_PSS_C_\n";
	out << "#define _" << file_prefix_ << "_PSS_C_\n\n\n";
	out << "#include \"" << file_prefix_ << "_PSS.h\"\n";
	out << "\n// BEGIN USER INSERT SECTION file\n";
	out << "// END USER INSERT SECTION file\n";

	doGenerate();

	out << "\n#endif\n";
	out.close();
}

void
GeneratorPersistenceC::check_for_generation(IR__::Contained_ptr item)
{
	//
	// check if item is already known
	//
	if (item_well_known(item))
		return;

	//
	// check if item is already in the list or currently processed
	//
	if ((this->m_recursion_set.find(item->id())) != m_recursion_set.end() || this->already_included (item))
		return;
	else
		m_recursion_set.insert(item->id());

	CORBA::ULong len;
	CORBA::ULong i;
	switch (item->def_kind()) {
	case CORBA__::dk_Module : {
		IR__::ModuleDef_var a_module = IR__::ModuleDef::_narrow(item);

		// modules
		IR__::ContainedSeq_var contained_seq = a_module->contents(CORBA__::dk_Module, true);
		len = contained_seq->length();
		for(i = 0; i < len; i++)
		{
			check_for_generation((*contained_seq)[i]);
		}

		// storagehomes
		contained_seq = a_module->contents(CORBA__::dk_StorageHome, true);
		len = contained_seq->length();
		for(i = 0; i < len; i++)
		{
			check_for_generation((*contained_seq)[i]);
		}

		break; }
	case CORBA__::dk_StorageType : {
		IR__::StorageTypeDef_var storagetype = IR__::StorageTypeDef::_narrow(item);

		// insert this interface in generation list
		this->insert_to_generate(item);

		break; }
	case CORBA__::dk_StorageHome : {
		IR__::StorageHomeDef_var storagehome = IR__::StorageHomeDef::_narrow(item);
		
		// insert this interface in generation list
		this->insert_to_generate(item);

		// managed storage type
		IR__::StorageTypeDef_var storagetype = storagehome->managed_storage_type();
		this->check_for_generation(storagetype);

		break; }
	default:
		break;
	};

	m_recursion_set.erase(item->id());
};

void
GeneratorPersistenceC::doAttribute(IR__::AttributeDef_ptr attribute)
{
	out << "\n//\n// " << attribute->id() << "\n//\n";
	std::string attribute_name = mapName(attribute);
	
	// read only
	out << map_psdl_return_type(attribute->type_def(), true) << "\n";
	out << class_name_ << "::" << attribute_name << "() const\n";
	out << "{\n";
	out.indent();
	out << "return m_" << attribute_name << ";\n";
	out.unindent();
	out << "}\n\n";

	// not read only
	if(attribute->mode() == IR__::ATTR_NORMAL)
	{
		CORBA::TCKind att_type_kind = attribute->type_def()->type()->kind();
		switch ( att_type_kind )
		{
			case CORBA::tk_short:
			case CORBA::tk_long:
			case CORBA::tk_longlong:
			case CORBA::tk_ushort:
			case CORBA::tk_ulong:
			case CORBA::tk_ulonglong:
			case CORBA::tk_float:
			case CORBA::tk_double:
			case CORBA::tk_longdouble:
			case CORBA::tk_boolean:
			case CORBA::tk_char:
			case CORBA::tk_wchar:
			case CORBA::tk_string:
			case CORBA::tk_wstring:
				genAttributeWithNomalType(attribute, att_type_kind);
				break;
			default:
				genAttributeWithOtherType(attribute, att_type_kind);
		}
	}
}

void
GeneratorPersistenceC::genAttributeWithNomalType(IR__::AttributeDef_ptr attribute, CORBA::TCKind att_type_kind)
{
	std::string attribute_name = mapName(attribute);

	out << map_psdl_return_type(attribute->type_def(), false) << "\n";
	out << class_name_ << "::" << attribute_name << "(";
	out << map_psdl_parameter_type(attribute->type_def(), false) << " param)\n";
	out << "{\n";
	out.indent();
	out << "m_" << attribute_name << " = param;\n";
	out.unindent();
	out << "}\n\n";

	out << "void\n";
	out << class_name_ << "::" << attribute_name << "(";
	out << map_psdl_parameter_type(attribute->type_def(), true) << " param)\n";
	out << "{\n";
	out.indent();
	switch ( att_type_kind )
	{
		case CORBA::tk_string:
			out << "strcpy( m_" << attribute_name << ", param );\n";
			break;
		case CORBA::tk_wstring:
			out << "wcscpy( m_" << attribute_name << ", param );\n";
			break;
		default:
			out << "m_" << attribute_name << " = param;\n";
	}
	out.unindent();
	out << "}\n\n";

	// the fourth operation only for string and wstring
	if(attribute->type_def()->type()->kind()==CORBA::tk_string)
	{
		out << "void\n";
		out << class_name_ << "::" << attribute_name << "(CORBA::String_var& param)\n";
		out << "{\n";
		out.indent();
		out << "m_" << attribute_name << " = param;\n";
		out.unindent();
		out << "}\n\n";
	}
	else if(attribute->type_def()->type()->kind()==CORBA::tk_wstring)
	{
		out << "void\n";
		out << class_name_ << "::" << attribute_name << "(CORBA::WString_var& param)\n";
		out << "{\n";
		out.indent();
		out << "m_" << attribute_name << " = param;\n";
		out.unindent();
		out << "}\n\n";
	}
}

void
GeneratorPersistenceC::genAttributeWithOtherType(IR__::AttributeDef_ptr attribute, CORBA::TCKind att_type_kind)
{
	std::string attribute_name = mapName(attribute);
	out << map_psdl_return_type(attribute->type_def(), false) << "\n";
	out << class_name_ << "::" << attribute_name << "(";
	out << map_psdl_parameter_type(attribute->type_def(), false) << " param)\n";
	out << "{\n";
	out.indent();
	out << "return m_" << attribute_name << ";\n";
	out.unindent();
	out << "}\n\n";

	out << "void\n";
	out << class_name_ << "::" << attribute_name << "(";
	out << map_psdl_parameter_type(attribute->type_def(), true) << " param)\n";
	out << "{\n";
	out.indent();
	out << "m_" << attribute_name << " = param;\n";
	out.unindent();
	out << "}\n\n";
}

void
GeneratorPersistenceC::doOperation(IR__::OperationDef_ptr operation)
{
	genOperation(operation, operation->result_def());
}

void
GeneratorPersistenceC::genOperation(IR__::OperationDef_ptr operation, IR__::IDLType_ptr ret_type)
{
	out << "\n//\n// " << operation->id() << "\n//\n";
	out << map_psdl_return_type(ret_type, false) << "\n";
	out << class_name_ << "::" << mapName(operation) << "(";

	//
	// parameters
	//
	IR__::ParDescriptionSeq* pards = operation->params();
	CORBA::ULong i;
	for( i=0; i<pards->length(); i++)
	{
		IR__::ParameterDescription pardescr = (*pards)[i];
		if (pardescr.mode == IR__::PARAM_IN) {
			out << map_in_parameter_type (pardescr.type_def) << " " << string(pardescr.name);
		};
		if (pardescr.mode == IR__::PARAM_OUT) {
			out << map_out_parameter_type (pardescr.type_def) << " " << string(pardescr.name);
		};
		if (pardescr.mode == IR__::PARAM_INOUT) {
			out << map_inout_parameter_type (pardescr.type_def) << " " << string(pardescr.name);
		};
		if((i+1)!=pards->length()) { out << ", "; }
	};

	out << ")\n";
	out << "{\n// BEGIN USER INSERT SECTION " << class_name_ << "::" << mapName(operation) << "()\n";
	out << "// END USER INSERT SECTION " << class_name_ << "::" << mapName(operation) << "()\n}\n\n";
}

void
GeneratorPersistenceC::genFactory(IR__::OperationDef_ptr operation, IR__::InterfaceDef_ptr inf_type, IR__::InterfaceDef_ptr inf_home )
{
	out << "\n//\n// " << operation->id() << "\n//\n";
	IR__::IDLType_ptr ret_type = IR__::IDLType::_narrow(inf_type);
	out << map_psdl_return_type(ret_type, false) << "\n";
	out << class_name_ << "::" << mapName(operation) << "(";

	//
	// parameters
	//
	IR__::ParDescriptionSeq* pards = operation->params();
	CORBA::ULong i;
	for( i=0; i<pards->length(); i++)
	{
		IR__::ParameterDescription pardescr = (*pards)[i];
		if (pardescr.mode == IR__::PARAM_IN) {
			out << map_in_parameter_type (pardescr.type_def) << " " << string(pardescr.name);
		};
		if (pardescr.mode == IR__::PARAM_OUT) {
			out << map_out_parameter_type (pardescr.type_def) << " " << string(pardescr.name);
		};
		if (pardescr.mode == IR__::PARAM_INOUT) {
			out << map_inout_parameter_type (pardescr.type_def) << " " << string(pardescr.name);
		};
		if((i+1)!=pards->length()) { out << ", "; }
	};

	out << ")\n";
	out << "{\n";
	out.indent();
	
	IR__::AttributeDefSeq state_members = collectStateMembers(inf_type, CORBA__::dk_Create);
	out << "string strFactory = \"\";\n\n";
	m_strName = "strFactory";
	out << m_strName << " = \"INSERT INTO " << inf_home->name() << " ( pid, spid, ";
	CORBA::ULong len = state_members.length();
	for(i = 0; i < len; i++)
	{
		IR__::AttributeDef_var a_attribute = IR__::AttributeDef::_narrow(state_members[i]);
		out << mapName(a_attribute);
		( (i+1)!=len ) ? out << ", " : out << " ) \";\n";
	}
	m_strContent = "VALUES (";
	out << genSQLLine(m_strName, m_strContent, false, false, true);
	m_strContent = "\\'";
	out << genSQLLine(m_strName, m_strContent, false, false, false);
	m_strContent = "convertPidToString(m_pid)";
	out << genSQLLine(m_strName, m_strContent, false, false, false, true);
	m_strContent = "\\'";
	out << genSQLLine(m_strName, m_strContent, false, true, true);
	m_strContent = "\\'";
	out << genSQLLine(m_strName, m_strContent, false, false, false);
	m_strContent = "convertSpidToString(m_shortPid)";
	out << genSQLLine(m_strName, m_strContent, false, false, false, true);
	m_strContent = "\\'";
	out << genSQLLine(m_strName, m_strContent, false, true, true);

	for(i=0; i<state_members.length(); i++)
	{
		bool bFound = false;
		string strTemp = "";
		IR__::AttributeDef_var a_attribute = IR__::AttributeDef::_narrow(state_members[i]);
		
		for(CORBA::ULong j=0; j<pards->length(); j++)
		{
			IR__::ParameterDescription pardescr = (*pards)[j];	
			strTemp = string(pardescr.name);
			if(strTemp.compare(a_attribute->name())==0)
			{
				bFound = true;
				break;
			}
		}
		
		if(bFound)
		{
			switch(psdl_check_type(a_attribute->type_def()))
			{
			case CPPBase::_SHORT:
				out << "memset(szTemp, \'\\0\', 64);\n";
				out << "sprintf(szTemp, \"%hd\", m_" << strTemp << ");\n";
				if((i+1)!=state_members.length())
					out << m_strName << ".append(strcat(szTemp, \", \"));\n";
				else
					out << m_strName << ".append(strcat(szTemp, \" \"));\n";
				break;
			case CPPBase::_INT:
				out << "memset(szTemp, \'\\0\', 64);\n";
				out << "sprintf(szTemp, \"%d\", m_" << strTemp << ");\n";
				if((i+1)!=state_members.length())
					out << m_strName << ".append(strcat(szTemp, \", \"));\n";
				else
					out << m_strName << ".append(strcat(szTemp, \" \"));\n";
				break;
			case CPPBase::_LONG:
				out << "memset(szTemp, \'\\0\', 64);\n";
				out << "sprintf(szTemp, \"%ld\", m_" << strTemp << ");\n";
				if((i+1)!=state_members.length())
					out << m_strName << ".append(strcat(szTemp, \", \"));\n";
				else
					out << m_strName << ".append(strcat(szTemp, \" \"));\n";
				break;
			case CPPBase::_FLOAT:
				out << "memset(szTemp, \'\\0\', 64);\n";
				out << "sprintf(szTemp, \"%f\", m_" << strTemp << ");\n";
				if((i+1)!=state_members.length())
					out << m_strName << ".append(strcat(szTemp, \", \"));\n";
				else
					out << m_strName << ".append(strcat(szTemp, \" \"));\n";
				break;
			case CPPBase::_DOUBLE:
				out << "memset(szTemp, \'\\0\', 64);\n";
				out << "sprintf(szTemp, \"%lf\", m_" << strTemp << ");\n";
				if((i+1)!=state_members.length())
					out << m_strName << ".append(strcat(szTemp, \", \"));\n";
				else
					out << m_strName << ".append(strcat(szTemp, \" \"));\n";
				break;
			case CPPBase::_LONGDOUBLE:
				out << "memset(szTemp, \'\\0\', 64);\n";
				out << "sprintf(szTemp, \"%Lf\", m_" << strTemp << ");\n";
				if((i+1)!=state_members.length())
					out << m_strName << ".append(strcat(szTemp, \", \"));\n";
				else
					out << m_strName << ".append(strcat(szTemp, \" \"));\n";
				break;
			case CPPBase::_STRING:
				m_strContent = "\\'";
				out << genSQLLine(m_strName, m_strContent, false, false, false);
				m_strContent = "m_" + strTemp;
				out << genSQLLine(m_strName, m_strContent, false, false, false, true);
				m_strContent = "\\'";
				out << genSQLLine(m_strName, m_strContent, false, ((i+1)!=state_members.length()), true);
				break;
			case CPPBase::_BOOL:
				m_strContent = "convertBool2String(m_" + strTemp + ")";
				out << genSQLLine(m_strName, m_strContent, false, ((i+1)!=state_members.length()), false, true);
				m_strContent = "";
				out << genSQLLine(m_strName, m_strContent, false, false, true);
				break;
			}
		}
		else
		{
			m_strContent = "NULL";
			out << genSQLLine(m_strName, m_strContent, false, ((i+1)!=state_members.length()), true);
		}
	}
	m_strContent = ");";
	out << genSQLLine(m_strName, m_strContent, false, false, false);
	out.unindent();
	out << "\n// BEGIN USER INSERT SECTION " << class_name_ << "::" << mapName(operation) << "()\n";
	out << "// END USER INSERT SECTION " << class_name_ << "::" << mapName(operation) << "()\n}\n\n";
}

void
GeneratorPersistenceC::doFactory(IR__::FactoryDef_ptr factory, IR__::InterfaceDef_ptr inf_def)
{
	if(isAbstract)
	{
		IR__::AbstractStorageTypeDef_var abs_storagetype;
		IR__::AbstractStorageHomeDef_var abs_storagehome = IR__::AbstractStorageHomeDef::_narrow(inf_def);
		if(!CORBA::is_nil(abs_storagehome))
			abs_storagetype = abs_storagehome->managed_abstract_storage_type();
		if(!CORBA::is_nil(abs_storagetype))
			genFactory(factory, abs_storagetype, abs_storagehome);
	}
	else
	{
		IR__::StorageTypeDef_var storagetype;
		IR__::StorageHomeDef_var storagehome = IR__::StorageHomeDef::_narrow(inf_def);
		if(!CORBA::is_nil(storagehome))
			storagetype = storagehome->managed_storage_type();
		if(!CORBA::is_nil(storagetype))
			genFactory(factory, storagetype, storagehome);
	}
}

void
GeneratorPersistenceC::doKey(IR__::KeyDef_ptr key, IR__::InterfaceDef_ptr inf_def)
{
	if(isAbstract)
	{
		IR__::AbstractStorageTypeDef_var abs_storagetype;
		IR__::AbstractStorageHomeDef_var abs_storagehome = IR__::AbstractStorageHomeDef::_narrow(inf_def);
		if(!CORBA::is_nil(abs_storagehome))
			abs_storagetype = abs_storagehome->managed_abstract_storage_type();
		if(!CORBA::is_nil(abs_storagetype))
		{
			genKey(key, abs_storagetype, abs_storagehome, false);
			genKey(key, abs_storagetype, abs_storagehome, true);
		}
	}
	else
	{
		//
		//still necessary as the concrete storage home has no relational table?
		//
		IR__::StorageTypeDef_var storagetype;
		IR__::StorageHomeDef_var storagehome = IR__::StorageHomeDef::_narrow(inf_def);
		if(!CORBA::is_nil(storagehome))
			storagetype = storagehome->managed_storage_type();
		if(!CORBA::is_nil(storagetype))
		{
			genKey(key, storagetype, storagehome, false);
			genKey(key, storagetype, storagehome, true);
		}
	}
}

void
GeneratorPersistenceC::genKey(IR__::OperationDef_ptr operation, IR__::InterfaceDef_ptr inf_type, IR__::InterfaceDef_ptr inf_home, bool isRef)
{
	IR__::IDLType_ptr ret_type = IR__::IDLType::_narrow(inf_type);

	if(!isRef)
		out << "\n//\n// " << operation->id() << "\n//\n";
	char* szReturnType = map_psdl_return_type(ret_type, false);

	//since the definition of a abstract stoage type is not yet supported, 
	//we have to replcace the "_ptr" with "&" for operation find_by_ref_... 
	if(isRef)
	{
		char* pdest = strstr( szReturnType, "_ptr" );
		if( pdest != NULL )
		{
			memset(pdest, '\0', 4);
			memset(pdest, '&', 1);
		}
	}
	
	out << szReturnType << "\n" << class_name_ << "::";
	isRef ? out << "find_ref_by_" : out << "find_by_";
	out << mapName(operation) << "(";

	//
	// parameters
	//
	IR__::ParDescriptionSeq* pards = operation->params();
	CORBA::ULong i;
	for( i=0; i<pards->length(); i++)
	{
		IR__::ParameterDescription pardescr = (*pards)[i];
		if (pardescr.mode == IR__::PARAM_IN) {
			out << map_in_parameter_type (pardescr.type_def) << " " << string(pardescr.name);
		};
		if (pardescr.mode == IR__::PARAM_OUT) {
			out << map_out_parameter_type (pardescr.type_def) << " " << string(pardescr.name);
		};
		if (pardescr.mode == IR__::PARAM_INOUT) {
			out << map_inout_parameter_type (pardescr.type_def) << " " << string(pardescr.name);
		};

		if((i+1)!=pards->length()) { out << ", "; }
	};

	out << ")";
	
	if(!isRef)
	{
		out << "\n";
		out.indent();
		out << "throw(CosPersistentState::NotFound";
		handleException(operation);
		out << ")";
		out.unindent();
	}
	
	out << "\n{\n";
	out.indent();

	// make the SQL sentence for select(key)
	out << "char* szTemp = new char[64];\n";
	out << "string strKey = \"\";\n\n";
	m_strName = "strKey";
	m_strContent = "SELECT * FROM ONLY ";
	m_strContent += inf_home->name();
	out << genSQLLine(m_strName, m_strContent, true, false, true);
	m_strContent = "WHERE";
	out << genSQLLine(m_strName, m_strContent, false, false, true);
	for( i=0; i<pards->length(); i++ )
	{
		IR__::ParameterDescription pardescr = (*pards)[i];
		m_strContent = string(pardescr.name);
		if(psdl_check_type(pardescr.type_def)!=CPPBase::_STRING)
			m_strContent += " =";
		else
			m_strContent += " LIKE";
		out << genSQLLine(m_strName, m_strContent, false, false, true);

		switch(psdl_check_type(pardescr.type_def))
		{
		case CPPBase::_SHORT:
			out << "memset(szTemp, \'\\0\', 64);\n";
			out << "sprintf(szTemp, \"%hd\", m_" << string(pardescr.name) << ");\n";
			if((i+1)!=pards->length())
				out << m_strName << ".append(strcat(szTemp, \", \"));\n";
			else
				out << m_strName << ".append(strcat(szTemp, \" \"));\n";
			break;
		case CPPBase::_INT:
			out << "memset(szTemp, \'\\0\', 64);\n";
			out << "sprintf(szTemp, \"%d\", m_" << string(pardescr.name) << ");\n";
			if((i+1)!=pards->length())
				out << m_strName << ".append(strcat(szTemp, \", \"));\n";
			else
				out << m_strName << ".append(strcat(szTemp, \" \"));\n";
			break;
		case CPPBase::_LONG:
			out << "memset(szTemp, \'\\0\', 64);\n";
			out << "sprintf(szTemp, \"%ld\", m_" << string(pardescr.name) << ");\n";
			if((i+1)!=pards->length())
				out << m_strName << ".append(strcat(szTemp, \", \"));\n";
			else
				out << m_strName << ".append(strcat(szTemp, \" \"));\n";
			break;
		case CPPBase::_FLOAT:
			out << "memset(szTemp, \'\\0\', 64);\n";
			out << "sprintf(szTemp, \"%f\", m_" << string(pardescr.name) << ");\n";
			if((i+1)!=pards->length())
				out << m_strName << ".append(strcat(szTemp, \", \"));\n";
			else
				out << m_strName << ".append(strcat(szTemp, \" \"));\n";
			break;
		case CPPBase::_DOUBLE:
			out << "memset(szTemp, \'\\0\', 64);\n";
			out << "sprintf(szTemp, \"%lf\", m_" << string(pardescr.name) << ");\n";
			if((i+1)!=pards->length())
				out << m_strName << ".append(strcat(szTemp, \", \"));\n";
			else
				out << m_strName << ".append(strcat(szTemp, \" \"));\n";
			break;
		case CPPBase::_LONGDOUBLE:
			out << "memset(szTemp, \'\\0\', 64);\n";
			out << "sprintf(szTemp, \"%Lf\", m_" << string(pardescr.name) << ");\n";
			if((i+1)!=pards->length())
				out << m_strName << ".append(strcat(szTemp, \", \"));\n";
			else
				out << m_strName << ".append(strcat(szTemp, \" \"));\n";
			break;
		case CPPBase::_STRING:
			m_strContent = "\\'";
			out << genSQLLine(m_strName, m_strContent, false, false, false);
			m_strContent = "m_" + string(pardescr.name);
			out << genSQLLine(m_strName, m_strContent, false, false, false, true);
			m_strContent = "\\'";
			out << genSQLLine(m_strName, m_strContent, false, ((i+1)!=pards->length()), true);
			break;
		case CPPBase::_BOOL:
			m_strContent = "convertBool2String(m_" + string(pardescr.name) + ")";
			out << genSQLLine(m_strName, m_strContent, false, ((i+1)!=pards->length()), false, true);
			m_strContent = "";
			out << genSQLLine(m_strName, m_strContent, false, false, true);
			break;
		}
	}
	m_strContent = ");";
	out << genSQLLine(m_strName, m_strContent, false, false, false);
	out.unindent();

	out << "\n// BEGIN USER INSERT SECTION " << class_name_;
	isRef ? out << "::find_ref_by_" : out << "::find_by_";
	out << mapName(operation) << "()\n";
	out << "// END USER INSERT SECTION " << class_name_;
	isRef ? out << "::find_ref_by_" : out << "::find_by_";
	out << mapName(operation) << "()\n}\n\n";
}

void 
GeneratorPersistenceC::doException(IR__::ExceptionDef_ptr except)
{
	out << ", " << mapFullName(except);
}

void
GeneratorPersistenceC::genAbstractObjsForConcreteType(IR__::AbstractStorageTypeDef_ptr abs_storage_type)
{
	IR__::InterfaceDefSeq_var abs_storage_types = abs_storage_type->base_abstract_storage_types();
	for(CORBA::ULong i = 0; i < abs_storage_types->length(); i++) 
	{
		IR__::AbstractStorageTypeDef_ptr abs_storage_type_inh;
		abs_storage_type_inh = IR__::AbstractStorageTypeDef::_narrow((*abs_storage_types)[i]);
		handleAttribute(abs_storage_type_inh);
		handleOperation(abs_storage_type_inh);
	}

	handleAttribute(abs_storage_type);
	handleOperation(abs_storage_type);
}

void 
GeneratorPersistenceC::doStorageType(IR__::StorageTypeDef_ptr storage_type)
{
	class_name_ = string(storage_type->name());

	IR__::InterfaceDefSeq_var supported_infs = storage_type->supported_interfaces();
	if(supported_infs->length()!=1)
		throw CORBA::BAD_PARAM(); // is this exception appropriate?
	IR__::AbstractStorageTypeDef_var abs_storagetype;
	abs_storagetype = IR__::AbstractStorageTypeDef::_narrow((*supported_infs)[0]);

	// achtung: wenn kein modul, sollte vielleicht PSS_ der prefix für alle pss sein?
	out << "\n\n";	
	open_module(out, storage_type, "");
	out << "\n\n";
	out << "// BEGIN USER INSERT SECTION " << class_name_ << "\n";
	out << "// END USER INSERT SECTION " << class_name_ << "\n\n";
	out << class_name_ << "::" << class_name_ << "()\n";
	out << "{\n";
	out.indent();
	out << "char* szTemp = new char[64];\n\n";
	genSQLSentences(abs_storagetype, sql_SELECT);
	genSQLSentences(abs_storagetype, sql_UPDATE);
	out.unindent();
	out << "// BEGIN USER INSERT SECTION " << class_name_ << "::" << class_name_ << "()\n";
	out << "// END USER INSERT SECTION " <<class_name_ << "::" << class_name_ << "()\n}\n\n";
	out << class_name_ << "::~" << class_name_ << "()\n";
	out << "{\n// BEGIN USER INSERT SECTION " << class_name_ << "::~" << class_name_ << "()\n";
	out << "// END USER INSERT SECTION " <<class_name_ << "::~" << class_name_ << "()\n}\n\n";

	/*
	for(CORBA::ULong i = 0; i < supported_infs->length(); i++) 
	{
		IR__::AbstractStorageTypeDef_ptr abs_storage_type_inh;
		abs_storage_type_inh = IR__::AbstractStorageTypeDef::_narrow((*supported_infs)[i]);
		genAbstractObjsForConcreteType(abs_storage_type_inh);
	};
	*/
	genAbstractObjsForConcreteType(abs_storagetype);

	handleAttribute(storage_type);
	handleOperation(storage_type);

	out << "void\n";
	out << class_name_ << "::" << "setValue(map<string, CORBA::Any> valueMap)\n";
	out << "{\n";
	out.indent();
	out << "//pid = \n//spid = \n";
	out.unindent();
	out << "}\n\n";

	close_module(out, storage_type);
}

void
GeneratorPersistenceC::genAbstractObjsForConcreteHome(IR__::AbstractStorageHomeDef_ptr abs_storage_home)
{
	IR__::InterfaceDefSeq_var abs_storage_homes = abs_storage_home->base_abstract_storage_homes();
	for(CORBA::ULong i = 0; i < abs_storage_homes->length(); i++) 
	{
		IR__::AbstractStorageHomeDef_ptr abs_storage_home_inh;
		abs_storage_home_inh = IR__::AbstractStorageHomeDef::_narrow((*abs_storage_homes)[i]);
		isAbstract = true;
		handleAttribute(abs_storage_home_inh);
		handleOperation(abs_storage_home_inh);
		handleFactory(abs_storage_home_inh);
		handleKey(abs_storage_home_inh);
	}

	isAbstract = true;
	handleAttribute(abs_storage_home);
	handleOperation(abs_storage_home);
	handleFactory(abs_storage_home);
	handleKey(abs_storage_home);
}

void 
GeneratorPersistenceC::doStorageHome(IR__::StorageHomeDef_ptr storage_home)
{
	m_storagehome = IR__::StorageHomeDef::_duplicate(storage_home);
	m_storagetype = IR__::StorageTypeDef::_duplicate(storage_home->managed_storage_type());

	IR__::InterfaceDefSeq_var supported_infs = storage_home->supported_interfaces();
	if(supported_infs->length()!=1)
		throw CORBA::BAD_PARAM(); // is this exception appropriate?
	IR__::AbstractStorageHomeDef_var abs_storagehome;
	abs_storagehome = IR__::AbstractStorageHomeDef::_narrow((*supported_infs)[0]);
	m_SthMap.insert( Sth_Pair(abs_storagehome->managed_abstract_storage_type()->name(), abs_storagehome->name()) );

	// achtung: wenn kein modul, sollte vielleicht PSS_ der prefix für alle pss sein?
	out << "\n\n";
	open_module(out, m_storagetype, "");
	out << "\n\n";

	class_name_ = string(storage_home->name());
	out << "// BEGIN USER INSERT SECTION " << class_name_ << "\n";
	out << "// END USER INSERT SECTION " << class_name_ << "\n\n";
	out << class_name_ << "::" << class_name_ << "()\n";
	// init member variables
	out << "{\n";
	out.indent();
	genSQLSentences(abs_storagehome, sql_CREATE);
	out.unindent();
	out << "// BEGIN USER INSERT SECTION " << class_name_ << "::" << class_name_ << "()\n";
	out << "// END USER INSERT SECTION " <<class_name_ << "::" << class_name_ << "()\n}\n\n";
	out << class_name_ << "::~" << class_name_ << "()\n";
	out << "{\n// BEGIN USER INSERT SECTION " << class_name_ << "::~" << class_name_ << "()\n";
	out << "// END USER INSERT SECTION " <<class_name_ << "::~" << class_name_ << "()\n}\n\n";
	
	genCreateOperation(storage_home, false);
	genCreateOperation(storage_home, true);

	/*
	for(CORBA::ULong i = 0; i < supported_infs->length(); i++)
	{
		IR__::AbstractStorageHomeDef_var abs_storagehome;
		abs_storagehome = IR__::AbstractStorageHomeDef::_narrow((*supported_infs)[i]);
		genAbstractObjsForConcreteHome(abs_storagehome);
	};
	*/
	genAbstractObjsForConcreteHome(abs_storagehome);

	isAbstract = false;
	handleAttribute(storage_home);
	handleOperation(storage_home);
	handleFactory(storage_home);
	handleKey(storage_home);

	close_module(out, m_storagetype);
}

void
GeneratorPersistenceC::genCreateOperation(IR__::StorageHomeDef_ptr storage_home, bool isRef)
{
	int iLength = class_name_.length() + 10;
	string strDummy = "";
	char* szDisplay = map_psdl_return_type(storage_home->managed_storage_type(), false);
		
	if(isRef)
	{
		char* pdest = strstr( szDisplay, "*" );
		if( pdest != NULL )
		{
			memset(pdest, '\0', 1);
			strcat(szDisplay, "Ref");
		}
	}
	
	out << szDisplay << "\n" << class_name_ << "::_create(";
	
	IR__::AttributeDefSeq state_members;
	storage_home->managed_storage_type()->get_StateMembers(state_members, CORBA__::dk_Create);
	CORBA::ULong len = state_members.length();
	for(CORBA::ULong i = 0; i < len; i++)
	{
		IR__::AttributeDef_var a_attribute = IR__::AttributeDef::_narrow(state_members[i]);
		out << map_in_parameter_type(a_attribute->type_def()) << " " << mapName(a_attribute);
		if( (i+1)!=len )
		{
			out << ",\n";
			strDummy = "";
			strDummy.append(iLength, ' ');
			out << strDummy.c_str();
		}
	}
	
	if(isRef)
	{
		strDummy = "";
		strDummy.append(iLength, ' ');
		out << ",\n" << strDummy.c_str() << "CosPersistentState::YieldRef yr";
	}

	out << ")\n"; 

	IR__::InterfaceDefSeq_var supported_infs = storage_home->supported_interfaces();
	if(supported_infs->length()!=1)
		throw CORBA::BAD_PARAM(); // is this exception appropriate?
	IR__::AbstractStorageHomeDef_var abs_storagehome;
	abs_storagehome = IR__::AbstractStorageHomeDef::_narrow((*supported_infs)[0]);

	out << "{\n";
	out.indent();
	// make the SQL sentence for insert
	out << "string strInsert = \"\";\n\n";
	m_strName = "strInsert";
	out << m_strName << " = \"INSERT INTO " << abs_storagehome->name() << " ( pid, spid, ";
	for(i = 0; i < len; i++)
	{
		IR__::AttributeDef_var a_attribute = IR__::AttributeDef::_narrow(state_members[i]);
		out << mapName(a_attribute);
		( (i+1)!=len ) ? out << ", " : out << " ) \";\n";
	}
	m_strContent = "VALUES (";
	out << genSQLLine(m_strName, m_strContent, false, false, true);
	m_strContent = "\\'";
	out << genSQLLine(m_strName, m_strContent, false, false, false);
	m_strContent = "convertPidToString(m_pid)";
	out << genSQLLine(m_strName, m_strContent, false, false, false, true);
	m_strContent = "\\'";
	out << genSQLLine(m_strName, m_strContent, false, true, true);
	m_strContent = "\\'";
	out << genSQLLine(m_strName, m_strContent, false, false, false);
	m_strContent = "convertSpidToString(m_shortPid)";
	out << genSQLLine(m_strName, m_strContent, false, false, false, true);
	m_strContent = "\\'";
	out << genSQLLine(m_strName, m_strContent, false, true, true);

	for(unsigned int i=0; i<len; i++)
	{
		IR__::AttributeDef_var a_attribute = IR__::AttributeDef::_narrow(state_members[i]);

		switch(psdl_check_type(a_attribute->type_def()))
		{
		case CPPBase::_SHORT:
			out << "memset(szTemp, \'\\0\', 64);\n";
			out << "sprintf(szTemp, \"%hd\", m_" << mapName(a_attribute) << ");\n";
			if((i+1)!=state_members.length())
				out << m_strName << ".append(strcat(szTemp, \", \"));\n";
			else
				out << m_strName << ".append(strcat(szTemp, \" \"));\n";
			break;
		case CPPBase::_INT:
			out << "memset(szTemp, \'\\0\', 64);\n";
			out << "sprintf(szTemp, \"%d\", m_" << mapName(a_attribute) << ");\n";
			if((i+1)!=state_members.length())
				out << m_strName << ".append(strcat(szTemp, \", \"));\n";
			else
				out << m_strName << ".append(strcat(szTemp, \" \"));\n";
			break;
		case CPPBase::_LONG:
			out << "memset(szTemp, \'\\0\', 64);\n";
			out << "sprintf(szTemp, \"%ld\", m_" << mapName(a_attribute) << ");\n";
			if((i+1)!=state_members.length())
				out << m_strName << ".append(strcat(szTemp, \", \"));\n";
			else
				out << m_strName << ".append(strcat(szTemp, \" \"));\n";
			break;
		case CPPBase::_FLOAT:
			out << "memset(szTemp, \'\\0\', 64);\n";
			out << "sprintf(szTemp, \"%f\", m_" << mapName(a_attribute) << ");\n";
			if((i+1)!=state_members.length())
				out << m_strName << ".append(strcat(szTemp, \", \"));\n";
			else
				out << m_strName << ".append(strcat(szTemp, \" \"));\n";
			break;
		case CPPBase::_DOUBLE:
			out << "memset(szTemp, \'\\0\', 64);\n";
			out << "sprintf(szTemp, \"%lf\", m_" << mapName(a_attribute) << ");\n";
			if((i+1)!=state_members.length())
				out << m_strName << ".append(strcat(szTemp, \", \"));\n";
			else
				out << m_strName << ".append(strcat(szTemp, \" \"));\n";
			break;
		case CPPBase::_LONGDOUBLE:
			out << "memset(szTemp, \'\\0\', 64);\n";
			out << "sprintf(szTemp, \"%Lf\", m_" << mapName(a_attribute) << ");\n";
			if((i+1)!=state_members.length())
				out << m_strName << ".append(strcat(szTemp, \", \"));\n";
			else
				out << m_strName << ".append(strcat(szTemp, \" \"));\n";
			break;
		case CPPBase::_STRING:
			m_strContent = "\\'";
			out << genSQLLine(m_strName, m_strContent, false, false, false);
			m_strContent = "m_" + mapName(a_attribute);
			out << genSQLLine(m_strName, m_strContent, false, false, false, true);
			m_strContent = "\\'";
			out << genSQLLine(m_strName, m_strContent, false, ((i+1)!=state_members.length()), true);
			break;
		case CPPBase::_BOOL:
			m_strContent = "convertBool2String(m_" + mapName(a_attribute) + ")";
			out << genSQLLine(m_strName, m_strContent, false, ((i+1)!=state_members.length()), false, true);
			m_strContent = "";
			out << genSQLLine(m_strName, m_strContent, false, false, true);
			break;
		}
	}
	m_strContent = ");";
	out << genSQLLine(m_strName, m_strContent, false, false, false);
	out.unindent();
	out << "\n// BEGIN USER INSERT SECTION " << class_name_ << "::_create()\n";
	out << "// END USER INSERT SECTION " << class_name_ << "::_create()\n}\n\n";
}

string
GeneratorPersistenceC::genSQLLine(string strName, string strContent, bool start, bool comma, bool space, bool func)
{
	string strRet = strName;

	start ? strRet += " = " : strRet += " += ";
	if(!func) strRet += "\"";
	strRet += strContent;
	if(comma) strRet += ",";
	if(space) strRet += " ";
	if(!func) strRet += "\"";
	strRet += ";\n";

	return strRet;
}

void
GeneratorPersistenceC::genSQLSentences(IR__::AbstractStorageHomeDef_ptr abs_storage_home, SQLFunc sf)
{
	m_strContent = "";
	m_strName= "";
	IR__::AttributeDefSeq state_members;
	abs_storage_home->managed_abstract_storage_type()->get_StateMembers(state_members, CORBA__::dk_Self);
	IR__::InterfaceDefSeq_var base_abs_storagetypes = abs_storage_home->managed_abstract_storage_type()->base_abstract_storage_types();

	switch(sf)
	{
	case sql_CREATE:
		m_strName = "strCreateTable";
		m_strContent = "CREATE TABLE ";
		m_strContent += abs_storage_home->name();
		m_strContent += " (";
		out << genSQLLine(m_strName, m_strContent, true, false, true);

		if(base_abs_storagetypes->length()==0)
		{
			m_strContent = "pid  TEXT  NOT NULL  REFERENCES PID_CONTENT";
			out << genSQLLine(m_strName, m_strContent, false, true, true);
			m_strContent = "spid  TEXT";
			out << genSQLLine(m_strName, m_strContent, false, true, true);
		}

		for(unsigned int i=0; i<state_members.length(); i++)
		{
			IR__::AttributeDef_var a_attribute = IR__::AttributeDef::_narrow(state_members[i]);
			m_strContent = mapName(a_attribute);
			m_strContent += "  ";
			m_strContent.append( map_psdl2sql_type(a_attribute->type_def()) );
			bool isComma = ((i+1)!=state_members.length()) || (base_abs_storagetypes->length()==0);
			out << genSQLLine(m_strName, m_strContent, false, isComma, true);
		}

		if(base_abs_storagetypes->length()>0)
		{
			m_strContent = ") INHERITS ( ";
			for(unsigned int j=0; j<base_abs_storagetypes->length(); j++)
			{
				m_strContent.append(((*base_abs_storagetypes)[j])->name());
				
				if((j+1)!=base_abs_storagetypes->length())
					m_strContent += ", ";
				else
                    m_strContent += " );";

				out << genSQLLine(m_strName, m_strContent, false, false, false);
			}
		}
		else
		{
			m_strContent = "CONSTRAINT PK_";
			m_strContent += abs_storage_home->name();
			m_strContent += " PRIMARY KEY (pid)";
			out << genSQLLine(m_strName, m_strContent, false, false, true);
			m_strContent = ");";
			out << genSQLLine(m_strName, m_strContent, false, false, false);
		}

		out << "\n";
		break;
	case sql_SELECT:
		break;
	case sql_UPDATE:
		break;
	case sql_INSERT:
		break;
	case sql_DELETE:
		break;
	default:
		return;
	}
}

void
GeneratorPersistenceC::genSQLSentences(IR__::AbstractStorageTypeDef_ptr abs_storage_type, SQLFunc sf)
{
	m_strContent = "";
	m_strName= "";
	IR__::AttributeDefSeq state_members;
	abs_storage_type->get_StateMembers(state_members, CORBA__::dk_Variable);
	IR__::InterfaceDefSeq_var base_abs_storagetypes = abs_storage_type->base_abstract_storage_types();

	switch(sf)
	{
	case sql_SELECT:
		m_strName = "m_strSelect";
		m_strContent = "SELECT * FROM ONLY ";
		m_SthIter = m_SthMap.find(abs_storage_type->name());
		m_strContent += m_SthIter->second;
		out << genSQLLine(m_strName, m_strContent, true, false, true);
		m_strContent = "WHERE pid LIKE \\'";
		out << genSQLLine(m_strName, m_strContent, false, false, false);
		m_strContent = "convertPidToString(m_pid)";
		out << genSQLLine(m_strName, m_strContent, false, false, false, true);
		m_strContent = "\\';";
		out << genSQLLine(m_strName, m_strContent, false, false, false);
		out << "\n";
		break;
	case sql_UPDATE:
		m_strName = "m_strUpdate";
		m_strContent = "UPDATE ";
		m_SthIter = m_SthMap.find(abs_storage_type->name());
		m_strContent += m_SthIter->second;
		m_strContent += " SET";
		out << genSQLLine(m_strName, m_strContent, true, false, true);
		for(unsigned int i=0; i<state_members.length(); i++)
		{
			IR__::AttributeDef_var a_attribute = IR__::AttributeDef::_narrow(state_members[i]);
			m_strContent = mapName(a_attribute) + " = ";

			switch(psdl_check_type(a_attribute->type_def()))
			{
			case CPPBase::_SHORT:
				out << genSQLLine(m_strName, m_strContent, false, false, false);
				out << "memset(szTemp, \'\\0\', 64);\n";
				out << "sprintf(szTemp, \"%hd\", m_" << mapName(a_attribute) << ");\n";
				if((i+1)!=state_members.length())
					out << m_strName << ".append(strcat(szTemp, \", \"));\n";
				else
					out << m_strName << ".append(strcat(szTemp, \" \"));\n";
				break;
			case CPPBase::_INT:
				out << genSQLLine(m_strName, m_strContent, false, false, false);
				out << "memset(szTemp, \'\\0\', 64);\n";
				out << "sprintf(szTemp, \"%d\", m_" << mapName(a_attribute) << ");\n";
				if((i+1)!=state_members.length())
					out << m_strName << ".append(strcat(szTemp, \", \"));\n";
				else
					out << m_strName << ".append(strcat(szTemp, \" \"));\n";
				break;
			case CPPBase::_LONG:
				out << genSQLLine(m_strName, m_strContent, false, false, false);
				out << "memset(szTemp, \'\\0\', 64);\n";
				out << "sprintf(szTemp, \"%ld\", m_" << mapName(a_attribute) << ");\n";
				if((i+1)!=state_members.length())
					out << m_strName << ".append(strcat(szTemp, \", \"));\n";
				else
					out << m_strName << ".append(strcat(szTemp, \" \"));\n";
				break;
			case CPPBase::_FLOAT:
				out << genSQLLine(m_strName, m_strContent, false, false, false);
				out << "memset(szTemp, \'\\0\', 64);\n";
				out << "sprintf(szTemp, \"%f\", m_" << mapName(a_attribute) << ");\n";
				if((i+1)!=state_members.length())
					out << m_strName << ".append(strcat(szTemp, \", \"));\n";
				else
					out << m_strName << ".append(strcat(szTemp, \" \"));\n";
				break;
			case CPPBase::_DOUBLE:
				out << genSQLLine(m_strName, m_strContent, false, false, false);
				out << "memset(szTemp, \'\\0\', 64);\n";
				out << "sprintf(szTemp, \"%lf\", m_" << mapName(a_attribute) << ");\n";
				if((i+1)!=state_members.length())
					out << m_strName << ".append(strcat(szTemp, \", \"));\n";
				else
					out << m_strName << ".append(strcat(szTemp, \" \"));\n";
				break;
			case CPPBase::_LONGDOUBLE:
				out << genSQLLine(m_strName, m_strContent, false, false, false);
				out << "memset(szTemp, \'\\0\', 64);\n";
				out << "sprintf(szTemp, \"%Lf\", m_" << mapName(a_attribute) << ");\n";
				if((i+1)!=state_members.length())
					out << m_strName << ".append(strcat(szTemp, \", \"));\n";
				else
					out << m_strName << ".append(strcat(szTemp, \" \"));\n";
				break;
			case CPPBase::_STRING:
				m_strContent += "\\'";
				out << genSQLLine(m_strName, m_strContent, false, false, false);
				m_strContent = "m_" + mapName(a_attribute);
				out << genSQLLine(m_strName, m_strContent, false, false, false, true);
				m_strContent = "\\'";
				out << genSQLLine(m_strName, m_strContent, false, ((i+1)!=state_members.length()), true);
				break;
			case CPPBase::_BOOL:
				out << genSQLLine(m_strName, m_strContent, false, false, false);
				m_strContent = "convertBool2String(m_" + mapName(a_attribute) + ")";
				out << genSQLLine(m_strName, m_strContent, false, ((i+1)!=state_members.length()), false, true);
				m_strContent = "";
				out << genSQLLine(m_strName, m_strContent, false, false, true);
				break;
			}
		}
	
		m_strContent = "WHERE pid LIKE \\'";
		out << genSQLLine(m_strName, m_strContent, false, false, false);
		m_strContent = "convertPidToString(m_pid)";
		out << genSQLLine(m_strName, m_strContent, false, false, false, true);
		m_strContent = "\\';";
		out << genSQLLine(m_strName, m_strContent, false, false, false);
		out << "\n";
		break;
	case sql_INSERT:
	case sql_DELETE:
		break;
	default:
		return;
	}
}

IR__::AttributeDefSeq 
GeneratorPersistenceC::collectStateMembers(IR__::InterfaceDef_ptr inf_def, CORBA__::CollectStyle style)
{
	IR__::AttributeDefSeq state_members;

	IR__::AbstractStorageTypeDef_ptr abs_storagetype;
	abs_storagetype = IR__::AbstractStorageTypeDef::_narrow(inf_def);
	if(!CORBA::is_nil(abs_storagetype))
		abs_storagetype->get_StateMembers(state_members, style);

	IR__::StorageTypeDef_ptr storagetype;
	storagetype = IR__::StorageTypeDef::_narrow(inf_def);
	if(!CORBA::is_nil(storagetype))
		storagetype->get_StateMembers(state_members, style);

	return state_members;
}

} // namespace
