/*****************************************************************************/
/* Qedo - Quality of Service Enabled Distributed Objects                     */
/*                                                                           */
/* Copyright (c) 2002/2003 by the Qedo Team                                  */
/*                                                                           */
/* http://qedo.berlios.de                                                    */
/*                                                                           */
/* This file is part of Qedo Generator                                       */
/*                                                                           */
/* Qedo Generator is free software; you can redistribute it and/or modify    */
/* it under the terms of the GNU General Public License as published by      */
/* the Free Software Foundation; either version 2 of the License, or         */
/* (at your option) any later version.                                       */
/*                                                                           */
/* Qedo Generator is distributed in the hope that it will be useful,         */
/* but WITHOUT ANY WARRANTY; without even the implied warranty of            */
/* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the             */
/* GNU General Public License for more details.                              */
/*                                                                           */
/* You should have received a copy of the GNU General Public License         */
/* along with Foobar; if not, write to the Free Software                     */
/* Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA */
/*                                                                           */
/*****************************************************************************/
#include "GeneratorPersistenceH.h"


namespace QEDO_CIDL_Generator {

GeneratorPersistenceH::GeneratorPersistenceH
( QEDO_ComponentRepository::CIDLRepository_impl *repository)
: CPPBase(repository), 
  m_isAbstract(true), 
  m_isASHKey(true)
{
}

GeneratorPersistenceH::~GeneratorPersistenceH
()
{
}

void
GeneratorPersistenceH::generate(std::string target, std::string fileprefix)
{
	try { initialize(target, fileprefix); }
	catch (InitializeError) { return; }
	
	m_filename = file_prefix_ + "_PSS.h";
	
	out.open(m_filename.c_str());
	out << "//\n";
	out << "// generated by Qedo\n";
	out << "//\n\n";
	out << "#ifndef _" << file_prefix_ << "_PSS_H_\n";
	out << "#define _" << file_prefix_ << "_PSS_H_\n\n\n";
	out << "// BEGIN USER INSERT SECTION file_pre\n";
	out << "// END USER INSERT SECTION file_pre\n\n";
	out << "#include <CORBA.h>\n";
	out << "#include \"CORBADepends.h\"\n";
	out << "#include \"StorageObject.h\"\n";
	out << "#include \"StorageHomeBase.h\"\n";
	out << "#include \"Catalog.h\"\n";
	out << "#include \"PSSHelper.h\"\n\n";
	out << "using namespace Qedo;\n\n";
	out << "// BEGIN USER INSERT SECTION file_post\n";
	out << "// END USER INSERT SECTION file_post\n";

	doGenerate();

	out << "\n#endif\n";
	out.close();
}

void
GeneratorPersistenceH::check_for_generation(IR__::Contained_ptr item)
{
	// check if item is already known
	if (item_well_known(item))
		return;

	// check if item is already in the list or currently processed
	if ((this->m_recursion_set.find(item->id())) != m_recursion_set.end() || this->already_included (item))
		return;
	else
		m_recursion_set.insert(item->id());

	CORBA::ULong i;
	CORBA::ULong ulLen;

	switch (item->def_kind())
	{
	case CORBA__::dk_Module : 
	{
		IR__::ModuleDef_var a_module = IR__::ModuleDef::_narrow(item);

		// modules
		IR__::ContainedSeq_var contained_seq = a_module->contents(CORBA__::dk_Module, true);
		ulLen = contained_seq->length();
		for(i=0; i<ulLen; i++)
			check_for_generation((*contained_seq)[i]);

		// abstract storagehomes
		contained_seq = a_module->contents(CORBA__::dk_AbstractStorageHome, true);
		ulLen = contained_seq->length();
		for(i=0; i<ulLen; i++)
			check_for_generation((*contained_seq)[i]);

		// storagehomes
		contained_seq = a_module->contents(CORBA__::dk_StorageHome, true);
		ulLen = contained_seq->length();
		for(i=0; i<ulLen; i++)
			check_for_generation((*contained_seq)[i]);

		break; 
	}
	case CORBA__::dk_AbstractStorageType :
	{
		IR__::AbstractStorageTypeDef_var abs_storagetype = IR__::AbstractStorageTypeDef::_narrow(item);
		// insert this interface in generation list
		this->insert_to_generate(item);

		break;
	}
	case CORBA__::dk_StorageType :
	{
		IR__::StorageTypeDef_var storagetype = IR__::StorageTypeDef::_narrow(item);
		// insert this interface in generation list
		this->insert_to_generate(item);

		break;
	}
    case CORBA__::dk_AbstractStorageHome :
	{
		IR__::AbstractStorageHomeDef_var abs_storagehome = IR__::AbstractStorageHomeDef::_narrow(item);
		// insert this interface in generation list
		this->insert_to_generate(item);

		// managed abstract storage type
		IR__::AbstractStorageTypeDef_var abs_storagetype = abs_storagehome->managed_abstract_storagetype();
		this->check_for_generation(abs_storagetype);

		break;
	}
	case CORBA__::dk_StorageHome : 
	{
		IR__::StorageHomeDef_var storagehome = IR__::StorageHomeDef::_narrow(item);
		// insert this interface in generation list
		this->insert_to_generate(item);

		// managed storage type
		IR__::StorageTypeDef_var storagetype = storagehome->managed_storagetype();
		this->check_for_generation(storagetype);

		break;
	}
	default:
		break;
	};

	m_recursion_set.erase(item->id());
};

void
GeneratorPersistenceH::genAttribute(IR__::StorageTypeDef_ptr storagetype)
{
	IR__::AttributeDefSeq state_members;
	storagetype->get_state_members(state_members, CORBA__::dk_Variable);
	CORBA::ULong ulLen = state_members.length();
	
	out << "private:\n\n";
	out.indent();

	for(CORBA::ULong i=0; i<ulLen; i++)
	{
		IR__::AttributeDef_var attribute = IR__::AttributeDef::_narrow(state_members[i]);
		std::string attribute_name = mapName(attribute);
		out << map_attribute_type(attribute->type_def()) << " m_" << attribute_name << ";\n";
	}

	out.unindent();
}

void
GeneratorPersistenceH::doAttribute(IR__::AttributeDef_ptr attribute)
{
	out << "\n//\n// " << attribute->id() << "\n//\n";
	std::string attribute_name = mapName(attribute);
	IR__::IDLType_var attr_type = attribute->type_def();
		
	// read only
	if(m_isAbstract) out << "virtual ";
	out << map_psdl_return_type(attr_type, true) << " " << attribute_name << "() const";
	m_isAbstract ? out << " = 0;\n" : out << ";\n";

	// not read only
	if(attribute->mode() == IR__::ATTR_NORMAL)
	{
		switch ( attr_type->type()->kind() )
		{
			case CORBA::tk_string:
			case CORBA::tk_wstring:
				if(m_isAbstract) out << "virtual ";
				out << map_psdl_return_type(attr_type, false) << " " << attribute_name << "(";
				out << map_psdl_parameter_type(attr_type, false) << " param)";
				m_isAbstract ? out << " = 0;\n" : out << ";\n";
		}

		if(m_isAbstract) out << "virtual ";
		out << "void " << attribute_name << "(";
		out << map_psdl_parameter_type(attr_type, true) << " param)";
		m_isAbstract ? out << " = 0;\n" : out << ";\n";

		// the fourth operation only for string and wstring
		if(attr_type->type()->kind()==CORBA::tk_string)
		{
			if(m_isAbstract) out << "virtual ";
			out << "void " << attribute_name << "(CORBA::String_var& param)";
			m_isAbstract ? out << " = 0;\n" : out << ";\n";
		}
		else if(attr_type->type()->kind()==CORBA::tk_wstring)
		{
			if(m_isAbstract) out << "virtual ";
			out << "void " << attribute_name << "(CORBA::WString_var& param)";
			m_isAbstract ? out << " = 0;\n" : out << ";\n";
		}
	}
}

void
GeneratorPersistenceH::genOperation(IR__::OperationDef_ptr operation, IR__::IDLType_ptr ret_type)
{
	out << "\n//\n// " << operation->id() << "\n//\n";
	if(m_isAbstract) out << "virtual ";
	out << map_psdl_return_type(ret_type, false) << " " << mapName(operation) << "(";

	// parameters
	IR__::ParDescriptionSeq_var pards = operation->params();
	for( CORBA::ULong i=0; i<pards->length(); i++)
	{
		IR__::ParameterDescription pardescr = (*pards)[i];
		if (pardescr.mode == IR__::PARAM_IN) {
			out << map_in_parameter_type (pardescr.type_def) << " " << string(pardescr.name);
		};
		if (pardescr.mode == IR__::PARAM_OUT) {
			out << map_out_parameter_type (pardescr.type_def) << " " << string(pardescr.name);
		};
		if (pardescr.mode == IR__::PARAM_INOUT) {
			out << map_inout_parameter_type (pardescr.type_def) << " " << string(pardescr.name);
		};
		if((i+1)!=pards->length()) { out << ", "; }
	};

	m_isAbstract ? out << ") = 0;\n" : out << ");\n";
}

void
GeneratorPersistenceH::doOperation(IR__::OperationDef_ptr operation)
{
	genOperation(operation, operation->result_def());
}

void
GeneratorPersistenceH::doFactory(IR__::FactoryDef_ptr factory, IR__::InterfaceDef_ptr inf_def)
{
	if( (m_isAbstract==TRUE) || (m_isAbstract==FALSE && m_isASHKey==TRUE) )
	{
		IR__::AbstractStorageTypeDef_var abs_storagetype;
		IR__::AbstractStorageHomeDef_var abs_storagehome = IR__::AbstractStorageHomeDef::_narrow(inf_def);
		if(!CORBA::is_nil(abs_storagehome))
			abs_storagetype = abs_storagehome->managed_abstract_storagetype();
		if(!CORBA::is_nil(abs_storagetype))
			genOperation(factory, abs_storagetype);
	}
	else
	{
		IR__::StorageTypeDef_var storagetype;
		IR__::StorageHomeDef_var storagehome = IR__::StorageHomeDef::_narrow(inf_def);
		if(!CORBA::is_nil(storagehome))
			storagetype = storagehome->managed_storagetype();
		if(!CORBA::is_nil(storagetype))
			genOperation(factory, storagetype);
	}
}

void
GeneratorPersistenceH::genKey(IR__::OperationDef_ptr operation, IR__::IDLType_ptr ret_type, bool isRef)
{
	if(!isRef) out << "\n//\n// " << operation->id() << "\n//\n";
	if(m_isAbstract) out << "virtual ";
	char* szReturnType = map_psdl_return_type(ret_type, false);

	//since the definition of a abstract stoage type is not yet supported, 
	//we have to replcace the "_ptr" with "&" for operation find_by_ref_... 
	if(isRef)
	{
		char* pdest = strstr( szReturnType, "*" );
		if( pdest != NULL )
			memset(pdest, '&', 1);
	}
	
	out << szReturnType;
	isRef ? out << " find_ref_by_" : out << " find_by_";
	out << mapName(operation) << "(";

	// parameters
	IR__::ParDescriptionSeq* pards = operation->params();
	for( CORBA::ULong i=0; i<pards->length(); i++)
	{
		IR__::ParameterDescription pardescr = (*pards)[i];
		if (pardescr.mode == IR__::PARAM_IN) {
			out << map_in_parameter_type (pardescr.type_def) << " " << string(pardescr.name);
		};
		if (pardescr.mode == IR__::PARAM_OUT) {
			out << map_out_parameter_type (pardescr.type_def) << " " << string(pardescr.name);
		};
		if (pardescr.mode == IR__::PARAM_INOUT) {
			out << map_inout_parameter_type (pardescr.type_def) << " " << string(pardescr.name);
		};
		if((i+1)!=pards->length()) { out << ", "; }
	};

	out << ")";
	
	if(!isRef)
	{
		out << "\n";
		out.indent();
		out << "throw(CosPersistentState::NotFound";
		handleException(operation);
		out << ")";
		out.unindent();
	}
	
	m_isAbstract ? out << " = 0;\n" : out << ";\n";
}

void
GeneratorPersistenceH::doKey(IR__::KeyDef_ptr key, IR__::InterfaceDef_ptr inf_def)
{
	if( (m_isAbstract==TRUE) || (m_isAbstract==FALSE && m_isASHKey==TRUE) )
	{
		IR__::AbstractStorageTypeDef_var abs_storagetype;
		IR__::AbstractStorageHomeDef_var abs_storagehome = IR__::AbstractStorageHomeDef::_narrow(inf_def);
		if(!CORBA::is_nil(abs_storagehome))
			abs_storagetype = abs_storagehome->managed_abstract_storagetype();
		if(!CORBA::is_nil(abs_storagetype))
		{
			genKey(key, abs_storagetype, false);
			genKey(key, abs_storagetype, true);
		}
	}
	else
	{
		IR__::StorageTypeDef_var storagetype;
		IR__::StorageHomeDef_var storagehome = IR__::StorageHomeDef::_narrow(inf_def);
		if(!CORBA::is_nil(storagehome))
			storagetype = storagehome->managed_storagetype();
		if(!CORBA::is_nil(storagetype))
		{
			genKey(key, storagetype, false);
			genKey(key, storagetype, true);
		}
	}
}

void 
GeneratorPersistenceH::doException(IR__::ExceptionDef_ptr except)
{
	out << ", " << mapFullName(except);
}

void 
GeneratorPersistenceH::genAbstractStorageTypeBody(IR__::AbstractStorageTypeDef_ptr abs_storagetype, bool isRef)
{
	std::string class_name = string(abs_storagetype->name());

	out << "class " << class_name;
	isRef ? out << "Ref\n" : out << "\n";
	out.indent();
	
	IR__::InterfaceDefSeq_var abs_storagetype_seq = abs_storagetype->base_abstract_storagetypes();
	if(abs_storagetype_seq->length()==0)
	{
		out << ": public virtual CosPersistentState::StorageObject";
		isRef ? out << "Ref\n" : out << "\n";
	}
	else
		for(CORBA::ULong i=0; i<abs_storagetype_seq->length(); i++) 
		{
			i==0 ? out << ": " : out << ", ";
			out << "public virtual " << ((*abs_storagetype_seq)[i])->name();
			isRef ? out << "Ref\n" : out << "\n";
		};

	out.unindent();
	out << "{\n\npublic:\n\n";
	out.indent();
    out << class_name;
	isRef ? out << "Ref();\n" : out << "();\n";
	out << "~" << class_name;
	isRef ? out << "Ref();\n" : out << "();\n";

	m_isAbstract = true;
	handleAttribute(abs_storagetype);
	handleOperation(abs_storagetype);

	out.unindent();
	out << "};\n\n";

	out << "typedef OB::ObjVar< " << class_name;
	if(isRef) out << "Ref";
	out	<< " > " << class_name;
	if(isRef) out << "Ref"; 
	out << "_var;\n";
	out << "typedef OB::ObjVar< " << class_name;
	if(isRef) out << "Ref";
	out << " > " << class_name;
	if(isRef) out << "Ref";
	out << "_out;\n\n\n";
}

void 
GeneratorPersistenceH::doAbstractStorageType(IR__::AbstractStorageTypeDef_ptr abs_storagetype)
{
	// achtung: wenn kein modul, sollte vielleicht PSS_ der prefix für alle pss sein?
	out << "\n\n";
	open_module(out, abs_storagetype, "");
	out << "\n\n";

	// generate normal class
	genAbstractStorageTypeBody(abs_storagetype, false);
	// generate ref class
	genAbstractStorageTypeBody(abs_storagetype, true);

	close_module(out, abs_storagetype);
}

void
GeneratorPersistenceH::genAbstractObjsForConcreteType(IR__::AbstractStorageTypeDef_ptr abs_storagetype)
{
	IR__::InterfaceDefSeq_var abs_storagetype_seq = abs_storagetype->base_abstract_storagetypes();
	for(CORBA::ULong i=0; i<abs_storagetype_seq->length(); i++) 
	{
		m_isAbstract = false;
		handleAttribute((*abs_storagetype_seq)[i]);
		handleOperation((*abs_storagetype_seq)[i]);
	}

	m_isAbstract = false;
	handleAttribute(abs_storagetype);
	handleOperation(abs_storagetype);
}

void 
GeneratorPersistenceH::genStorageTypeBody(IR__::StorageTypeDef_ptr storagetype, bool isRef)
{
	std::string class_name = string(storagetype->name());

	out << "class " << class_name;
	isRef ? out << "Ref\n" : out << "\n";
	out.indent();
	
	IR__::StorageTypeDef_var base_storagetype = storagetype->base_storagetype();
	if(base_storagetype)
	{
		out << ": public virtual " << base_storagetype->name();
		isRef ? out << "Ref\n" : out << "\n";
	}
	else
	{
		out << ": public virtual StorageObject";
		if(isRef) out << "Ref";
		out << "Impl\n";
	}

	IR__::InterfaceDefSeq_var supported_infs = storagetype->supported_interfaces();
	for(CORBA::ULong i=0; i<supported_infs->length(); i++)
	{
		out << ", public virtual " << ((*supported_infs)[i])->name();
		isRef ? out << "Ref\n" : out << "\n";
	};

	out << "// BEGIN USER INSERT SECTION INHERITANCE_" << class_name;
	isRef ? out << "Ref\n" : out << "\n";
	out << "// END USER INSERT SECTION INHERITANCE_" << class_name;
	isRef ? out << "Ref\n" : out << "\n";
	out.unindent();
	out << "{\n\npublic:\n\n";
	out.indent();
    out << class_name;
	isRef ? out << "Ref();\n" : out << "();\n";
	out << "~" << class_name;
	isRef ? out << "Ref();\n" : out << "();\n";

	for(CORBA::ULong i=0; i<supported_infs->length(); i++) 
	{
		IR__::AbstractStorageTypeDef_var abs_storagetype_inh;
		abs_storagetype_inh = IR__::AbstractStorageTypeDef::_narrow((*supported_infs)[i]);
		genAbstractObjsForConcreteType(abs_storagetype_inh);
	};

	m_isAbstract = false;
	handleAttribute(storagetype);
	handleOperation(storagetype);

	out << "\nvoid setValue(map<string, CORBA::Any> valueMap);\n\n\n";
	out.unindent();

	genAttribute(storagetype);
	
	out << "\n// BEGIN USER INSERT SECTION " << class_name;
	isRef ? out << "Ref\n" : out << "\n";
	out << "// END USER INSERT SECTION " << class_name;
	isRef ? out << "Ref\n" : out << "\n\n";
	out << "};\n\n\n";
}

void 
GeneratorPersistenceH::doStorageType(IR__::StorageTypeDef_ptr storagetype)
{
	// achtung: wenn kein modul, sollte vielleicht PSS_ der prefix für alle pss sein?
	out << "\n\n";	
	open_module(out, storagetype, "");
	out << "\n\n";

	// generate normal class
	genStorageTypeBody(storagetype, false);
	// generate ref class
	genStorageTypeBody(storagetype, true);

	close_module(out, storagetype);
}

void 
GeneratorPersistenceH::doAbstractStorageHome(IR__::AbstractStorageHomeDef_ptr abs_storagehome)
{
	IR__::AbstractStorageTypeDef_var abs_storagetype = abs_storagehome->managed_abstract_storagetype();

	// achtung: wenn kein modul, sollte vielleicht PSS_ der prefix für alle pss sein?
	out << "\n\n";
	open_module(out, abs_storagetype, "");
	out << "\n\n";

	std::string class_name = string(abs_storagehome->name());

	out << "class " << class_name << "\n";
	out.indent();
	
	IR__::InterfaceDefSeq_var abs_storagehome_seq = abs_storagehome->base_abstract_storagehomes();
	if(abs_storagehome_seq->length()==0)
		out << ": public virtual CosPersistentState::StorageHomeBase\n";
	else
		for(CORBA::ULong i=0; i<abs_storagehome_seq->length(); i++)
		{
			i==0 ? out << ": " : out << ", ";
			out << "public virtual " << ((*abs_storagehome_seq)[i])->name() << "\n";
		};

	out.unindent();
	out << "{\n\npublic:\n\n";
	out.indent();
    out << class_name << "();\n";
	out << "~" << class_name << "();\n";

	m_isAbstract = true;
	handleAttribute(abs_storagehome);
	handleOperation(abs_storagehome);
	handleFactory(abs_storagehome);
	handleKey(abs_storagehome);

	out.unindent();
	out << "};\n\n";
	out << "typedef OB::ObjVar< " << class_name << " > " << class_name << "_var;\n";
	out << "typedef OB::ObjVar< " << class_name << " > " << class_name << "_out;\n";
	out << "\n\n";

	close_module(out, abs_storagetype);
}

void
GeneratorPersistenceH::genAbstractObjsForConcreteHome(IR__::AbstractStorageHomeDef_ptr abs_storagehome)
{
	IR__::InterfaceDefSeq_var abs_storagehome_seq = abs_storagehome->base_abstract_storagehomes();
	for(CORBA::ULong i=0; i<abs_storagehome_seq->length(); i++) 
	{
		IR__::AbstractStorageHomeDef_var abs_storagehome_inh;
		abs_storagehome_inh = IR__::AbstractStorageHomeDef::_narrow((*abs_storagehome_seq)[i]);
		m_isAbstract = false;
		m_isASHKey = true;
		handleAttribute(abs_storagehome_inh);
		handleOperation(abs_storagehome_inh);
		handleFactory(abs_storagehome_inh);
		handleKey(abs_storagehome_inh);
	}

	m_isAbstract = false;
	m_isASHKey = true;
	handleAttribute(abs_storagehome);
	handleOperation(abs_storagehome);
	handleFactory(abs_storagehome);
	handleKey(abs_storagehome);
}

void
GeneratorPersistenceH::genCreateOperation(IR__::StorageHomeDef_ptr storagehome, bool isRef)
{
	int iLength = 0;
	string strDummy = "";
	char* szDisplay = map_psdl_return_type(storagehome->managed_storagetype(), false);
	isRef ? iLength = strlen(szDisplay) + 11 : iLength = strlen(szDisplay) + 9;
	
	if(isRef)
	{
		char* pdest = strstr( szDisplay, "*" );
		if( pdest != NULL )
		{
			memset(pdest, '\0', 1);
			strcat(szDisplay, "Ref");
		}
	}
	
	out << szDisplay << " _create(";
	out << "Pid* pid,\n";
	strDummy.append(iLength, ' ');
	out << strDummy.c_str();
	out << "ShortPid* shortPid,\n";
		
	IR__::AttributeDefSeq state_members;
	storagehome->managed_storagetype()->get_state_members(state_members, CORBA__::dk_Create);
	CORBA::ULong ulLen = state_members.length();
	for(CORBA::ULong i=0; i<ulLen; i++)
	{
		strDummy = "";
		strDummy.append(iLength, ' ');
		out << strDummy.c_str();

		IR__::AttributeDef_var attribute = IR__::AttributeDef::_narrow(state_members[i]);
		out << map_in_parameter_type(attribute->type_def()) << " " << mapName(attribute);
		if( (i+1)!=ulLen )
			out << ",\n";
	}
	
	if(isRef)
	{
		strDummy = "";
		strDummy.append(iLength, ' ');
		out << ",\n" << strDummy.c_str() << "CosPersistentState::YieldRef yr";
	}

	out << ");\n\n"; 
}

void 
GeneratorPersistenceH::doStorageHome(IR__::StorageHomeDef_ptr storagehome)
{
	IR__::StorageTypeDef_var storagetype = storagehome->managed_storagetype();

	// achtung: wenn kein modul, sollte vielleicht PSS_ der prefix für alle pss sein?
	out << "\n\n";
	open_module(out, storagetype, "");
	out << "\n\n";

	std::string class_name = string(storagehome->name());

	out << "class " << class_name << "\n";
	out.indent();
	
	IR__::StorageHomeDef_var base_storagehome = storagehome->base_storagehome();
	if(base_storagehome)
		out << ": public virtual " << base_storagehome->name() << "\n";
	else
		out << ": public virtual StorageHomeBaseImpl\n";

	IR__::InterfaceDefSeq_var supported_infs = storagehome->supported_interfaces();
	for(CORBA::ULong i=0; i<supported_infs->length(); i++) 
		out << ", public virtual " << ((*supported_infs)[i])->name() << "\n";

	out << "// BEGIN USER INSERT SECTION INHERITANCE_" << class_name << "\n";
	out << "// END USER INSERT SECTION INHERITANCE_" << class_name << "\n";
	out.unindent();
	out << "{\n\npublic:\n\n";
	out.indent();
    out << class_name << "();\n";
	out << "~" << class_name << "();\n\n";

	genCreateOperation(storagehome, false);
	genCreateOperation(storagehome, true);

	for(CORBA::ULong i=0; i<supported_infs->length(); i++) 
	{
		IR__::AbstractStorageHomeDef_var abs_storagehome_inh;
		abs_storagehome_inh = IR__::AbstractStorageHomeDef::_narrow((*supported_infs)[i]);
		genAbstractObjsForConcreteHome(abs_storagehome_inh);
	};

	m_isAbstract = false;
	m_isASHKey = false;
	handleAttribute(storagehome);
	handleOperation(storagehome);
	handleFactory(storagehome);
	handleKey(storagehome);

	out.unindent();
	out << "\n\nprivate:\n\n";
	out.indent();
	out << "string strCreateTable;\n";
	out.unindent();

	out << "\n// BEGIN USER INSERT SECTION " << class_name << "\n";
	out << "// END USER INSERT SECTION " << class_name << "\n\n";
	out << "};\n\n\n";

	close_module(out, storagetype);
}

} // namespace
