/***************************************************************************/
/* Qedo - Quality of Service Enabled Distributed Objects                   */
/*                                                                         */
/* http://qedo.berlios.de/                                                 */
/*                                                                         */
/* Copyright (C) 2002 by the Qedo Team                                     */
/*                                                                         */
/* This library is free software; you can redistribute it and/or           */
/* modify it under the terms of the GNU Lesser General Public              */
/* License as published by the Free Software Foundation; either            */
/* version 2.1 of the License, or (at your option) any later version.      */
/*                                                                         */
/* This library is distributed in the hope that it will be useful,         */
/* but WITHOUT ANY WARRANTY; without even the implied warranty of          */
/* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU        */
/* Lesser General Public License for more details.                         */
/*                                                                         */
/* You should have received a copy of the GNU Lesser General Public        */
/* License along with this library; if not, write to the Free Software     */
/* Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA */
/***************************************************************************/

#ifndef __COMPONENTS_IDL__
#define __COMPONENTS_IDL__

#include "CORBADepends.idl"


#pragma prefix "omg.org"


#ifndef _QEDO_NO_STREAMS

module StreamComponents {
	//
	// Forward declaration
	//
	interface SinkStreamPort;



	exception InvalidBinding {};
	exception NoBinding {};

    local interface StreamingBuffer
    {
            exception OutOfRange {};
            exception IllegalSize {};
            exception OutOfMemory {};

            BufferPtr get_buffer();

            unsigned long get_size();

            void set_used (in unsigned long bytes_used)
                    raises (OutOfRange);

            unsigned long get_used();
    };

};

#endif


module Components {

	typedef string FeatureName;
	typedef sequence<FeatureName> NameList;
	typedef unsigned long FailureReason;


    exception InvalidName { };
	exception InvalidConnection { };
	exception ExceededConnectionLimit { };
	exception AlreadyConnected { };
	exception NoConnection { };
	exception CookieRequired { };
	exception DuplicateKeyValue { };
	exception NoKeyAvailable { };
	exception InvalidKey { };
	exception UnknownKeyValue { };
	exception BadEventType {
		CORBA::RepositoryId expected_event_type;
	};
	exception HomeNotFound { };
	exception WrongComponentType { };
	exception InvalidConfiguration { };
	exception CreateFailure
	{
		FailureReason reason;
	};
	exception FinderFailure
	{
		FailureReason reason;
	};
	exception RemoveFailure
	{
		FailureReason reason;
	};


	abstract valuetype EventBase {};

	abstract valuetype PrimaryKeyBase { };

	interface EventConsumerBase /*: CosNotifyComm::StructuredPushConsumer*/ {
		void push_event (in EventBase evt) raises (BadEventType);
	};

	valuetype Cookie {
		private CORBA::OctetSeq cookieValue;
	};

	valuetype PortDescription {
		public FeatureName name;
		public CORBA::RepositoryId type_id;
	};

	valuetype FacetDescription : PortDescription {
		public Object facet_ref;
	};

	typedef sequence < FacetDescription > FacetDescriptions;

    valuetype ConnectionDescription {
		public Cookie ck;
		public Object objref;
	};

	typedef sequence < ConnectionDescription > ConnectedDescriptions;

	valuetype ReceptacleDescription : PortDescription {
		public boolean is_multiplex;
		public ConnectedDescriptions connections;
	};

	typedef sequence < ReceptacleDescription > ReceptacleDescriptions;

	valuetype ConsumerDescription : PortDescription {
		public EventConsumerBase consumer;
	};

	typedef sequence < ConsumerDescription > ConsumerDescriptions;

	valuetype EmitterDescription : PortDescription {
		public EventConsumerBase consumer;
	};

	typedef sequence < EmitterDescription > EmitterDescriptions;

	valuetype SubscriberDescription : PortDescription {
		public Cookie ck;
		public EventConsumerBase consumer;
	};

	typedef sequence < SubscriberDescription > SubscriberDescriptions;
	
	valuetype ComponentPortDescription {
		public FacetDescriptions facets;
		public ReceptacleDescriptions receptacles;
		public ConsumerDescriptions consumers;
		public EmitterDescriptions emitters;
		public SubscriberDescriptions publishers;
	};

	valuetype ConfigValue {
		public FeatureName name;
		public any value;
	};

#ifdef TAO_CIDL_GEN
	typedef sequence<octet> ConfigValues;
#else

	typedef sequence<ConfigValue> ConfigValues;
#endif

	interface Navigation {
		Object provide_facet (in FeatureName name)
			raises (InvalidName);
		FacetDescriptions get_all_facets();
		FacetDescriptions get_named_facets ( in NameList names )
			raises ( InvalidName );
		boolean same_component (in Object object_ref);
	};
	
	interface Receptacles {
		Cookie connect (
			in FeatureName name,
			in Object connection )
			raises (
				InvalidName,
				InvalidConnection,
				AlreadyConnected,
				ExceededConnectionLimit);
		void disconnect (
			in FeatureName name,
			in Cookie ck)
			raises (
				InvalidName,
				InvalidConnection,
				CookieRequired,
				NoConnection);
		ConnectedDescriptions get_connections (in FeatureName name)
			raises (InvalidName);
		ReceptacleDescriptions get_all_receptacles();
		ReceptacleDescriptions get_named_receptacles ( in NameList names )
			raises ( InvalidName );
	};

	interface Events {
		EventConsumerBase get_consumer (in FeatureName sink_name)
			raises (InvalidName);
		Cookie subscribe (in FeatureName publisher_name,
			in EventConsumerBase subscriber)
			raises (InvalidName);
		void unsubscribe (in FeatureName publisher_name,
			in Cookie ck)
			raises (InvalidName, InvalidConnection);
		void connect_consumer (in FeatureName emitter_name,
			in EventConsumerBase consumer)
			raises (InvalidName, AlreadyConnected);
		EventConsumerBase disconnect_consumer (
			in FeatureName source_name)
			raises (InvalidName, NoConnection);
		ConsumerDescriptions get_all_consumers();
		ConsumerDescriptions get_named_consumers ( in NameList names )
			raises ( InvalidName );
		EmitterDescriptions get_all_emitters();
		EmitterDescriptions get_named_emitters ( in NameList names )
			raises ( InvalidName );
		SubscriberDescriptions get_all_publishers();
		SubscriberDescriptions get_named_publishers ( in NameList names )
			raises ( InvalidName );
	};

	interface CCMObject;

	typedef sequence<CCMObject> CCMObjects; // extension !!!

	interface CCMHome {
		CORBA::IRObject get_component_def ();
		CORBA::IRObject get_home_def ();
		void remove_component ( in CCMObject comp)
			raises ( RemoveFailure );
		CCMObjects get_instances (); // extension !!!
		string get_home_rep_id(); // extension !!!
		string get_component_rep_id(); // extension !!!
	};

	interface KeylessCCMHome {
		CCMObject create_component()
			raises (CreateFailure);
		CCMObject create_component_with_config(in ConfigValues config) // extension !!!
			raises (CreateFailure);
	};

	interface HomeFinder {
		CCMHome find_home_by_component_type (
			in CORBA::RepositoryId comp_repid)
			raises (HomeNotFound);
		CCMHome find_home_by_home_type (
			in CORBA::RepositoryId home_repid)
			raises (HomeNotFound);
		CCMHome find_home_by_name (
			in string home_name)
			raises (HomeNotFound);
	};

	interface Configurator {
		void configure (in CCMObject comp)
			raises (WrongComponentType);
	};

	interface StandardConfigurator : Configurator {
		void set_configuration (in ConfigValues descr);
	};

	interface HomeConfiguration : CCMHome {
		void set_configurator (in Configurator cfg);
		void set_configuration_values (
			in ConfigValues config);
		void complete_component_configuration (in boolean b);
		void disable_home_configuration();
	};

	interface CCMObject : Navigation, Receptacles, Events {
		CORBA::IRObject get_component_def ( );
		CCMHome get_ccm_home( );
		PrimaryKeyBase get_primary_key( )
			raises (NoKeyAvailable);
		void configuration_complete( )
			raises (InvalidConfiguration);
		void remove();
		ComponentPortDescription get_all_ports();
	};

	interface Enumeration {
		boolean has_more_elements();
		CCMObject next_element();
	};

	module Transaction {

                typedef sequence<octet> TranToken;

                exception NoTransaction { };
                exception NotSupported { };
                exception SystemError { };
                exception Rollback { };
                exception HeuristicMixed { };
                exception HeuristicRollback { };
                exception Security { };
                exception InvalidToken { };

                enum Status {
                          ACTIVE,
                          MARKED_ROLLBACK,
                          PREPARED,
                          COMMITTED,
                          ROLLED_BACK,
                          NO_TRANSACTION,
                          PREPARING,
                          COMMITTING,
                          ROLLING_BACK
                };

		local interface UserTransaction {
                          void begin ()
                                  raises (NotSupported, SystemError);
                          void commit ()
                                  raises (Transaction::Rollback, NoTransaction,
                                  HeuristicMixed, HeuristicRollback,
                                  Security, SystemError);
                          void rollback ()
                                  raises (NoTransaction,
                                  Security, SystemError);
                          void set_rollback_only ()
                                  raises (NoTransaction, SystemError);
                          Status get_status()
                                  raises (SystemError);
                          void set_timeout (in long to)
                                  raises (SystemError);
                          TranToken suspend ()
                                  raises (NoTransaction, SystemError);
                          void resume (in TranToken txtoken)
                                  raises (InvalidToken, SystemError);
                };
        };
	
	typedef long/*SecurityLevel2::Credentials*/ Principal;
	enum CCMExceptionReason {
		SYSTEM_ERROR,
		CREATE_ERROR,
		REMOVE_ERROR,
		DUPLICATE_KEY,
		FIND_ERROR,
		OBJECT_NOT_FOUND,
		NO_SUCH_ENTITY};

	exception CCMException { CCMExceptionReason reason; };
	exception IllegalState { };

		/** extension */
	native Function;
	native FunctionData;
	
	local interface Thread {
		void stop();
		void join();
	};

	local interface Mutex {
		void lock();
		void unlock();
		void destroy();
	};

	local interface Cond {
		void wait(in Mutex m);
		boolean wait_timed(in Mutex m, in unsigned long wait);
		void signal();
		void destroy();
	};
		/** end extension */

	local interface CCMContext {
		Principal get_caller_principal();
		CCMHome get_CCM_home();
		boolean get_rollback_only()
			raises (IllegalState);
		Transaction::UserTransaction get_user_transaction()
			raises (IllegalState);
		boolean is_caller_in_role (in string role);
		void set_rollback_only()
			raises (IllegalState);
		/** extension */
		Object resolve_service_reference(in string service_id)
			raises(CCMException);
		Thread start_thread(in Function func,in FunctionData data)
			raises(CCMException);
		Mutex create_mutex()
			raises(CCMException);
#ifndef _QEDO_NO_STREAMS
                StreamComponents::StreamingBuffer get_streaming_buffer (in unsigned long min_size)
                        raises (StreamComponents::StreamingBuffer::IllegalSize,
                        StreamComponents::StreamingBuffer::OutOfMemory);
#endif
		Cond create_cond()
			raises(CCMException);
	};

	local interface EnterpriseComponent {
	};

	local interface SessionContext : CCMContext {
		Object get_CCM_object()
			raises (IllegalState);
	};


	local interface SessionComponent : EnterpriseComponent {
		void set_session_context ( in SessionContext ctx)
			raises (CCMException);
		void ccm_activate()
			raises (CCMException);
		void ccm_passivate()
			raises (CCMException);
		void ccm_remove ()
			raises (CCMException);
	};

	local interface SessionSynchronization {
		void after_begin ()
			raises (CCMException);
		void before_completion ()
			raises (CCMException);
		void after_completion (
			in boolean committed)
			raises (CCMException);
	};

	local interface EntityContext : CCMContext {
		Object get_CCM_object ()
			raises (IllegalState);
		PrimaryKeyBase get_primary_key ()
			raises (IllegalState);
	};

	local interface EntityComponent : EnterpriseComponent {
		void set_entity_context (in EntityContext ctx)
			raises (CCMException);
		void unset_entity_context ()
			raises (CCMException);
		void ccm_activate ()
			raises (CCMException);
		void ccm_load ()
			raises (CCMException);
		void ccm_store ()
			raises (CCMException);
		void ccm_passivate ()
			raises (CCMException);
		void ccm_remove ()
			raises (CCMException);
	};

#ifndef _QEDO_NO_QOS
	module Extension {
		local interface ContainerServerRequestInfo {
			readonly attribute string component_uuid;
			readonly attribute string component_id;
			readonly attribute string port_id;
			PortableInterceptor::ServerRequestInfo request_info();
		};

		local interface ContainerClientRequestInfo {
			readonly attribute string component_uuid;
			readonly attribute string component_id;
			readonly attribute string port_id;
			PortableInterceptor::ClientRequestInfo request_info();
		};

		local interface ContainerInterceptor {
			void set_slot_id(in PortableInterceptor::SlotId slot_id);
		};

		local interface ServerContainerInterceptor : ContainerInterceptor
		{
			void receive_request ( in Extension::ContainerServerRequestInfo info );
			void send_reply ( in Extension::ContainerServerRequestInfo info );
			void send_system_exception ( in Extension::ContainerServerRequestInfo info );
			void send_user_exception ( in Extension::ContainerServerRequestInfo info );

			void rec_request_from_servant_locator(in string operation);

			Cookie connect (in string comp_id, in FeatureName name,	in Object connection, out boolean con )
				raises (InvalidName, InvalidConnection, AlreadyConnected, ExceededConnectionLimit);

			Object provide_facet (in string comp_id, in FeatureName name, out boolean con)
				raises (InvalidName);
#ifndef _QEDO_NO_STREAMS

			Components::Cookie bind(in string comp_id, inout Components::FeatureName name, inout StreamComponents::SinkStreamPort the_sink, inout string transport_profile, out boolean con);

			StreamComponents::SinkStreamPort unbind (in string comp_id, inout Components::FeatureName name, inout Components::Cookie ck, out boolean con)
				raises (Components::CookieRequired, StreamComponents::InvalidBinding, StreamComponents::NoBinding);

			Object provide_sink_stream_port (in string comp_id, inout Components::FeatureName name, out boolean con)
				raises (Components::InvalidName);
#endif
		};

		local interface ClientContainerInterceptor : ContainerInterceptor
		{
			void send_request ( in Extension::ContainerClientRequestInfo info );
			void receive_reply ( in Extension::ContainerClientRequestInfo info );
			void receive_system_exception ( in Extension::ContainerClientRequestInfo info );
			void receive_user_exception ( in Extension::ContainerClientRequestInfo info );
		};
		local interface ServerInterceptorRegistration : PortableInterceptor::ServerRequestInterceptor
		{
			void register_interceptor_for_all (in ServerContainerInterceptor server_interceptor);
			void register_interceptor_for_component (in ServerContainerInterceptor server_interceptor, in string id);
			void unregister_interceptor_for_all ( in ServerContainerInterceptor server_interceptor);
			void unregister_interceptor_for_component ( in ServerContainerInterceptor server_interceptor, in string id);
			
		};

		local interface ClientInterceptorRegistration : PortableInterceptor::ClientRequestInterceptor
		{
			void register_interceptor_for_all ( in ClientContainerInterceptor client_interceptor);
		};

		local interface ServantInterceptorRegistration
		{
			void register_interceptor_for_all ( in ServerContainerInterceptor server_interceptor);
			boolean call(in string oper);
			// CCMObject
			Cookie connect (in string comp_id, in FeatureName name,	in Object connection, out boolean con )
				raises (InvalidName, InvalidConnection, AlreadyConnected, ExceededConnectionLimit);

			Object provide_facet (in string comp_id, in FeatureName name, out boolean con)
				raises (InvalidName);
			
#ifndef _QEDO_NO_STREAMS

			// StreamCCMObject
			Components::Cookie bind(in string comp_id, inout Components::FeatureName name, inout StreamComponents::SinkStreamPort the_sink, inout string transport_profile, out boolean con);

			StreamComponents::SinkStreamPort unbind (in string comp_id, inout Components::FeatureName name, inout Components::Cookie ck, out boolean con)
				raises (Components::CookieRequired, StreamComponents::InvalidBinding, StreamComponents::NoBinding);

			Object provide_sink_stream_port (in string comp_id, inout Components::FeatureName name, out boolean con)
				raises (Components::InvalidName);
#endif
		};

	}; // Extension

	local interface ExtensionContext : CCMContext
	{
		void set_server_interceptor_dispatcher_registration (
			in Components::Extension::ServerInterceptorRegistration registration);

		void set_client_interceptor_dispatcher_registration (
			in Components::Extension::ClientInterceptorRegistration registration );

		void set_servant_interceptor_dispatcher_registration (
			in Components::Extension::ServantInterceptorRegistration registration );

		Components::Extension::ServerInterceptorRegistration
			get_server_interceptor_dispatcher_registration ();

		Components::Extension::ClientInterceptorRegistration
			get_client_interceptor_dispatcher_registration ();

		Components::Extension::ServantInterceptorRegistration
			get_servant_interceptor_dispatcher_registration();

		void register_servant_locator_for_all (in Components::Extension::ServerContainerInterceptor server_interceptor);

		Components::ConfigValues
		get_contract_data ();

		void
		set_contract_data (in Components::ConfigValues contracts);

		void 
		install_service_reference(in string id, in Object objref) raises (CCMException);

		Object get_CCM_object();

	};

	local interface ExtensionComponent : EnterpriseComponent
	{
		void set_extension_context (in ExtensionContext ctx)
			raises (CCMException);
		void ccm_activate ()
			raises (CCMException);
		void ccm_passivate ()
			raises (CCMException);
		void ccm_remove ()
			raises (CCMException);
	};


#endif

	enum BadComponentReferenceReason {
		NON_LOCAL_REFERENCE,
		NON_COMPONENT_REFERENCE,
		WRONG_CONTAINER
	};

#ifndef _QEDO_NO_DB
	typedef CosPersistentState::CatalogBase CatalogBase;
	typedef CosPersistentState::PTypeId PTypeId;
	typedef CosPersistentState::Pid PersistentId;
#endif

	typedef short SegmentId;
	const SegmentId COMPONENT_SEGMENT = 0;
	typedef short FacetId;
	const FacetId COMPONENT_FACET = 0;
	typedef sequence<octet> IdData;
	typedef short StateIdType;
	const StateIdType PERSISTENT_ID = 0;

	exception BadComponentReference {
		BadComponentReferenceReason reason;
	};
	exception PolicyMismatch { };
	exception PersistenceNotAvailable { };
	exception UnknownActualHome { };
	exception ProxyHomeNotSupported { };
	exception InvalidStateIdData {};

	local interface HomeRegistration;

	local interface CCM2Context : CCMContext {
		HomeRegistration get_home_registration ();
		void req_passivate ()
			raises (PolicyMismatch);
#ifndef _QEDO_NO_DB
		CatalogBase get_persistence (
			in PTypeId catalog_type_id)
			raises (PersistenceNotAvailable);
#else
		void get_persistence();
#endif
	};

	local interface HomeRegistration {
		void register_home (
			in CCMHome ahome,
			in string home_name);
		void unregister_home (in CCMHome ahome);
	};

	local interface ProxyHomeRegistration : HomeRegistration {
		void register_proxy_home (
			in CCMHome rhome,
			in CCMHome ahome)
			raises (UnknownActualHome, ProxyHomeNotSupported);
	};

	local interface Session2Context : SessionContext, CCM2Context {
		Object create_ref (
			in CORBA::RepositoryId repid);
		Object create_ref_from_oid (
			in PortableServer::ObjectId oid,
			in CORBA::RepositoryId repid);
		PortableServer::ObjectId get_oid_from_ref (
			in Object objref)
			raises (IllegalState, BadComponentReference);
	};

	abstract valuetype StateIdValue {
		StateIdType get_sid_type();
		IdData get_sid_data();
	};

	local interface StateIdFactory {
		StateIdValue create (in IdData data)
			raises (InvalidStateIdData);
	};

#ifndef _QEDO_NO_DB
	valuetype PersistentIdValue : StateIdValue {
		private PersistentId pid;
		PersistentId get_pid();
#ifdef TAO_IDL
		PersistentIdValue init(in PersistentId pid);
#else
		factory init(in PersistentId pid);
#endif
	};
#endif
	valuetype SegmentDescr {
		private StateIdValue sid;
		private SegmentId seg;
		StateIdValue get_sid();
		SegmentId get_seg_id();
#ifdef TAO_IDL
		SegmentDescr init(in StateIdValue sid, in SegmentId seg);
#else
		factory init(in StateIdValue sid, in SegmentId seg);
#endif
	};

#ifdef TAO_CIDL_GEN
	typedef sequence<octet> SegmentDescrSeq;
#else

	typedef sequence<SegmentDescr> SegmentDescrSeq;
#endif


	local interface ComponentId {
		FacetId get_target_facet();
		SegmentId get_target_segment();
		StateIdValue get_target_state_id (
			in StateIdFactory sid_factory)
			raises (InvalidStateIdData);
		StateIdValue get_segment_state_id (
			in SegmentId seg,
			in StateIdFactory sid_factory)
			raises (InvalidStateIdData);
		ComponentId create_with_new_target (
			in FacetId new_target_facet,
			in SegmentId new_target_segment);
		SegmentDescrSeq get_segment_descrs (
			in StateIdFactory sid_factory)
			raises (InvalidStateIdData);
	};

	local interface Entity2Context : EntityContext, CCM2Context {
		ComponentId get_component_id ()
			raises (IllegalState);
		ComponentId create_component_id (
			in FacetId target_facet,
			in SegmentId target_segment,
			in SegmentDescrSeq seq_descrs);
		ComponentId create_monolithic_component_id (
			in FacetId target_facet,
			in StateIdValue sid);
		Object create_ref_from_cid (
			in CORBA::RepositoryId repid,
			in ComponentId cid);
		ComponentId get_cid_from_ref (
			in Object objref)
			raises (BadComponentReference);
	};

	typedef sequence<CCMHome> CCMHomes;


	//
	// module deployment
	//
	module Deployment
	{

		//
		// typedefs
		//
		typedef FailureReason InvalidConfigurationReason;
		const InvalidConfigurationReason UnknownConfigValueName = 0;
		const InvalidConfigurationReason InvalidConfigValueType = 1;
		const InvalidConfigurationReason ConfigValueRequired = 2;
		const InvalidConfigurationReason ConfigValueNotExpected = 3;

		typedef string UUID;
		typedef string Location;

		enum AssemblyState { INACTIVE,  INSERVICE };


		//
		// exceptions
		//
		exception InvalidConfiguration
		{
			InvalidConfigurationReason reason;
			FeatureName name;
		};
		exception UnknownImplId { };
		exception InvalidLocation { };
		exception InstallationFailure
		{
			FailureReason reason;
		};
		exception InvalidAssembly { };
		exception ImplEntryPointNotFound { };


		//
		// interfaces
		//
		interface ComponentInstallation
		{
			void install(in UUID implUUID,
						 in Location component_loc)
					raises (InvalidLocation, InstallationFailure);

			void replace(in UUID implUUID,
					     in Location component_loc)
					raises (InvalidLocation, InstallationFailure);

			void remove(in UUID implUUID)
					raises (UnknownImplId, RemoveFailure);

			Location get_implementation(in UUID implUUID)
					raises(UnknownImplId, InstallationFailure);
		};


		interface Assembly
		{
			void build() raises (CreateFailure);

			void tear_down() raises (RemoveFailure);

			AssemblyState get_state();
		};


		interface AssemblyFactory
		{
			Cookie create_assembly(in Location assembly_loc)
				raises (InvalidLocation, CreateFailure);

			Assembly lookup(in Cookie c)
				raises (InvalidAssembly);

			void destroy(in Cookie c)
				raises (InvalidAssembly, RemoveFailure);
		};


		interface ComponentServer;
		typedef sequence<ComponentServer> ComponentServers;


		interface ServerActivator
		{
			ComponentServer create_component_server(
								in ConfigValues config)
								raises(CreateFailure, InvalidConfiguration);

			void remove_component_server(in ComponentServer server)
								raises(RemoveFailure);

			ComponentServers get_component_servers();
		};


		interface Container;
		typedef sequence<Container> Containers;


		interface ComponentServer
		{
			readonly attribute ConfigValues configuration;

			ServerActivator get_server_activator();

			Container create_container(in ConfigValues config)
						raises (CreateFailure, InvalidConfiguration);

			void remove_container(in Container cref) raises (RemoveFailure);

			Containers get_containers();

	 		void remove() raises (RemoveFailure);
		};


		interface Container
		{
			readonly attribute ConfigValues configuration;

			ComponentServer get_component_server();

			CCMHome install_home(in UUID id,
							     in string entrypt,
								 in ConfigValues config)
						raises (UnknownImplId,
						        ImplEntryPointNotFound,
						        InstallationFailure,
						        InvalidConfiguration);

			void remove_home(in CCMHome href) raises (RemoveFailure);

			CCMHomes get_homes();

			void remove() raises (RemoveFailure);

			/** extension */
			void install_service_reference(in string id, in Object objref) raises (CCMException);
		};


		/**
		 * extension for having an upload functionality
		 */
		interface ExtComponentInstallation : ComponentInstallation
		{
			string upload(in UUID implUUID, in CORBA::OctetSeq package)
				raises(InstallationFailure);
		};

	}; // end of module deployment

        // @@@ This is a Qedo extension
        local interface HomeContext
        {
                CCMHome get_CCM_home();
        };

	local interface HomeExecutorBase
	{
		void set_context (in HomeContext ctx)
			raises (CCMException);
	};

	local interface ExecutorLocator : EnterpriseComponent
	{
		Object obtain_executor (in string name);
		void release_executor (in Object exc);
		void configuration_complete()
			raises (InvalidConfiguration);
	};


	// These interfaces are not standard, but every container implementation needs to define
	// something like this to implement session or entity components
	local interface SessionExecutorLocator : ExecutorLocator, SessionComponent
	{
	};

	//
	// extension for service integration
	//
	local interface CCMService : ExecutorLocator, SessionComponent
	{
		void preinvoke(in string comp_id, in string operation);
		void postinvoke(in string comp_id, in string operation);
	};

	local interface EntityExecutorLocator : ExecutorLocator, EntityComponent
	{
	};

#ifndef _QEDO_NO_QOS
	local interface ExtensionExecutorLocator : ExecutorLocator, ExtensionComponent
	{
	};

#endif
};

#ifndef _QEDO_NO_STREAMS

module StreamComponents {

//
// Forward declaration
//
interface SinkStreamPort;

//
// Exceptions
//
exception UnsupportedStreamtype {
	CORBA::RepositoryIdSeq unsupported_streamtypes;
};

exception NoStream {};					// Raised when end_stream is called without a previous begin_stream
exception DuplicateStream {};			// Raised when begin_stream is called twice without first calling end_stream
exception TransportFailure {};
exception ExceededBindingLimit {};
exception AlreadyBound {};
exception IllegalStream {};				// Raised when the wrong send_stream_data_* operation is used with respect to the
										// repository identifier supplied in the preceeding begin_stream operation

//
// Structures
//
struct TransportSpec {
	string transport_profile;
	Components::ConfigValues transport_parameters;
};


// TCP Profile Header
// A stream ends when the stream_number increases by one
// Since TCP delivers reliable and in correct order, we can omit a sequence number
struct TCPProfileHeader {
	unsigned short stream_number;
	unsigned long seq_length;
};

// UDP Profile Header
struct UDPProfileHeader {
	unsigned short stream_number;
	unsigned long seq_length;
	unsigned short fragment_number;
	unsigned short last_fragment_number;
};

//
// Valuetypes
//
valuetype BindingDescription {
	public Components::Cookie ck;
	public SinkStreamPort the_sink;
};
typedef sequence <BindingDescription> BindingDescriptions;

valuetype SourceDescription : Components::PortDescription {
	public boolean is_multiplex;
	public CORBA::RepositoryIdSeq stream_types;
	public BindingDescriptions bindings;
};
typedef sequence <SourceDescription> SourceDescriptions;

valuetype SinkDescription : Components::PortDescription {
	public CORBA::RepositoryIdSeq stream_types;
	public SinkStreamPort the_sink;
};
typedef sequence <SinkDescription> SinkDescriptions;

//
// Interfaces
//

//
// For each sink stream port there will be exactly one object implementing the SinkStreamPort interface
// There is no need for typed-specific SinkStreamPort interfaces, since the source component cannot know
// the name of the sink (in the scope of the sink component) to which it transfers data
// Consequently operations like begin_stream_<my_sink>() make no sense
//
interface SinkStreamPort {
	void begin_stream (in CORBA::RepositoryId repository_id,
					   in Components::ConfigValues stream_meta_data)
		raises (UnsupportedStreamtype, DuplicateStream);

	void end_stream()
		raises (NoStream);

	void check_streamtype (in CORBA::RepositoryIdSeq the_streamtypes)
		raises (UnsupportedStreamtype);

	void consider_transport (inout TransportSpec the_transport)
		raises (AlreadyBound, TransportFailure);

	void release_transport();
};


//
// The Streams interface with general stream management operations
//
interface Streams {
	SinkStreamPort provide_sink_stream_port (in Components::FeatureName name)
		raises (Components::InvalidName);

	Components::Cookie bind (in Components::FeatureName name, in SinkStreamPort the_sink, in string transport_profile)
		raises (Components::InvalidName, AlreadyBound, InvalidBinding, ExceededBindingLimit);

	SinkStreamPort unbind (in Components::FeatureName name, in Components::Cookie ck)
		raises (Components::CookieRequired, InvalidBinding, NoBinding);

	BindingDescriptions get_bindings (in Components::FeatureName name)
		raises (Components::InvalidName);

	SinkDescriptions get_named_sinks (in Components::NameList names)
		raises(Components::InvalidName);

	SinkDescriptions get_all_sinks();

	SourceDescriptions get_named_sources (in Components::NameList names)
		raises (Components::InvalidName);

	SourceDescriptions get_all_sources();
};


//
// This is the CORBA interface a component with stream ports must implement
//
interface StreamCCMObject : Streams, Components::CCMObject 
{
};


};
#endif
#pragma prefix ""


//
// module ConfigurationService
//
module ConfigurationService
{

	//
	// exceptions
	//
	exception UnknownConfiguration {};

	//
	// InternalConfiguration
	//
	local interface InternalConfiguration
	{
		string get_value(in string name)
			raises(UnknownConfiguration);
	};
};

#endif
