//
// generated by Qedo
//

#include "openpmf_ccm_PEP_ManagerImpl.h"


// BEGIN USER INSERT SECTION file
#include "ServerPEPInterceptor.h"
#include <SL3_Transformer.h>
#include <CCM_Transformer.h>
#include <cpm_admin.h>
#include <pep_ccm_impl.h>

#ifndef _WIN32
extern PortableInterceptor::SlotId global_pmf_slot_id;
#else // _WIN32
extern PortableInterceptor::SlotId
get_global_pmf_slot_id();
#endif // _WIN32


using namespace PMFCCM;
using namespace OpenPMF;
using namespace PortableServer;
using namespace CORBA;

// END USER INSERT SECTION file


namespace openpmf_ccm {


// BEGIN USER INSERT SECTION PEP_ManagerExec
// END USER INSERT SECTION PEP_ManagerExec


PEP_ManagerExec::PEP_ManagerExec()
{
// BEGIN USER INSERT SECTION PEP_ManagerExec::PEP_ManagerExec
  std::cout << "PEP_ManagerExec::PEP_ManagerExec()\n";
// END USER INSERT SECTION PEP_ManagerExec::PEP_ManagerExec
}


PEP_ManagerExec::~PEP_ManagerExec()
{
// BEGIN USER INSERT SECTION PEP_ManagerExec::~PEP_ManagerExec
    Components::ContainerPortableInterceptor::ServerContainerInterceptorRegistration_ptr server_reg =
        context_->get_server_interceptor_dispatcher_registration();
    server_reg->unregister_server_interceptor(server_cookie_);
// END USER INSERT SECTION PEP_ManagerExec::~PEP_ManagerExec

}


void
PEP_ManagerExec::set_context(::openpmf_ccm::CCM_pep_manager_ContextImpl_ptr context)
    throw (CORBA::SystemException, Components::CCMException)
{
    context_ = ::openpmf_ccm::CCM_pep_manager_ContextImpl::_duplicate(context);
}


void
PEP_ManagerExec::configuration_complete()
    throw (CORBA::SystemException, Components::InvalidConfiguration)
{
// BEGIN USER INSERT SECTION PEP_ManagerExec::configuration_complete
  std::cout << "PEP_ManagerExec::configuration_complete " 
	    << policy_name_ 
	    << std::endl;

  PMFCORBA::PlatformRef pf = new PMFCORBA::Platform;

  pf->add_transformer("client.name", new PMFCORBA_SL3::TLSIdentityTransformer
                             (NULL, new PMFCORBA_SL3::ClientTransformer));
  pf->add_transformer("initiator.name", new PMFCORBA_SL3::InitiatorTransformer);
  pf->add_transformer("target.name", new OpenPMF::CCM::TargetTransformer(NULL, NULL));
  pf->add_transformer("operation.name", new OpenPMF::CCM::OperationTransformer(NULL, NULL));
  pf->add_transformer("target.type", new OpenPMF::CCM::TypeTransformer(NULL, NULL));

  std::cout << "Transformer OK"
    	    << policy_name_ 
	    << std::endl;
  
  ORB_var orb = ORB_instance("mico-local-orb", FALSE);
  Bootstrap_var boot = Bootstrap::_nil();
  CORBA::Object_var obj = CORBA::Object::_nil();
  try {
      obj = orb->resolve_initial_references
          ("PolicyManagementFramework");
      boot = Bootstrap::_narrow(obj);
      assert(!is_nil(boot));
  }
  catch (const ORB::InvalidName& ex) {
  }
  PolicyEnforcementPoint_impl* pep_impl = new PolicyEnforcementPoint_impl
      (orb, pf, "<unspecified>", "CCM",
       "<unspecified>", this->policy_name_);
  pep_impl->reload_policy();
  if (!is_nil(boot)) {
      obj = orb->resolve_initial_references("RootPOA");
      POA_var poa = POA::_narrow(obj);
      assert(!is_nil(poa));
      CORBA::PolicyList pl(0);
      POA_var pep_poa = POA::_nil();
      try {
          pep_poa = poa->create_POA("OpenPMF/PEP_POA", POAManager::_nil(), pl);
      }
      catch (const POA::AdapterAlreadyExists& ex) {
          pep_poa = poa->find_POA("OpenPMF/PEP_POA", FALSE);
      }
      assert(!is_nil(pep_poa));
      POAManager_var mgr = pep_poa->the_POAManager();
      mgr->activate();
      PolicyManagement_var pm = boot->policy_management();
      PEPRegistry_var pep_regs = pm->pep_registry();
      ObjectId_var oid = pep_poa->activate_object(pep_impl);
      obj = pep_poa->id_to_reference(oid);
      PolicyEnforcementPoint_var pep = PolicyEnforcementPoint::_narrow(obj);
      pep_regs->register_PEP(pep);
  }

  //  server_interceptor_ = new Qedo::ServerPEPInterceptor(pf_, rt_policy_);

  //  server_reg->register_interceptor_for_all(server_interceptor_);
  std::cout << "PEP_ManagerExec::configuration_complete COPI init OK\n";



  Components::ContainerPortableInterceptor::ServerContainerInterceptorRegistration_ptr server_reg =
    context_->get_server_interceptor_dispatcher_registration();
  server_pep_interceptor_ = new Qedo::ServerPEPInterceptor(context_,this, pep_impl);
#ifndef _WIN32
  server_pep_interceptor_->set_pmf_slot_id(global_pmf_slot_id);
#else // _WIN32
  server_pep_interceptor_->set_pmf_slot_id(get_global_pmf_slot_id());
#endif // _WIN32
  server_cookie_ = server_reg->register_server_interceptor(server_pep_interceptor_);
  




// END USER INSERT SECTION PEP_ManagerExec::configuration_complete
}


void
PEP_ManagerExec::remove()
    throw (CORBA::SystemException)
{
// BEGIN USER INSERT SECTION PEP_ManagerExec::remove
// END USER INSERT SECTION PEP_ManagerExec::remove
}


void
PEP_ManagerExec::policy_name(const char* param)
	throw(CORBA::SystemException)
{
// BEGIN USER INSERT SECTION PEP_ManagerExec::_policy_name
  std::cout << "PEP_ManagerExec::policy_name= " << param << std::endl;
  policy_name_ = param;
// END USER INSERT SECTION PEP_ManagerExec::_policy_name
}


char*
PEP_ManagerExec::policy_name()
	throw(CORBA::SystemException)
{
// BEGIN USER INSERT SECTION PEP_ManagerExec::policy_name
    return CORBA::string_dup(this->policy_name_.c_str());
// END USER INSERT SECTION PEP_ManagerExec::policy_name
}


// BEGIN USER INSERT SECTION PEP_ManagerImpl
// END USER INSERT SECTION PEP_ManagerImpl


PEP_ManagerImpl::PEP_ManagerImpl()
:component_(new PEP_ManagerExec())
{
// BEGIN USER INSERT SECTION PEP_ManagerImpl::PEP_ManagerImpl
  std::cout << "PEP_ManagerImpl::PEP_ManagerImpl\n";

// END USER INSERT SECTION PEP_ManagerImpl::PEP_ManagerImpl
}


PEP_ManagerImpl::~PEP_ManagerImpl()
{
// BEGIN USER INSERT SECTION PEP_ManagerImpl::~PEP_ManagerImpl
// END USER INSERT SECTION PEP_ManagerImpl::~PEP_ManagerImpl

    component_->_remove_ref();
}


::CORBA::Object*
PEP_ManagerImpl::obtain_executor(const char* name)
    throw (CORBA::SystemException)
{
    if (! strcmp ( name, "component" ) ) {
        return Components::EnterpriseComponent::_duplicate (component_);
    }
    
    return Components::EnterpriseComponent::_nil();
}


void
PEP_ManagerImpl::release_executor(::CORBA::Object_ptr executor)
    throw (CORBA::SystemException)
{
    CORBA::release (executor);
}


void
PEP_ManagerImpl::configuration_complete()
    throw (CORBA::SystemException, Components::InvalidConfiguration)
{
    component_->configuration_complete();

// BEGIN USER INSERT SECTION PEP_ManagerImpl::configuration_complete
    std::cout << "PEP_ManagerImpl::configuration_complete "
      //	      << policy_name 
	      << std::cout;
// END USER INSERT SECTION PEP_ManagerImpl::configuration_complete
}


void
PEP_ManagerImpl::set_extension_context(::Components::ExtensionContext_ptr context)
    throw (CORBA::SystemException, Components::CCMException)
{
    #ifdef TAO_ORB
    ::openpmf_ccm::CCM_pep_manager_Context_ptr tmp_context;
    
    tmp_context = dynamic_cast<::openpmf_ccm::CCM_pep_manager_ContextImpl*>(context);
    
    if (tmp_context)
        context_ = ::openpmf_ccm::CCM_pep_manager_ContextImpl::_duplicate(tmp_context);
    else
        context_ = ::openpmf_ccm::CCM_pep_manager_ContextImpl::_nil();
        
    #else
    context_ = ::openpmf_ccm::CCM_pep_manager_ContextImpl::_narrow(context);
    
    #endif
    component_->set_context(context_);
}


void
PEP_ManagerImpl::ccm_activate()
    throw (CORBA::SystemException, Components::CCMException)
{
// BEGIN USER INSERT SECTION PEP_ManagerImpl::ccm_activate
// END USER INSERT SECTION PEP_ManagerImpl::ccm_activate
}


void
PEP_ManagerImpl::ccm_passivate()
    throw (CORBA::SystemException, Components::CCMException)
{
// BEGIN USER INSERT SECTION PEP_ManagerImpl::ccm_passivate
// END USER INSERT SECTION PEP_ManagerImpl::ccm_passivate
}


void
PEP_ManagerImpl::ccm_remove()
    throw (CORBA::SystemException, Components::CCMException)
{
// BEGIN USER INSERT SECTION PEP_ManagerImpl::ccm_remove
// END USER INSERT SECTION PEP_ManagerImpl::ccm_remove
}


// BEGIN USER INSERT SECTION HomePEP_ManagerExec
// END USER INSERT SECTION HomePEP_ManagerExec


HomePEP_ManagerExec::HomePEP_ManagerExec()
{
// BEGIN USER INSERT SECTION HomePEP_ManagerExec::HomePEP_ManagerExec
// END USER INSERT SECTION HomePEP_ManagerExec::HomePEP_ManagerExec
}


HomePEP_ManagerExec::~HomePEP_ManagerExec()
{
// BEGIN USER INSERT SECTION HomePEP_ManagerExec::~HomePEP_ManagerExec
// END USER INSERT SECTION HomePEP_ManagerExec::~HomePEP_ManagerExec

}


void
HomePEP_ManagerExec::set_context(Components::HomeContext_ptr ctx)
    throw (CORBA::SystemException, Components::CCMException)
{
    context_ = Components::HomeContext::_duplicate(ctx);
    
}


::Components::EnterpriseComponent_ptr
HomePEP_ManagerExec::create ()
    throw (CORBA::SystemException, Components::CreateFailure)
{
// BEGIN USER INSERT SECTION HomePEP_ManagerExec::create
// END USER INSERT SECTION HomePEP_ManagerExec::create
    return new PEP_ManagerImpl();
}


};


//
// entry point
//
::Components::HomeExecutorBase_ptr
create_pep_manager_homeE(void)
{
// BEGIN USER INSERT SECTION create_pep_manager_home
// END USER INSERT SECTION create_pep_manager_home

    return new ::openpmf_ccm::HomePEP_ManagerExec();
}

