/*****************************************************************************/
/* Qedo - Quality of Service Enabled Distributed Objects                     */
/*                                                                           */
/* Copyright (c) 2002/2003 by the Qedo Team                                  */
/*                                                                           */
/* http://qedo.berlios.de                                                    */
/*                                                                           */
/* This file is part of Qedo Generator                                       */
/*                                                                           */
/* Qedo Generator is free software; you can redistribute it and/or modify    */
/* it under the terms of the GNU General Public License as published by      */
/* the Free Software Foundation; either version 2 of the License, or         */
/* (at your option) any later version.                                       */
/*                                                                           */
/* Qedo Generator is distributed in the hope that it will be useful,         */
/* but WITHOUT ANY WARRANTY; without even the implied warranty of            */
/* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the             */
/* GNU General Public License for more details.                              */
/*                                                                           */
/* You should have received a copy of the GNU General Public License         */
/* along with Foobar; if not, write to the Free Software                     */
/* Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA */
/*                                                                           */
/*****************************************************************************/
#include "GeneratorPersistenceC.h"


namespace QEDO_CIDL_Generator {

GeneratorPersistenceC::GeneratorPersistenceC
( QEDO_ComponentRepository::CIDLRepository_impl *repository)
: CPPBase(repository), 
  bAbstract_(true),
  bRef_(false),
  strFilename_(""),
  strClassname_(""),
  strActBasename_(""),
  strName_(""),
  strContent_("")
{
}

GeneratorPersistenceC::~GeneratorPersistenceC
()
{
	if(!lValueTypes_.empty())
	{
		std::list<IR__::ValueDef_ptr>::iterator valuetype_iter;
	
		for(valuetype_iter = lValueTypes_.begin();
			valuetype_iter != lValueTypes_.end();
			valuetype_iter++)
		{
			//(dynamic_cast <IR__::ValueDef_ptr> (*valuetype_iter))->_remove_ref();
		}

		lValueTypes_.clear();
	}
}

void
GeneratorPersistenceC::generate(std::string target, std::string fileprefix)
{
	try { initialize(target, fileprefix); }
	catch (InitializeError) { return; }
	
	strFilename_ = file_prefix_ + "_PSS.cpp";
	
	out.open(strFilename_.c_str());
	out << "//\n";
	out << "// generated by Qedo\n";
	out << "//\n\n";
	out << "#ifndef _" << file_prefix_ << "_PSS_C_\n";
	out << "#define _" << file_prefix_ << "_PSS_C_\n\n\n";
	out << "#include \"" << file_prefix_ << "_PSS.h\"\n";
	out << "\n// BEGIN USER INSERT SECTION file\n";
	out << "// END USER INSERT SECTION file\n";

	doGenerate();

	out << "\n#endif\n";
	out.close();
}

void
GeneratorPersistenceC::check_for_generation(IR__::Contained_ptr item)
{
	// check if item is already known
	if (item_well_known(item))
		return;

	// check if item is already in the list or currently processed
	if ((this->sRecursion_.find(item->id())) != sRecursion_.end() || this->already_included (item))
		return;
	else
		sRecursion_.insert(item->id());
	
	CORBA::ULong i;
	CORBA::ULong ulLen;

	switch (item->def_kind()) 
	{
	case CORBA__::dk_Module :
	{
		IR__::ModuleDef_var a_module = IR__::ModuleDef::_narrow(item);

		// modules
		IR__::ContainedSeq_var contained_seq = a_module->contents(CORBA__::dk_Module, true);
		ulLen = contained_seq->length();
		for(i=0; i<ulLen; i++)
			check_for_generation((*contained_seq)[i]);

		// abstract storagehomes
		contained_seq = a_module->contents(CORBA__::dk_AbstractStorageHome, true);
		ulLen = contained_seq->length();
		for(i=0; i<ulLen; i++)
			check_for_generation((*contained_seq)[i]);

		// storagehomes
		contained_seq = a_module->contents(CORBA__::dk_StorageHome, true);
		ulLen = contained_seq->length();
		for(i=0; i<ulLen; i++)
			check_for_generation((*contained_seq)[i]);

		// valuetypes
		contained_seq = a_module->contents(CORBA__::dk_Value, true);
		ulLen = contained_seq->length();
		for(i=0; i<ulLen; i++)
		{
			IR__::ValueDef_ptr value = IR__::ValueDef::_narrow((*contained_seq)[i]);
			lValueTypes_.push_back(value);
		}

		break;
	}
	case CORBA__::dk_AbstractStorageType :
	{
		IR__::AbstractStorageTypeDef_var abs_storagetype = IR__::AbstractStorageTypeDef::_narrow(item);
		// insert this interface in generation list
		this->insert_to_generate(item);

		break;
	}
	case CORBA__::dk_StorageType :
	{
		IR__::StorageTypeDef_var storagetype = IR__::StorageTypeDef::_narrow(item);
		// insert this interface in generation list
		this->insert_to_generate(item);

		break;
	}
	case CORBA__::dk_AbstractStorageHome :
	{
		IR__::AbstractStorageHomeDef_var abs_storagehome = IR__::AbstractStorageHomeDef::_narrow(item);
		// insert this interface in generation list
		this->insert_to_generate(item);

		// managed abstract storage type
		IR__::AbstractStorageTypeDef_var abs_storagetype = abs_storagehome->managed_abstract_storagetype();
		this->check_for_generation(abs_storagetype);

		break;
	}
	case CORBA__::dk_StorageHome :
	{
		IR__::StorageHomeDef_var storagehome = IR__::StorageHomeDef::_narrow(item);	
		// insert this interface in generation list
		this->insert_to_generate(item);

		// managed storage type
		IR__::StorageTypeDef_var storagetype = storagehome->managed_storagetype();
		this->check_for_generation(storagetype);

		break; 
	}
	default:
		break;
	};

	sRecursion_.erase(item->id());
};

void
GeneratorPersistenceC::genDuplAndDown(std::string strClassName)
{
	//generate _duplicate and _downcast operation
	out << strClassName << "*\n";
	out << strClassName << "::_duplicate(const " << strClassName << "* obj)\n";
	out << "{\n";
	out.indent();
	out << "if( obj!=NULL )\n";
	out.indent();
	out << "obj->_add_ref();\n";
	out.unindent();
	out << "return obj;\n";
	out.unindent();
	out << "}\n\n";

	out << strClassName << "*\n";
	out << strClassName << "::_downcast(const " << strClassName << "* obj)\n";
	out << "{\n";
	out.indent();
	out << "return obj;\n";
	out.unindent();
	out << "}\n";
}

void
GeneratorPersistenceC::genAttributeWithNomalType(IR__::AttributeDef_ptr attribute, CORBA::TCKind att_type_kind)
{
	std::string attribute_name = mapName(attribute);
	IR__::IDLType_var attr_type = attribute->type_def();

	switch ( att_type_kind )
	{
		case CORBA::tk_string:
		case CORBA::tk_wstring:
			out << map_psdl_return_type(attr_type, false) << "\n";
			out << strClassname_;
			if(bRef_) out << "Ref";
			out << "::" << attribute_name << "(";
			out << map_psdl_parameter_type(attr_type, false) << " param)\n";
			out << "{\n";
			out.indent();
			out << attribute_name << "_ = param;\n";
			out << "setModified(true);\n";
			out.unindent();
			out << "}\n\n";
	}

	out << "void\n";
	out << strClassname_;
	if(bRef_) out << "Ref";
	out << "::" << attribute_name << "(";
	out << map_psdl_parameter_type(attr_type, true) << " param)\n";
	out << "{\n";
	out.indent();
	switch ( att_type_kind )
	{
		case CORBA::tk_string:
			out << "strcpy( " << attribute_name << "_, param );\n";
			break;
		case CORBA::tk_wstring:
			out << "wcscpy( " << attribute_name << "_, param );\n";
			break;
		default:
			out << attribute_name << "_ = param;\n";
	}
	out << "setModified(true);\n";
	out.unindent();
	out << "}\n\n";

	// the fourth operation only for string and wstring
	if(attr_type->type()->kind()==CORBA::tk_string)
	{
		out << "void\n";
		out << strClassname_;
		if(bRef_) out << "Ref";
		out << "::" << attribute_name << "(CORBA::String_var& param)\n";
		out << "{\n";
		out.indent();
		out << attribute_name << "_ = (char*)param;\n";
		out << "setModified(true);\n";
		out.unindent();
		out << "}\n\n";
	}
	else if(attr_type->type()->kind()==CORBA::tk_wstring)
	{
		out << "void\n";
		out << strClassname_;
		if(bRef_) out << "Ref";
		out << "::" << attribute_name << "(CORBA::WString_var& param)\n";
		out << "{\n";
		out.indent();
		out << attribute_name << "_ = (char*)param;\n";
		out << "setModified(true);\n";
		out.unindent();
		out << "}\n\n";
	}
}

void
GeneratorPersistenceC::genAttributeWithOtherType(IR__::AttributeDef_ptr attribute, CORBA::TCKind att_type_kind)
{
	std::string attribute_name = mapName(attribute);
	IR__::IDLType_var attr_type = attribute->type_def();
	
	out << map_psdl_return_type(attr_type, false) << "\n";
	out << strClassname_;
	if(bRef_) out << "Ref";
	out << "::" << attribute_name << "(";
	out << map_psdl_parameter_type(attr_type, false) << " param)\n";
	out << "{\n";
	out.indent();
	out << "return " << attribute_name << "_;\n";
	out.unindent();
	out << "}\n\n";
	
	out << "void\n";
	out << strClassname_;
	if(bRef_) out << "Ref";
	out << "::" << attribute_name << "(";
	out << map_psdl_parameter_type(attr_type, true) << " param)\n";
	out << "{\n";
	out.indent();
	if( attr_type->type()->kind() == CORBA::tk_value )
	{
		std::list<IR__::ValueDef_ptr>::iterator valuetype_iter;
		for(valuetype_iter = lValueTypes_.begin();
			valuetype_iter != lValueTypes_.end();
			valuetype_iter++)
		{
			IR__::ValueDef_var value = IR__::ValueDef::_narrow(*valuetype_iter);
			std::string attr_type_name = map_attribute_type(attribute->type_def());
			if(attr_type_name.find(mapName(value))!=std::string::npos)
			{
				IR__::ContainedSeq_var contained_seq = value->contents(CORBA__::dk_ValueMember, true);
				for(CORBA::ULong j = 0; j < contained_seq->length(); j++)
				{
					IR__::ValueMemberDef_var vMember = IR__::ValueMemberDef::_narrow((*contained_seq)[j]);

					switch(psdl_check_type(vMember->type_def()))
					{
					case CPPBase::_SHORT:
					case CPPBase::_INT:
					case CPPBase::_LONG:
					case CPPBase::_STRING:
						out << attribute_name << "_->" << mapName(vMember) << "( param." << mapName(vMember) << "() );\n";
						break;
					}
				}
				break;
			}
		}
	}
	else
	{
		out << attribute_name << "_ = param;\n";
	}
	out << "setModified(true);\n";
	out.unindent();
	out << "}\n\n";
}

void
GeneratorPersistenceC::doAttribute(IR__::AttributeDef_ptr attribute)
{
	out << "\n//\n// " << attribute->id() << "\n//\n";
	std::string attribute_name = mapName(attribute);
	IR__::IDLType_var attr_type = attribute->type_def();
	
	// read only
	out << map_psdl_return_type(attr_type, true) << "\n";
	out << strClassname_;
	if(bRef_) out << "Ref";
	out << "::" << attribute_name << "() const\n";
	out << "{\n";
	out.indent();
	out << "return " << attribute_name << "_;\n";
	out.unindent();
	out << "}\n\n";

	// not read only
	if(attribute->mode() == IR__::ATTR_NORMAL)
	{
		CORBA::TCKind att_type_kind = attr_type->type()->kind();
		switch ( att_type_kind )
		{
			case CORBA::tk_short:
			case CORBA::tk_long:
			case CORBA::tk_longlong:
			case CORBA::tk_ushort:
			case CORBA::tk_ulong:
			case CORBA::tk_ulonglong:
			case CORBA::tk_float:
			case CORBA::tk_double:
			case CORBA::tk_longdouble:
			case CORBA::tk_boolean:
			case CORBA::tk_char:
			case CORBA::tk_wchar:
			case CORBA::tk_octet:
			case CORBA::tk_string:
			case CORBA::tk_wstring:
				genAttributeWithNomalType(attribute, att_type_kind);
				break;
			default:
				genAttributeWithOtherType(attribute, att_type_kind);
		}
	}
}

void
GeneratorPersistenceC::genOperation(IR__::OperationDef_ptr operation, IR__::IDLType_ptr ret_type)
{
	out << "\n//\n// " << operation->id() << "\n//\n";
	out << map_psdl_return_type(ret_type, false) << "\n";
	out << strClassname_;
	if(bRef_) out << "Ref";
	out << "::" << mapName(operation) << "(";

	// parameters
	IR__::ParDescriptionSeq_var pards = operation->params();
	for( CORBA::ULong i=0; i<pards->length(); i++)
	{
		IR__::ParameterDescription pardescr = (*pards)[i];
		if (pardescr.mode == IR__::PARAM_IN) {
			out << map_in_parameter_type (pardescr.type_def) << " " << std::string(pardescr.name);
		};
		if (pardescr.mode == IR__::PARAM_OUT) {
			out << map_out_parameter_type (pardescr.type_def) << " " << std::string(pardescr.name);
		};
		if (pardescr.mode == IR__::PARAM_INOUT) {
			out << map_inout_parameter_type (pardescr.type_def) << " " << std::string(pardescr.name);
		};
		if((i+1)!=pards->length()) { out << ", "; }
	};

	out << ")\n";
	out << "{\n// BEGIN USER INSERT SECTION " << strClassname_;
	if(bRef_) out << "Ref";
	out << "::" << mapName(operation) << "()\n";
	out << "// END USER INSERT SECTION " << strClassname_;
	if(bRef_) out << "Ref";
	out << "::" << mapName(operation) << "()\n}\n\n";
}

void
GeneratorPersistenceC::doOperation(IR__::OperationDef_ptr operation)
{
	genOperation(operation, operation->result_def());
}

void
GeneratorPersistenceC::genFactory(IR__::OperationDef_ptr operation, IR__::InterfaceDef_ptr inf_type, IR__::InterfaceDef_ptr inf_home )
{
	int iLength = 0;	
	bool bFound = false;
	std::string strTemp = "";
	std::string strDummy = "";
	stringstream strDisplay;
	IR__::AttributeDef_var attribute = 0;

	out << "\n//\n// " << operation->id() << "\n//\n";
	IR__::IDLType_var ret_type = IR__::IDLType::_narrow(inf_type);

	out << map_psdl_return_type(ret_type, false) << "\n";
	strDisplay << strClassname_ << "::" << mapName(operation) << "(";
	out << strDisplay.str();

	iLength = strDisplay.str().length();
	strDummy.append(iLength, ' ');
	
	out << "Pid* pid,\n";
	out << strDummy.c_str();
	out << "ShortPid* shortPid,\n";

	// parameters
	IR__::ParDescriptionSeq_var pards = operation->params();
	for( CORBA::ULong i=0; i<pards->length(); i++)
	{
		out << strDummy.c_str();
		IR__::ParameterDescription pardescr = (*pards)[i];
		if (pardescr.mode == IR__::PARAM_IN) {
			out << map_in_parameter_type (pardescr.type_def) << " " << std::string(pardescr.name);
		};
		if (pardescr.mode == IR__::PARAM_OUT) {
			out << map_out_parameter_type (pardescr.type_def) << " " << std::string(pardescr.name);
		};
		if (pardescr.mode == IR__::PARAM_INOUT) {
			out << map_inout_parameter_type (pardescr.type_def) << " " << std::string(pardescr.name);
		};
		if((i+1)!=pards->length()) { out << ",\n"; }
	};

	out << ")\n";
	out << "{\n";
	out.indent();

	//++++++++++++++++++++++++++++++++++++++++
	// INSERT sentence for FACTORY
	//++++++++++++++++++++++++++++++++++++++++
	IR__::AttributeDefSeq state_members = collectStateMembers(inf_type, CORBA__::dk_Create);
	out << "char* szTemp = new char[64];\n";
	out << "std::string strFactory = \"\";\n\n";
	out << "CatalogBase_ptr pCatalogBase = get_catalog();\n";
	out << "CatalogBaseImpl* pCatalogBaseImpl = dynamic_cast <CatalogBaseImpl*> (pCatalogBase);\n\n";
	strName_ = "strFactory";

	out << strName_ << " = \"INSERT INTO pid_content (pid, ownhome) VALUES ( \";\n";
	strContent_ = "\\'";
	out << genSQLLine(strName_, strContent_, false, false, false);
	strContent_ = "convertPidToString(pid)";
	out << genSQLLine(strName_, strContent_, false, false, false, true);
	strContent_ = "\\'";
	out << genSQLLine(strName_, strContent_, false, true, true);
	out << strName_ << " += \"\\\'" << inf_home->name() << "\\\' );\";\n\n";
	out << "if(!pCatalogBaseImpl->ExecuteSQL(" << strName_ << ".c_str()))\n";
	out.indent();
	out << "throw CORBA::BAD_PARAM();\n\n";
	out.unindent();

	out << strName_ << " = \"INSERT INTO " << inf_home->name() << " ( pid, spid, ";

	CORBA::ULong ulLen = state_members.length();
	for(i=0; i<ulLen; i++)
	{
		attribute = IR__::AttributeDef::_narrow(state_members[i]);
		if( attribute->type_def()->type()->kind() == CORBA::tk_value )
		{
			std::list<IR__::ValueDef_ptr>::iterator valuetype_iter;
			for(valuetype_iter = lValueTypes_.begin();
				valuetype_iter != lValueTypes_.end();
				valuetype_iter++)
			{
				IR__::ValueDef_var value = IR__::ValueDef::_narrow(*valuetype_iter);
				std::string attr_type_name = map_attribute_type(attribute->type_def());
				if(attr_type_name.find(mapName(value))!=std::string::npos)
				{
					IR__::ContainedSeq_var contained_seq = value->contents(CORBA__::dk_ValueMember, true);
					for(CORBA::ULong j = 0; j < contained_seq->length(); j++)
					{
						IR__::ValueMemberDef_var vMember = IR__::ValueMemberDef::_narrow((*contained_seq)[j]);
						out << "value_" << mapName(vMember);
						( (i+1)!=ulLen ) ? out << ", " : out << " ) \";\n";
					}
					break;
				}
			}
		}
		else
		{
			out << mapName(attribute);
			( (i+1)!=ulLen ) ? out << ", " : out << " ) \";\n";
		}
	}

	strContent_ = "VALUES (";
	out << genSQLLine(strName_, strContent_, false, false, true);
	strContent_ = "\\'";
	out << genSQLLine(strName_, strContent_, false, false, false);
	strContent_ = "convertPidToString(pid)";
	out << genSQLLine(strName_, strContent_, false, false, false, true);
	strContent_ = "\\'";
	out << genSQLLine(strName_, strContent_, false, true, true);
	strContent_ = "\\'";
	out << genSQLLine(strName_, strContent_, false, false, false);
	strContent_ = "convertSpidToString(shortPid)";
	out << genSQLLine(strName_, strContent_, false, false, false, true);
	strContent_ = "\\'";
	out << genSQLLine(strName_, strContent_, false, true, true);

	for(i=0; i<ulLen; i++)
	{
		bFound = false;
		strTemp = "";
		attribute = IR__::AttributeDef::_narrow(state_members[i]);
		
		for(CORBA::ULong j=0; j<pards->length(); j++)
		{
			IR__::ParameterDescription pardescr = (*pards)[j];	
			strTemp = std::string(pardescr.name);
			if(strTemp.compare(attribute->name())==0)
			{
				bFound = true;
				break;
			}
		}
		
		if(bFound)
		{
			if( attribute->type_def()->type()->kind() == CORBA::tk_value )
			{
				std::list<IR__::ValueDef_ptr>::iterator valuetype_iter;
				for(valuetype_iter = lValueTypes_.begin();
					valuetype_iter != lValueTypes_.end();
					valuetype_iter++)
				{
					IR__::ValueDef_var value = IR__::ValueDef::_narrow(*valuetype_iter);
					std::string attr_type_name = map_attribute_type(attribute->type_def());
					if(attr_type_name.find(mapName(value))!=std::string::npos)
					{
						IR__::ContainedSeq_var contained_seq = value->contents(CORBA__::dk_ValueMember, true);
						for(CORBA::ULong j = 0; j < contained_seq->length(); j++)
						{
							IR__::ValueMemberDef_var vMember = IR__::ValueMemberDef::_narrow((*contained_seq)[j]);
							switch(psdl_check_type(vMember->type_def()))
							{
							case CPPBase::_SHORT:
								out << "memset(szTemp, \'\\0\', 64);\n";
								out << "sprintf(szTemp, \"%hd\", " << strTemp << "->" << mapName(vMember) << "());\n";
								if((i+1)!=ulLen)
									out << strName_ << ".append(strcat(szTemp, \", \"));\n";
								else
									out << strName_ << ".append(strcat(szTemp, \" \"));\n";
								break;
							case CPPBase::_INT:
								out << "memset(szTemp, \'\\0\', 64);\n";
								out << "sprintf(szTemp, \"%d\", " << strTemp << "->" << mapName(vMember) << "());\n";
								if((i+1)!=ulLen)
									out << strName_ << ".append(strcat(szTemp, \", \"));\n";
								else
									out << strName_ << ".append(strcat(szTemp, \" \"));\n";
								break;
							case CPPBase::_LONG:
								out << "memset(szTemp, \'\\0\', 64);\n";
								out << "sprintf(szTemp, \"%ld\", " << strTemp << "->" << mapName(vMember) << "());\n";
								if((i+1)!=ulLen)
									out << strName_ << ".append(strcat(szTemp, \", \"));\n";
								else
									out << strName_ << ".append(strcat(szTemp, \" \"));\n";
								break;
							case CPPBase::_STRING:
								strContent_ = "\\'";
								out << genSQLLine(strName_, strContent_, false, false, false);
								strContent_ = strTemp + "->";
								strContent_ += mapName(vMember) + "()";
								out << genSQLLine(strName_, strContent_, false, false, false, true);
								strContent_ = "\\'";
								out << genSQLLine(strName_, strContent_, false, ((i+1)!=ulLen), true);
								break;
							}
						}
						break;
					}
				}
			}
			else
			{
				switch(psdl_check_type(attribute->type_def()))
				{
				case CPPBase::_SHORT:
					out << "memset(szTemp, \'\\0\', 64);\n";
					out << "sprintf(szTemp, \"%hd\", " << strTemp << ");\n";
					if((i+1)!=ulLen)
						out << strName_ << ".append(strcat(szTemp, \", \"));\n";
					else
						out << strName_ << ".append(strcat(szTemp, \" \"));\n";
					break;
				case CPPBase::_INT:
					out << "memset(szTemp, \'\\0\', 64);\n";
					out << "sprintf(szTemp, \"%d\", " << strTemp << ");\n";
					if((i+1)!=ulLen)
						out << strName_ << ".append(strcat(szTemp, \", \"));\n";
					else
						out << strName_ << ".append(strcat(szTemp, \" \"));\n";
					break;
				case CPPBase::_LONG:
					out << "memset(szTemp, \'\\0\', 64);\n";
					out << "sprintf(szTemp, \"%ld\", " << strTemp << ");\n";
					if((i+1)!=ulLen)
						out << strName_ << ".append(strcat(szTemp, \", \"));\n";
					else
						out << strName_ << ".append(strcat(szTemp, \" \"));\n";
					break;
				case CPPBase::_FLOAT:
					out << "memset(szTemp, \'\\0\', 64);\n";
					out << "sprintf(szTemp, \"%f\", " << strTemp << ");\n";
					if((i+1)!=ulLen)
						out << strName_ << ".append(strcat(szTemp, \", \"));\n";
					else
						out << strName_ << ".append(strcat(szTemp, \" \"));\n";
					break;
				case CPPBase::_DOUBLE:
					out << "memset(szTemp, \'\\0\', 64);\n";
					out << "sprintf(szTemp, \"%lf\", " << strTemp << ");\n";
					if((i+1)!=ulLen)
						out << strName_ << ".append(strcat(szTemp, \", \"));\n";
					else
						out << strName_ << ".append(strcat(szTemp, \" \"));\n";
					break;
				case CPPBase::_LONGDOUBLE:
					out << "memset(szTemp, \'\\0\', 64);\n";
					out << "sprintf(szTemp, \"%Lf\", " << strTemp << ");\n";
					if((i+1)!=ulLen)
						out << strName_ << ".append(strcat(szTemp, \", \"));\n";
					else
						out << strName_ << ".append(strcat(szTemp, \" \"));\n";
					break;
				case CPPBase::_STRING:
					strContent_ = "\\'";
					out << genSQLLine(strName_, strContent_, false, false, false);
					strContent_ = strTemp;
					out << genSQLLine(strName_, strContent_, false, false, false, true);
					strContent_ = "\\'";
					out << genSQLLine(strName_, strContent_, false, ((i+1)!=ulLen), true);
					break;
				case CPPBase::_BOOL:
					strContent_ = "convertBool2String(" + strTemp + ")";
					out << genSQLLine(strName_, strContent_, false, ((i+1)!=ulLen), false, true);
					strContent_ = "";
					out << genSQLLine(strName_, strContent_, false, false, true);
					break;
				}
			}
		}
		else
		{
			if( attribute->type_def()->type()->kind() == CORBA::tk_value )
			{
				std::list<IR__::ValueDef_ptr>::iterator valuetype_iter;
				for(valuetype_iter = lValueTypes_.begin();
					valuetype_iter != lValueTypes_.end();
					valuetype_iter++)
				{
					IR__::ValueDef_var value = IR__::ValueDef::_narrow(*valuetype_iter);
					std::string attr_type_name = map_attribute_type(attribute->type_def());
					if(attr_type_name.find(mapName(value))!=std::string::npos)
					{
						IR__::ContainedSeq_var contained_seq = value->contents(CORBA__::dk_ValueMember, true);
						for(CORBA::ULong j = 0; j < contained_seq->length(); j++)
						{
							strContent_ = "NULL";
							out << genSQLLine(strName_, strContent_, false, ((i+1)!=ulLen), true);
						}
					}
				}	
			}
			else
			{
				strContent_ = "NULL";
				out << genSQLLine(strName_, strContent_, false, ((i+1)!=ulLen), true);
			}
		}
	}
	strContent_ = ");";
	out << genSQLLine(strName_, strContent_, false, false, false);
	//++++++++++++++++++++++++++++++++++++++++
	// end of INSERT sentence for FACTORY !!!!
	//++++++++++++++++++++++++++++++++++++++++
	
	out << "\nif(pCatalogBaseImpl->ExecuteSQL(" << strName_ << ".c_str()))\n";
	out << "{\n";
	out.indent();
	out << "//use factory to create a storage object\n";
	out << "#ifdef ORBACUS_ORB\n";
	out << "StorageObjectFactory factory = new OBNative_CosPersistentState::StorageObjectFactory_pre();\n";
	out << "#endif\n";
	out << "#ifdef MICO_ORB\n";
	out << "StorageObjectFactory factory = new CosPersistentState::StorageObjectFactory_pre();\n";
	out << "#endif\n";
	out << "factory = pCatalogBaseImpl->getConnector()->register_storage_object_factory(\"\", factory);\n";
	out << "StorageObjectImpl* pObjectImpl = factory->create();\n";
	out << "factory->_remove_ref();\n";
	out << "lObjectes_.push_back(pObjectImpl);\n";
	out << map_psdl_return_type(ret_type, false) << " pActObject = dynamic_cast <" << map_psdl_return_type(ret_type, false) << "> (pObjectImpl);\n";
	out << "\n//set values to current storageobject incarnation\n";
	out << "//How to handle with pid, spid and the other member variables not given?\n";
	for(CORBA::ULong j=0; j<pards->length(); j++)
	{
		IR__::ParameterDescription pardescr = (*pards)[j];
		ret_type = pardescr.type_def;
		out << "pActObject->" << std::string(pardescr.name) << "(";
		if( ret_type->type()->kind() == CORBA::tk_value )
			out << "*"; // special for valuetype
		out << std::string(pardescr.name) << ");\n";
	}
	out << "\nreturn pActObject;\n";
	out.unindent();
	out << "}\n";
	out << "else\n";
	out.indent();
	out << "throw CORBA::BAD_PARAM();\n";
	out.unindent();

	out.unindent();
	out << "\n// BEGIN USER INSERT SECTION " << strClassname_ << "::" << mapName(operation) << "()\n";
	out << "// END USER INSERT SECTION " << strClassname_ << "::" << mapName(operation) << "()\n}\n\n";
}

void
GeneratorPersistenceC::doFactory(IR__::FactoryDef_ptr factory, IR__::InterfaceDef_ptr inf_def)
{
	if(bAbstract_)
	{
		IR__::AbstractStorageTypeDef_var abs_storagetype;
		IR__::AbstractStorageHomeDef_var abs_storagehome = IR__::AbstractStorageHomeDef::_narrow(inf_def);
		if(!CORBA::is_nil(abs_storagehome))
			abs_storagetype = abs_storagehome->managed_abstract_storagetype();
		if(!CORBA::is_nil(abs_storagetype))
			genFactory(factory, abs_storagetype, abs_storagehome);
	}
	else
	{
		IR__::StorageTypeDef_var storagetype;
		IR__::StorageHomeDef_var storagehome = IR__::StorageHomeDef::_narrow(inf_def);
		if(!CORBA::is_nil(storagehome))
			storagetype = storagehome->managed_storagetype();
		if(!CORBA::is_nil(storagetype))
			genFactory(factory, storagetype, storagehome);
	}
}

void
GeneratorPersistenceC::genKey(IR__::OperationDef_ptr operation, IR__::InterfaceDef_ptr inf_type, IR__::InterfaceDef_ptr inf_home, bool isRef)
{
	IR__::IDLType_var ret_type = IR__::IDLType::_narrow(inf_type);

	if(!isRef)
		out << "\n//\n// " << operation->id() << "\n//\n";
	char* szReturnType = map_psdl_return_type(ret_type, false);
	char* szOriginalType = map_psdl_return_type(ret_type, false);

	//since the definition of a abstract stoage type is not yet supported, 
	//we have to replcace the "*" with "Ref" for operation find_by_ref_... 
	if(isRef)
	{
		char* pdest = strstr( szReturnType, "*" );
		if( pdest != NULL )
		{
			memset(pdest, '\0', 1);
			strcat(szReturnType, "Ref");
		}
	}
	
	out << szReturnType << "\n" << strClassname_ << "::";
	isRef ? out << "find_ref_by_" : out << "find_by_";
	out << mapName(operation) << "(";

	// parameters
	IR__::ParDescriptionSeq_var pards = operation->params();
	for( CORBA::ULong i=0; i<pards->length(); i++)
	{
		IR__::ParameterDescription pardescr = (*pards)[i];
		if (pardescr.mode == IR__::PARAM_IN) {
			out << map_in_parameter_type (pardescr.type_def) << " " << std::string(pardescr.name);
		};
		if (pardescr.mode == IR__::PARAM_OUT) {
			out << map_out_parameter_type (pardescr.type_def) << " " << std::string(pardescr.name);
		};
		if (pardescr.mode == IR__::PARAM_INOUT) {
			out << map_inout_parameter_type (pardescr.type_def) << " " << std::string(pardescr.name);
		};

		if((i+1)!=pards->length()) { out << ", "; }
	};

	out << ")";
	
	if(!isRef)
	{
		out << "\n";
		out.indent();
		out << "throw(CosPersistentState::NotFound";
		handleException(operation);
		out << ")";
		out.unindent();
	}
	
	out << "\n{\n";
	out.indent();

	//++++++++++++++++++++++++++++++++++++++++
	// SELECT sentence for KEY
	//++++++++++++++++++++++++++++++++++++++++
	if(!isRef)
		out << szReturnType << " pActObject = NULL;\n";
	else
		out << szOriginalType << " pActObject = NULL;\n";
	out << "char* szTemp = new char[64];\n";
	out << "std::string strKey = \"\";\n\n";
	strName_ = "strKey";
	strContent_ = "SELECT pid FROM ";
	strContent_ += inf_home->name();
	out << genSQLLine(strName_, strContent_, true, false, true);
	strContent_ = "WHERE";
	out << genSQLLine(strName_, strContent_, false, false, true);

	CORBA::ULong ulLen = pards->length();

	for( i=0; i<ulLen; i++ )
	{
		IR__::ParameterDescription pardescr = (*pards)[i];
	
		if( pardescr.type_def->type()->kind() == CORBA::tk_value )
		{
			std::list<IR__::ValueDef_ptr>::iterator valuetype_iter;
			for(valuetype_iter = lValueTypes_.begin();
				valuetype_iter != lValueTypes_.end();
				valuetype_iter++)
			{
				IR__::ValueDef_var value = IR__::ValueDef::_narrow(*valuetype_iter);
				std::string attr_type_name = map_attribute_type(pardescr.type_def);
				if(attr_type_name.find(mapName(value))!=std::string::npos)
				{
					IR__::ContainedSeq_var contained_seq = value->contents(CORBA__::dk_ValueMember, true);
					for(CORBA::ULong j = 0; j < contained_seq->length(); j++)
					{
						IR__::ValueMemberDef_var vMember = IR__::ValueMemberDef::_narrow((*contained_seq)[j]);
						strContent_ = "value_" + mapName(vMember);
						if(psdl_check_type(vMember->type_def())!=CPPBase::_STRING)
							strContent_ += " =";
						else
							strContent_ += " LIKE";
						out << genSQLLine(strName_, strContent_, false, false, true);

						switch(psdl_check_type(vMember->type_def()))
						{
						case CPPBase::_SHORT:
							out << "memset(szTemp, \'\\0\', 64);\n";
							out << "sprintf(szTemp, \"%hd\", " << std::string(pardescr.name) << "->" << mapName(vMember) << "());\n";
							if((i+1)!=ulLen)
								out << strName_ << ".append(strcat(szTemp, \", \"));\n";
							else
								out << strName_ << ".append(strcat(szTemp, \" \"));\n";
							break;
						case CPPBase::_INT:
							out << "memset(szTemp, \'\\0\', 64);\n";
							out << "sprintf(szTemp, \"%d\", " << std::string(pardescr.name) << "->" << mapName(vMember) << "());\n";
							if((i+1)!=ulLen)
								out << strName_ << ".append(strcat(szTemp, \", \"));\n";
							else
								out << strName_ << ".append(strcat(szTemp, \" \"));\n";
							break;
						case CPPBase::_LONG:
							out << "memset(szTemp, \'\\0\', 64);\n";
							out << "sprintf(szTemp, \"%ld\", " << std::string(pardescr.name) << "->" << mapName(vMember) << "());\n";
							if((i+1)!=ulLen)
								out << strName_ << ".append(strcat(szTemp, \", \"));\n";
							else
								out << strName_ << ".append(strcat(szTemp, \" \"));\n";
							break;
						case CPPBase::_STRING:
							strContent_ = "\\'";
							out << genSQLLine(strName_, strContent_, false, false, false);
							strContent_ = std::string(pardescr.name) + "->";
							strContent_ += mapName(vMember) + "()";
							out << genSQLLine(strName_, strContent_, false, false, false, true);
							strContent_ = "\\'";
							out << genSQLLine(strName_, strContent_, false, ((i+1)!=ulLen), true);
							break;
						}
					}
					break;
				}
			}
		}
		else
		{
			strContent_ = std::string(pardescr.name);

			if(psdl_check_type(pardescr.type_def)!=CPPBase::_STRING)
				strContent_ += " =";
			else
				strContent_ += " LIKE";
			out << genSQLLine(strName_, strContent_, false, false, true);

			switch(psdl_check_type(pardescr.type_def))
			{
			case CPPBase::_SHORT:
				out << "memset(szTemp, \'\\0\', 64);\n";
				out << "sprintf(szTemp, \"%hd\", " << std::string(pardescr.name) << ");\n";
				if((i+1)!=ulLen)
					out << strName_ << ".append(strcat(szTemp, \", \"));\n";
				else
					out << strName_ << ".append(strcat(szTemp, \" \"));\n";
				break;
			case CPPBase::_INT:
				out << "memset(szTemp, \'\\0\', 64);\n";
				out << "sprintf(szTemp, \"%d\", " << std::string(pardescr.name) << ");\n";
				if((i+1)!=ulLen)
					out << strName_ << ".append(strcat(szTemp, \", \"));\n";
				else
					out << strName_ << ".append(strcat(szTemp, \" \"));\n";
				break;
			case CPPBase::_LONG:
				out << "memset(szTemp, \'\\0\', 64);\n";
				out << "sprintf(szTemp, \"%ld\", " << std::string(pardescr.name) << ");\n";
				if((i+1)!=ulLen)
					out << strName_ << ".append(strcat(szTemp, \", \"));\n";
				else
					out << strName_ << ".append(strcat(szTemp, \" \"));\n";
				break;
			case CPPBase::_FLOAT:
				out << "memset(szTemp, \'\\0\', 64);\n";
				out << "sprintf(szTemp, \"%f\", " << std::string(pardescr.name) << ");\n";
				if((i+1)!=ulLen)
					out << strName_ << ".append(strcat(szTemp, \", \"));\n";
				else
					out << strName_ << ".append(strcat(szTemp, \" \"));\n";
				break;
			case CPPBase::_DOUBLE:
				out << "memset(szTemp, \'\\0\', 64);\n";
				out << "sprintf(szTemp, \"%lf\", " << std::string(pardescr.name) << ");\n";
				if((i+1)!=ulLen)
					out << strName_ << ".append(strcat(szTemp, \", \"));\n";
				else
					out << strName_ << ".append(strcat(szTemp, \" \"));\n";
				break;
			case CPPBase::_LONGDOUBLE:
				out << "memset(szTemp, \'\\0\', 64);\n";
				out << "sprintf(szTemp, \"%Lf\", " << std::string(pardescr.name) << ");\n";
				if((i+1)!=ulLen)
					out << strName_ << ".append(strcat(szTemp, \", \"));\n";
				else
					out << strName_ << ".append(strcat(szTemp, \" \"));\n";
				break;
			case CPPBase::_STRING:
				strContent_ = "\\'";
				out << genSQLLine(strName_, strContent_, false, false, false);
				strContent_ = std::string(pardescr.name);
				out << genSQLLine(strName_, strContent_, false, false, false, true);
				strContent_ = "\\'";
				out << genSQLLine(strName_, strContent_, false, ((i+1)!=ulLen), true);
				break;
			case CPPBase::_BOOL:
				strContent_ = "convertBool2String(" + std::string(pardescr.name) + ")";
				out << genSQLLine(strName_, strContent_, false, ((i+1)!=ulLen), false, true);
				strContent_ = "";
				out << genSQLLine(strName_, strContent_, false, false, true);
				break;
			}
		}
	}
	strContent_ = ");";
	out << genSQLLine(strName_, strContent_, false, false, false);
	//++++++++++++++++++++++++++++++++++++++++
	// end of SELECT sentence for KEY !!!!!!!!
	//++++++++++++++++++++++++++++++++++++++++

	out << "\nif(!Open(" << strName_ << ".c_str()))\n";
	out.indent();
	out << "throw CosPersistentState::NotFound();\n\n";
	out.unindent();
	out << "if (GetFieldCount()<=0)\n{\n";
	out.indent();
	out << "Close();\n";
	out << "throw CosPersistentState::NotFound();\n";
	out.unindent();
	out << "}\n\n";
	out << "unsigned char* szPid = new unsigned char[254];\n";
	out << "memset(szPid, \'\\0\', 254);\n";
	out << "GetFieldValue(0, szPid);\n";
	out << "Close();\n\n";
	out << "std::string strPid = \"\";\n";
	out << "strPid.append((const char*)szPid);\n";
	out << "StorageObjectBase pObject = find_by_pid(strPid);\n";
	if(!isRef)
	{
		out << "pActObject = dynamic_cast <" << szReturnType << "> (pObject);\n\n";
		out << "return pActObject;\n";
	}
	else
	{
		out << "pActObject = dynamic_cast <" << szOriginalType << "> (pObject);\n";
		out << szReturnType << " ref = pActObject;\n\n";
		out << "return ref;\n";
	}

	out.unindent();
	out << "\n// BEGIN USER INSERT SECTION " << strClassname_;
	isRef ? out << "::find_ref_by_" : out << "::find_by_";
	out << mapName(operation) << "()\n";
	out << "// END USER INSERT SECTION " << strClassname_;
	isRef ? out << "::find_ref_by_" : out << "::find_by_";
	out << mapName(operation) << "()\n}\n\n";
}

void
GeneratorPersistenceC::doKey(IR__::KeyDef_ptr key, IR__::InterfaceDef_ptr inf_def)
{
	if(bAbstract_)
	{
		IR__::AbstractStorageTypeDef_var abs_storagetype;
		IR__::AbstractStorageHomeDef_var abs_storagehome = IR__::AbstractStorageHomeDef::_narrow(inf_def);
		if(!CORBA::is_nil(abs_storagehome))
			abs_storagetype = abs_storagehome->managed_abstract_storagetype();
		if(!CORBA::is_nil(abs_storagetype))
		{
			genKey(key, abs_storagetype, abs_storagehome, false);
			genKey(key, abs_storagetype, abs_storagehome, true);
		}
	}
	else
	{
		IR__::StorageTypeDef_var storagetype;
		IR__::StorageHomeDef_var storagehome = IR__::StorageHomeDef::_narrow(inf_def);
		if(!CORBA::is_nil(storagehome))
			storagetype = storagehome->managed_storagetype();
		if(!CORBA::is_nil(storagetype))
		{
			genKey(key, storagetype, storagehome, false);
			genKey(key, storagetype, storagehome, true);
		}
	}
}

void 
GeneratorPersistenceC::doException(IR__::ExceptionDef_ptr except)
{
	out << ", " << mapFullName(except);
}

void
GeneratorPersistenceC::genAbstractObjsForConcreteType(IR__::AbstractStorageTypeDef_ptr abs_storagetype)
{
	IR__::InterfaceDefSeq_var abs_storagetype_seq = abs_storagetype->base_abstract_storagetypes();
	
	for(CORBA::ULong i=0; i<abs_storagetype_seq->length(); i++) 
	{
		handleAttribute((*abs_storagetype_seq)[i]);
		handleOperation((*abs_storagetype_seq)[i]);
	}

	handleAttribute(abs_storagetype);
	handleOperation(abs_storagetype);
}

void
GeneratorPersistenceC::genStorageTypeBody(IR__::StorageTypeDef_ptr storagetype/*, bool isRef*/)
{
	strClassname_ = std::string(storagetype->name());

	IR__::InterfaceDefSeq_var supported_infs = storagetype->supported_interfaces();
	/*
	IR__::AbstractStorageTypeDef_var abs_storagetype = 
		IR__::AbstractStorageTypeDef::_narrow((*supported_infs)[0]);
	*/
	homeIter_ = homeMap_.find(storagetype->name());
	std::string strStoragehomeName = homeIter_->second;

	out << "// BEGIN USER INSERT SECTION " << strClassname_ << "\n";
	//isRef ? out << "Ref\n" : out << "\n";
	out << "// END USER INSERT SECTION " << strClassname_ << "\n\n";
	//isRef ? out << "Ref\n\n" : out << "\n\n";
	out << strClassname_;
	//if(isRef) out << "Ref";
	out << "::" << strClassname_;
	//if(isRef) out << "Ref";
	out	<< "()\n";
	out << "{\n";
	out.indent();

	//+++++++++++++++++++++++++++++++++++++++++++++++
	// SELECT sentence for strSelect_ in StorageType
	//+++++++++++++++++++++++++++++++++++++++++++++++
	out << "char* szTemp = new char[64];\n\n";
	out << "// for CatalogBase::refresh()\n";
	strName_ = "strSelect_";
	strContent_ = "SELECT * FROM ";
	strContent_ += strStoragehomeName;
	out << genSQLLine(strName_, strContent_, true, false, true);
	strContent_ = "WHERE pid LIKE \\'";
	out << genSQLLine(strName_, strContent_, false, false, false);
	strContent_ = "convertPidToString(pPid_)";
	out << genSQLLine(strName_, strContent_, false, false, false, true);
	strContent_ = "\\';";
	out << genSQLLine(strName_, strContent_, false, false, false);
	out << "\n";
	//++++++++++++++++++++++++++++++++++++++++++++++++++++++
	// end of SELECT sentence for strSelect_ in StorageType
	//++++++++++++++++++++++++++++++++++++++++++++++++++++++

	//+++++++++++++++++++++++++++++++++++++++++++++++
	// UPDATE sentence for strUpdate_ in StorageType
	//+++++++++++++++++++++++++++++++++++++++++++++++
	IR__::AttributeDef_var attribute = 0;
	IR__::AttributeDefSeq state_members = collectStateMembers(storagetype, CORBA__::dk_Create);
	CORBA::ULong ulLen = state_members.length();
	out << "// for CatalogBase::flush()\n";
	strName_ = "strUpdate_";
	strContent_ = "UPDATE ";
	strContent_ += strStoragehomeName;
	strContent_ += " SET";
	out << genSQLLine(strName_, strContent_, true, false, true);

	for(CORBA::ULong i=0; i<ulLen; i++)
	{
		attribute = IR__::AttributeDef::_narrow(state_members[i]);

		if( attribute->type_def()->type()->kind() == CORBA::tk_value )
		{
			std::list<IR__::ValueDef_ptr>::iterator valuetype_iter;
			for(valuetype_iter = lValueTypes_.begin();
				valuetype_iter != lValueTypes_.end();
				valuetype_iter++)
			{
				IR__::ValueDef_var value = IR__::ValueDef::_narrow(*valuetype_iter);
				std::string attr_type_name = map_attribute_type(attribute->type_def());
				if(attr_type_name.find(mapName(value))!=std::string::npos)
				{
					IR__::ContainedSeq_var contained_seq = value->contents(CORBA__::dk_ValueMember, true);
					for(CORBA::ULong j = 0; j < contained_seq->length(); j++)
					{
						IR__::ValueMemberDef_var vMember = IR__::ValueMemberDef::_narrow((*contained_seq)[j]);
						strContent_ = "value_" + mapName(vMember) + " = ";

						switch(psdl_check_type(vMember->type_def()))
						{
						case CPPBase::_SHORT:
							out << genSQLLine(strName_, strContent_, false, false, false);
							out << "memset(szTemp, \'\\0\', 64);\n";
							out << "sprintf(szTemp, \"%hd\", " << mapName(attribute) << "_->" << mapName(vMember) << "());\n";
							if((i+1)!=ulLen)
								out << strName_ << ".append(strcat(szTemp, \", \"));\n";
							else
								out << strName_ << ".append(strcat(szTemp, \" \"));\n";
							break;
						case CPPBase::_INT:
							out << genSQLLine(strName_, strContent_, false, false, false);
							out << "memset(szTemp, \'\\0\', 64);\n";
							out << "sprintf(szTemp, \"%d\", " << mapName(attribute) << "_->" << mapName(vMember) << "());\n";
							if((i+1)!=ulLen)
								out << strName_ << ".append(strcat(szTemp, \", \"));\n";
							else
								out << strName_ << ".append(strcat(szTemp, \" \"));\n";
							break;
						case CPPBase::_LONG:
							out << genSQLLine(strName_, strContent_, false, false, false);
							out << "memset(szTemp, \'\\0\', 64);\n";
							out << "sprintf(szTemp, \"%ld\", " << mapName(attribute) << "_->" << mapName(vMember) << "());\n";
							if((i+1)!=ulLen)
								out << strName_ << ".append(strcat(szTemp, \", \"));\n";
							else
								out << strName_ << ".append(strcat(szTemp, \" \"));\n";
							break;
						case CPPBase::_STRING:
							strContent_ += "\\'";
							out << genSQLLine(strName_, strContent_, false, false, false);
							strContent_ = mapName(attribute) + "_->";
							strContent_ += mapName(vMember) + "()";
							out << genSQLLine(strName_, strContent_, false, false, false, true);
							strContent_ = "\\'";
							out << genSQLLine(strName_, strContent_, false, ((i+1)!=ulLen), true);
							break;
						}
					}
					break;
				}
			}
		}
		else
		{
			strContent_ = mapName(attribute) + " = ";

			switch(psdl_check_type(attribute->type_def()))
			{
			case CPPBase::_SHORT:
				out << genSQLLine(strName_, strContent_, false, false, false);
				out << "memset(szTemp, \'\\0\', 64);\n";
				out << "sprintf(szTemp, \"%hd\", " << mapName(attribute) << "_);\n";
				if((i+1)!=ulLen)
					out << strName_ << ".append(strcat(szTemp, \", \"));\n";
				else
					out << strName_ << ".append(strcat(szTemp, \" \"));\n";
				break;
			case CPPBase::_INT:
				out << genSQLLine(strName_, strContent_, false, false, false);
				out << "memset(szTemp, \'\\0\', 64);\n";
				out << "sprintf(szTemp, \"%d\", " << mapName(attribute) << "_);\n";
				if((i+1)!=ulLen)
					out << strName_ << ".append(strcat(szTemp, \", \"));\n";
				else
					out << strName_ << ".append(strcat(szTemp, \" \"));\n";
				break;
			case CPPBase::_LONG:
				out << genSQLLine(strName_, strContent_, false, false, false);
				out << "memset(szTemp, \'\\0\', 64);\n";
				out << "sprintf(szTemp, \"%ld\", " << mapName(attribute) << "_);\n";
				if((i+1)!=ulLen)
					out << strName_ << ".append(strcat(szTemp, \", \"));\n";
				else
					out << strName_ << ".append(strcat(szTemp, \" \"));\n";
				break;
			case CPPBase::_FLOAT:
				out << genSQLLine(strName_, strContent_, false, false, false);
				out << "memset(szTemp, \'\\0\', 64);\n";
				out << "sprintf(szTemp, \"%f\", " << mapName(attribute) << "_);\n";
				if((i+1)!=ulLen)
					out << strName_ << ".append(strcat(szTemp, \", \"));\n";
				else
					out << strName_ << ".append(strcat(szTemp, \" \"));\n";
				break;
			case CPPBase::_DOUBLE:
				out << genSQLLine(strName_, strContent_, false, false, false);
				out << "memset(szTemp, \'\\0\', 64);\n";
				out << "sprintf(szTemp, \"%lf\", " << mapName(attribute) << "_);\n";
				if((i+1)!=ulLen)
					out << strName_ << ".append(strcat(szTemp, \", \"));\n";
				else
					out << strName_ << ".append(strcat(szTemp, \" \"));\n";
				break;
			case CPPBase::_LONGDOUBLE:
				out << genSQLLine(strName_, strContent_, false, false, false);
				out << "memset(szTemp, \'\\0\', 64);\n";
				out << "sprintf(szTemp, \"%Lf\", " << mapName(attribute) << "_);\n";
				if((i+1)!=ulLen)
					out << strName_ << ".append(strcat(szTemp, \", \"));\n";
				else
					out << strName_ << ".append(strcat(szTemp, \" \"));\n";
				break;
			case CPPBase::_STRING:
				strContent_ += "\\'";
				out << genSQLLine(strName_, strContent_, false, false, false);
				strContent_ = mapName(attribute) + "_";
				out << genSQLLine(strName_, strContent_, false, false, false, true);
				strContent_ = "\\'";
				out << genSQLLine(strName_, strContent_, false, ((i+1)!=ulLen), true);
				break;
			case CPPBase::_BOOL:
				out << genSQLLine(strName_, strContent_, false, false, false);
				strContent_ = "convertBool2String(" + mapName(attribute) + "_)";
				out << genSQLLine(strName_, strContent_, false, ((i+1)!=ulLen), false, true);
				strContent_ = "";
				out << genSQLLine(strName_, strContent_, false, false, true);
				break;
			}
		}
	}

	strContent_ = "WHERE pid LIKE \\'";
	out << genSQLLine(strName_, strContent_, false, false, false);
	strContent_ = "convertPidToString(pPid_)";
	out << genSQLLine(strName_, strContent_, false, false, false, true);
	strContent_ = "\\';";
	out << genSQLLine(strName_, strContent_, false, false, false);
	out << "\n";
	//++++++++++++++++++++++++++++++++++++++++++++++++++++++
	// end of UPDATE sentence for strUpdate_ in StorageType
	//++++++++++++++++++++++++++++++++++++++++++++++++++++++

	out.unindent();
	out << "// BEGIN USER INSERT SECTION " << strClassname_;
	//if(isRef) out << "Ref";
	out << "::" << strClassname_;
	//if(isRef) out << "Ref";
	out << "()\n";
	out << "// END USER INSERT SECTION " <<strClassname_;
	//if(isRef) out << "Ref";
	out << "::" << strClassname_;
	//if(isRef) out << "Ref";
	out << "()\n}\n\n";
	out << strClassname_;
	//if(isRef) out << "Ref";
	out << "::~" << strClassname_;
	//if(isRef) out << "Ref";
	out << "()\n";
	out << "{\n// BEGIN USER INSERT SECTION " << strClassname_;
	//if(isRef) out << "Ref";
	out << "::~" << strClassname_;
	//if(isRef) out << "Ref";
	out << "()\n";
	out << "// END USER INSERT SECTION " <<strClassname_;
	//if(isRef) out << "Ref";
	out << "::~" << strClassname_;
	//if(isRef) out << "Ref";
	out << "()\n}\n\n";

	//bRef_ = isRef;
	//genAbstractObjsForConcreteType(abs_storagetype);
	for(CORBA::ULong i = 0; i < supported_infs->length(); i++) 
	{
		IR__::AbstractStorageTypeDef_var abs_storage_type_inh;
		abs_storage_type_inh = IR__::AbstractStorageTypeDef::_narrow((*supported_infs)[i]);
		genAbstractObjsForConcreteType(abs_storage_type_inh);
	};
	handleAttribute(storagetype);
	handleOperation(storagetype);

	out << "void\n";
	out << strClassname_;
	//if(isRef) out << "Ref";
	out << "::" << "setValue(std::map<std::string, CORBA::Any> valueMap)\n";
	out << "{\n";
	out.indent();
	out << "char* szTemp;\n";
	out << "bool bTemp = false;\n";
	out << "std::map <std::string, CORBA::Any> :: const_iterator colIter;\n\n";
	out << "colIter = valueMap.find(\"pid\");\n";
	out << "colIter->second >>= pPid_;\n\n";
	out << "colIter = valueMap.find(\"spid\");\n";
	out << "colIter->second >>= pShortPid_;\n\n";

	for(CORBA::ULong i=0; i<ulLen; i++)
	{
		attribute = IR__::AttributeDef::_narrow(state_members[i]);

		if( attribute->type_def()->type()->kind() == CORBA::tk_value )
		{
			std::list<IR__::ValueDef_ptr>::iterator valuetype_iter;
			for(valuetype_iter = lValueTypes_.begin();
				valuetype_iter != lValueTypes_.end();
				valuetype_iter++)
			{
				IR__::ValueDef_var value = IR__::ValueDef::_narrow(*valuetype_iter);
				std::string attr_type_name = map_attribute_type(attribute->type_def());
				if(attr_type_name.find(mapName(value))!=std::string::npos)
				{
					IR__::ContainedSeq_var contained_seq = value->contents(CORBA__::dk_ValueMember, true);
					for(CORBA::ULong j = 0; j < contained_seq->length(); j++)
					{
						IR__::ValueMemberDef_var vMember = IR__::ValueMemberDef::_narrow((*contained_seq)[j]);
						out << "colIter = valueMap.find(\"value_" << mapName(vMember) << "\");\n";

						switch(psdl_check_type(vMember->type_def()))
						{
						case CPPBase::_SHORT:
						case CPPBase::_INT:
						case CPPBase::_LONG:
						case CPPBase::_FLOAT:
						case CPPBase::_DOUBLE:
						case CPPBase::_LONGDOUBLE:
						case CPPBase::_STRING:
							out << "colIter->second >>= szTemp;\n";
							out << mapName(attribute) << "_->" << mapName(vMember) << "(szTemp);\n\n";
							break;
						case CPPBase::_BOOL:
							out << "colIter->second >>= CORBA::Any::to_boolean(bTemp);\n";
							out << mapName(attribute) << "_->" << mapName(vMember) << "(bTemp);\n\n";
							break;
						}
					}
					break;
				}
			}
		}
		else
		{
			out << "colIter = valueMap.find(\"" << mapName(attribute) << "\");\n";

			switch(psdl_check_type(attribute->type_def()))
			{
			case CPPBase::_SHORT:
			case CPPBase::_INT:
			case CPPBase::_LONG:
			case CPPBase::_FLOAT:
			case CPPBase::_DOUBLE:
			case CPPBase::_LONGDOUBLE:
			case CPPBase::_STRING:
				out << "colIter->second >>= " << mapName(attribute) << "_;\n\n";
				break;
			case CPPBase::_BOOL:
				out << "colIter->second >>= CORBA::Any::to_boolean(" << mapName(attribute) << "_);\n\n";
				break;
			}
		}
	}
	out.unindent();
	out << "}\n\n";
	//genDuplAndDown(strClassname_);
	//out << "\n";
}

void
GeneratorPersistenceC::genBaseRefBody(std::string strTypeName)
{
	out << strTypeName << "Ref::" << strTypeName << "Ref() :\n";
	out.indent();
	out << "pObj_(NULL)\n";
	out.unindent();
	out << "{\n";
	out << "}\n\n";

	out << strTypeName << "Ref::" << strTypeName << "Ref(" << strTypeName << "* obj) :\n";
	out.indent();
	out << "pObj_(NULL)\n";
	out.unindent();
	out << "{\n";
	out.indent();
	out << "if( obj!= NULL )\n";
	out.indent();
	out << "pObj_ = obj;\n";
	out.unindent();
	out.unindent();
	out << "}\n\n";

	out << strTypeName << "Ref::" << strTypeName << "Ref(const " << strTypeName << "Ref& ref) :\n";
	out.indent();
	out << "pObj_(NULL)\n";
	out.unindent();
	out << "{\n";
	out.indent();
	out << "pObj_ = ref.deref();\n";
	out.unindent();
	out << "}\n\n";

	out << strTypeName << "Ref::~" << strTypeName << "Ref()\n";
	out << "{\n";
	out.indent();
	out << "if( pObj_!=NULL )\n";
	out.indent();
	out << "pObj_->_remove_ref();\n";
	out.unindent();
	out << "pObj_ = NULL;\n";
	out.unindent();
	out << "}\n\n";

	out << strTypeName << "Ref&\n";
	out << strTypeName << "Ref::operator=(const " << strTypeName << "Ref& ref)\n";
	out << "{\n";
	out.indent();
	out << "if( pObj_!=ref.pObj_ )\n";
	out << "{\n";
	out.indent();
	out << "if( pObj_!=NULL )\n";
	out.indent();
	out << "pObj_->_remove_ref();\n\n";
	out.unindent();
	out << "pObj_ = ref.pObj_;\n\n";
	out << "if( pObj_!=NULL )\n";
	out.indent();
	out << "pObj_->_add_ref();\n";
	out.unindent();
	out.unindent();
	out << "}\n\n";
	out << "return *this;\n";
	out.unindent();
	out << "}\n\n";
	
	out << strTypeName << "Ref&\n";
	out << strTypeName << "Ref::operator=(" << strTypeName << "* obj)\n";
	out << "{\n";
	out.indent();
	out << "if( pObj_!=NULL )\n";
	out.indent();
	out << "pObj_->_remove_ref();\n\n";
	out.unindent();
	out << "pObj_ = obj;\n\n";
	out << "return *this;\n";
	out.unindent();
	out << "}\n\n";

	out << strTypeName << "*\n";
	out << strTypeName << "Ref::operator->() const\n";
	out.indent();
	out << "throw(CORBA::SystemException)\n";
	out.unindent();
	out << "{\n";
	out.indent();
	out << "return pObj_;\n";
	out.unindent();
	out << "}\n\n";

	out << strTypeName << "*\n";
	out << strTypeName << "Ref::deref() const\n";
	out.indent();
	out << "throw(CORBA::SystemException)\n";
	out.unindent();
	out << "{\n";
	out.indent();
	out << "return pObj_;\n";
	out.unindent();
	out << "}\n\n";


	out << "void\n";
	out << strTypeName << "Ref::release()\n";
	out << "{\n";
	out.indent();
	out << "if( pObj_!=NULL )\n";
	out.indent();
	out << "pObj_->_remove_ref();\n";
	out.unindent();
	out << "pObj_ = NULL;\n";
	out.unindent();
	out << "}\n\n";

	out << "void\n";
	out << strTypeName << "Ref::destroy_object()\n";
	out.indent();
	out << "throw(CORBA::SystemException)\n";
	out.unindent();
	out << "{\n";
	out.indent();
	out << "if( pObj_!=NULL )\n";
	out.indent();
	out << "pObj_->destroy_object();\n";
	out.unindent();
	out.unindent();
	out << "}\n\n";

	out << "Pid*\n";
	out << strTypeName << "Ref::get_pid() const\n";
	out.indent();
	out << "throw(CORBA::SystemException)\n";
	out.unindent();
	out << "{\n";
	out.indent();
	out << "Pid* pPid = NULL;\n\n";
	out << "if( pObj_!=NULL )\n";
	out.indent();
	out << "pPid = pObj_->get_pid();\n\n";
	out.unindent();
	out << "return pPid;\n";
	out.unindent();
	out << "}\n\n";

	out << "ShortPid*\n";
	out << strTypeName << "Ref::get_short_pid() const\n";
	out.indent();
	out << "throw(CORBA::SystemException)\n";
	out.unindent();
	out << "{\n";
	out.indent();
	out << "ShortPid* pSpid = NULL;\n\n";
	out << "if( pObj_!=NULL )\n";
	out.indent();
	out << "pSpid = pObj_->get_short_pid();\n\n";
	out.unindent();
	out << "return pSpid;\n";
	out.unindent();
	out << "}\n\n";

	out << "CORBA::Boolean\n";
	out << strTypeName << "Ref::is_null() const\n";
	out << "{\n";
	out.indent();
	out << "return ( pObj_==NULL );\n";
	out.unindent();
	out << "}\n\n";

	out << strActBasename_ << "*\n";
	out << strTypeName << "Ref::get_storage_home() const\n";
	out.indent();
	out << "throw(CORBA::SystemException)\n";
	out.unindent();
	out << "{\n";
	out.indent();
	out << "StorageHomeBase_var pHomeBase = StorageHomeBase::_nil();\n";
	out << strActBasename_ << "* pHome = NULL;\n\n";
	out << "if( pObj_!=NULL )\n";
	out << "{\n";
	out.indent();
	out << "pHomeBase = pObj_->get_storage_home();\n";
	out << "pHome = dynamic_cast <" << strActBasename_ << "*> (pHomeBase._retn());\n";
	out.unindent();
	out << "}\n\n";
	out << "return pHome;\n";
	out.unindent();
	out << "}\n\n";

	out << strTypeName << "Ref\n";
	out << strTypeName << "Ref::_duplicate(const " << strTypeName << "Ref ref)\n";
	out << "{\n";
	out.indent();
	out << "return " << strTypeName << "Ref( ref );\n";
	out.unindent();
	out << "}\n\n";

	out << strTypeName << "Ref\n";
	out << strTypeName << "Ref::_downcast(const " << strTypeName << "Ref ref)\n";
	out << "{\n";
	out.indent();
	out << "return ref;\n";
	out.unindent();
	out << "}\n\n";
}

void
GeneratorPersistenceC::genRefBody(IR__::StorageTypeDef_ptr storagetype)
{
	std::string strClassName = std::string(storagetype->name());
	genBaseRefBody(strClassName);
	
	// generate conversion operators
	out << "//conversion operators\n";
	out << "//... to do ...\n\n";
}

void
GeneratorPersistenceC::genAbstractRefBody(IR__::AbstractStorageTypeDef_ptr abs_storagetype)
{
	std::string strClassName = std::string(abs_storagetype->name());
	genBaseRefBody(strClassName);
	
	// generate conversion operators
	out << "//conversion operators\n";
	out << "//... to do ...\n\n";
}

void 
GeneratorPersistenceC::doAbstractStorageType(IR__::AbstractStorageTypeDef_ptr abs_storagetype)
{
	out << "\n\n";	
	open_module(out, abs_storagetype, "");
	out << "\n\n";

	//std::string strClassName = std::string(abs_storagetype->name());
	//genDuplAndDown(strClassName);
	//out << "\n";

	// generate ref class
	// Don't known how to build a Ref-class :-(
	//genStorageTypeBody(storagetype, true);
	genAbstractRefBody(abs_storagetype); // Hopefully it's right!
	
	out << "\n\n";
	close_module(out, abs_storagetype);
}

void 
GeneratorPersistenceC::doStorageType(IR__::StorageTypeDef_ptr storagetype)
{
	out << "\n\n";	
	open_module(out, storagetype, "");
	out << "\n\n";

	// generate normal class
	genStorageTypeBody(storagetype/*, false*/);
	// generate ref class
	// Don't known how to build a Ref-class :-(
	//genStorageTypeBody(storagetype, true);
	genRefBody(storagetype); // Hopefully it's right!

	close_module(out, storagetype);
}

void
GeneratorPersistenceC::genAbstractObjsForConcreteHome(IR__::AbstractStorageHomeDef_ptr abs_storagehome)
{
	IR__::InterfaceDefSeq_var abs_storagehome_seq = abs_storagehome->base_abstract_storagehomes();

	for(CORBA::ULong i=0; i<abs_storagehome_seq->length(); i++) 
	{
		IR__::AbstractStorageHomeDef_var abs_storagehome_inh;
		abs_storagehome_inh = IR__::AbstractStorageHomeDef::_narrow((*abs_storagehome_seq)[i]);
		bAbstract_ = true;
		handleAttribute(abs_storagehome_inh);
		handleOperation(abs_storagehome_inh);
		handleFactory(abs_storagehome_inh);
		handleKey(abs_storagehome_inh);
	}

	bAbstract_ = true;
	handleAttribute(abs_storagehome);
	handleOperation(abs_storagehome);
	handleFactory(abs_storagehome);
	handleKey(abs_storagehome);
}

void
GeneratorPersistenceC::genCreateOperation(IR__::StorageHomeDef_ptr storagehome, bool isRef)
{
	IR__::InterfaceDefSeq_var supported_infs = storagehome->supported_interfaces();
		
	//IR__::AbstractStorageHomeDef_var abs_storagehome = 
	//	IR__::AbstractStorageHomeDef::_narrow((*supported_infs)[0]);

	std::string strDummy = "";
	int iLength = strClassname_.length() + 10;
	char* szRetType = map_psdl_return_type(storagehome->managed_storagetype(), false);
	char* szOriginalType = map_psdl_return_type(storagehome->managed_storagetype(), false);
	IR__::AttributeDef_var attribute = 0;
	
	if(isRef)
	{
		char* pdest = strstr( szRetType, "*" );
		if( pdest != NULL )
		{
			memset(pdest, '\0', 1);
			strcat(szRetType, "Ref");
		}
	}
	
	out << szRetType << "\n" << strClassname_ << "::_create(";
	out << "Pid* pid,\n";
	strDummy.append(iLength, ' ');
	out << strDummy.c_str();
	out << "ShortPid* shortPid,\n";

	IR__::AttributeDefSeq state_members = 
		collectStateMembers(storagehome->managed_storagetype(), CORBA__::dk_Create);

	CORBA::ULong ulLen = state_members.length();

	for(CORBA::ULong i=0; i<ulLen; i++)
	{
		strDummy = "";
		strDummy.append(iLength, ' ');
		out << strDummy.c_str();

		attribute = IR__::AttributeDef::_narrow(state_members[i]);
		out << map_in_parameter_type(attribute->type_def()) << " " << mapName(attribute);
		if( (i+1)!=ulLen )
			out << ",\n";
	}
	
	if(isRef)
	{
		strDummy = "";
		strDummy.append(iLength, ' ');
		out << ",\n" << strDummy.c_str() << "CosPersistentState::YieldRef yr";
	}

	out << ")\n"; 
	out << "{\n";
	out.indent();

	//+++++++++++++++++++++++++++++++++++++++++++
	// INSERT sentence for _create in storagehome
	//+++++++++++++++++++++++++++++++++++++++++++
	out << "char* szTemp = new char[64];\n";
	out << "std::string strInsert = \"\";\n\n";
	out << "CatalogBase_ptr pCatalogBase = get_catalog();\n";
	out << "CatalogBaseImpl* pCatalogBaseImpl = dynamic_cast <CatalogBaseImpl*> (pCatalogBase);\n\n";
	strName_ = "strInsert";

	out << strName_ << " = \"INSERT INTO pid_content (pid, ownhome) VALUES ( \";\n";
	strContent_ = "\\'";
	out << genSQLLine(strName_, strContent_, false, false, false);
	strContent_ = "convertPidToString(pid)";
	out << genSQLLine(strName_, strContent_, false, false, false, true);
	strContent_ = "\\'";
	out << genSQLLine(strName_, strContent_, false, true, true);
	out << strName_ << " += \"\\\'" << storagehome->name() << "\\\' );\";\n\n";
	out << "if(!pCatalogBaseImpl->ExecuteSQL(" << strName_ << ".c_str()))\n";
	out.indent();
	out << "throw CORBA::BAD_PARAM();\n\n";
	out.unindent();

	out << strName_ << " = \"INSERT INTO " << storagehome->name() << " ( pid, spid, ";
	
	for(i=0; i<ulLen; i++)
	{
		attribute = IR__::AttributeDef::_narrow(state_members[i]);
		if( attribute->type_def()->type()->kind() == CORBA::tk_value )
		{
			std::list<IR__::ValueDef_ptr>::iterator valuetype_iter;
			for(valuetype_iter = lValueTypes_.begin();
				valuetype_iter != lValueTypes_.end();
				valuetype_iter++)
			{
				IR__::ValueDef_var value = IR__::ValueDef::_narrow(*valuetype_iter);
				std::string attr_type_name = map_attribute_type(attribute->type_def());
				if(attr_type_name.find(mapName(value))!=std::string::npos)
				{
					IR__::ContainedSeq_var contained_seq = value->contents(CORBA__::dk_ValueMember, true);
					for(CORBA::ULong j = 0; j < contained_seq->length(); j++)
					{
						IR__::ValueMemberDef_var vMember = IR__::ValueMemberDef::_narrow((*contained_seq)[j]);
						out << "value_" << mapName(vMember);
						( (i+1)!=ulLen ) ? out << ", " : out << " ) \";\n";
					}
					break;
				}
			}
		}
		else
		{
			out << mapName(attribute);
			( (i+1)!=ulLen ) ? out << ", " : out << " ) \";\n";
		}
	}
	
	out << "//Where should the pid and spid come from?\n";
	strContent_ = "VALUES (";
	out << genSQLLine(strName_, strContent_, false, false, true);
	strContent_ = "\\'";
	out << genSQLLine(strName_, strContent_, false, false, false);
	strContent_ = "convertPidToString(pid)";
	out << genSQLLine(strName_, strContent_, false, false, false, true);
	strContent_ = "\\'";
	out << genSQLLine(strName_, strContent_, false, true, true);
	strContent_ = "\\'";
	out << genSQLLine(strName_, strContent_, false, false, false);
	strContent_ = "convertSpidToString(shortPid)";
	out << genSQLLine(strName_, strContent_, false, false, false, true);
	strContent_ = "\\'";
	out << genSQLLine(strName_, strContent_, false, true, true);

	for(CORBA::ULong i=0; i<ulLen; i++)
	{
		attribute = IR__::AttributeDef::_narrow(state_members[i]);
		// parse valuemember from valuetype
		if( attribute->type_def()->type()->kind() == CORBA::tk_value )
		{
			std::list<IR__::ValueDef_ptr>::iterator valuetype_iter;
			for(valuetype_iter = lValueTypes_.begin();
				valuetype_iter != lValueTypes_.end();
				valuetype_iter++)
			{
				IR__::ValueDef_var value = IR__::ValueDef::_narrow(*valuetype_iter);
				std::string attr_type_name = map_attribute_type(attribute->type_def());
				if(attr_type_name.find(mapName(value))!=std::string::npos)
				{
					IR__::ContainedSeq_var contained_seq = value->contents(CORBA__::dk_ValueMember, true);
					for(CORBA::ULong j = 0; j < contained_seq->length(); j++)
					{
						IR__::ValueMemberDef_var vMember = IR__::ValueMemberDef::_narrow((*contained_seq)[j]);
						switch(psdl_check_type(vMember->type_def()))
						{
						case CPPBase::_SHORT:
							out << "memset(szTemp, \'\\0\', 64);\n";
							out << "sprintf(szTemp, \"%hd\", " << mapName(attribute) << "->" << mapName(vMember) << "());\n";
							if((i+1)!=ulLen)
								out << strName_ << ".append(strcat(szTemp, \", \"));\n";
							else
								out << strName_ << ".append(strcat(szTemp, \" \"));\n";
							break;
						case CPPBase::_INT:
							out << "memset(szTemp, \'\\0\', 64);\n";
							out << "sprintf(szTemp, \"%d\", " << mapName(attribute) << "->" << mapName(vMember) << "());\n";
							if((i+1)!=ulLen)
								out << strName_ << ".append(strcat(szTemp, \", \"));\n";
							else
								out << strName_ << ".append(strcat(szTemp, \" \"));\n";
							break;
						case CPPBase::_LONG:
							out << "memset(szTemp, \'\\0\', 64);\n";
							out << "sprintf(szTemp, \"%ld\", " << mapName(attribute) << "->" << mapName(vMember) << "());\n";
							if((i+1)!=ulLen)
								out << strName_ << ".append(strcat(szTemp, \", \"));\n";
							else
								out << strName_ << ".append(strcat(szTemp, \" \"));\n";
							break;
						case CPPBase::_STRING:
							strContent_ = "\\'";
							out << genSQLLine(strName_, strContent_, false, false, false);
							strContent_ = mapName(attribute) + "->";
							strContent_ += mapName(vMember);
							strContent_ += "()";
							out << genSQLLine(strName_, strContent_, false, false, false, true);
							strContent_ = "\\'";
							out << genSQLLine(strName_, strContent_, false, ((i+1)!=ulLen), true);
							break;
						}
					}
					break;
				}
			}
		}
		else // for normal state member with normal data type
		{
			switch(psdl_check_type(attribute->type_def()))
			{
			case CPPBase::_SHORT:
				out << "memset(szTemp, \'\\0\', 64);\n";
				out << "sprintf(szTemp, \"%hd\", " << mapName(attribute) << ");\n";
				if((i+1)!=ulLen)
					out << strName_ << ".append(strcat(szTemp, \", \"));\n";
				else
					out << strName_ << ".append(strcat(szTemp, \" \"));\n";
				break;
			case CPPBase::_INT:
				out << "memset(szTemp, \'\\0\', 64);\n";
				out << "sprintf(szTemp, \"%d\", " << mapName(attribute) << ");\n";
				if((i+1)!=ulLen)
					out << strName_ << ".append(strcat(szTemp, \", \"));\n";
				else
					out << strName_ << ".append(strcat(szTemp, \" \"));\n";
				break;
			case CPPBase::_LONG:
				out << "memset(szTemp, \'\\0\', 64);\n";
				out << "sprintf(szTemp, \"%ld\", " << mapName(attribute) << ");\n";
				if((i+1)!=ulLen)
					out << strName_ << ".append(strcat(szTemp, \", \"));\n";
				else
					out << strName_ << ".append(strcat(szTemp, \" \"));\n";
				break;
			case CPPBase::_FLOAT:
				out << "memset(szTemp, \'\\0\', 64);\n";
				out << "sprintf(szTemp, \"%f\", " << mapName(attribute) << ");\n";
				if((i+1)!=ulLen)
					out << strName_ << ".append(strcat(szTemp, \", \"));\n";
				else
					out << strName_ << ".append(strcat(szTemp, \" \"));\n";
				break;
			case CPPBase::_DOUBLE:
				out << "memset(szTemp, \'\\0\', 64);\n";
				out << "sprintf(szTemp, \"%lf\", " << mapName(attribute) << ");\n";
				if((i+1)!=ulLen)
					out << strName_ << ".append(strcat(szTemp, \", \"));\n";
				else
					out << strName_ << ".append(strcat(szTemp, \" \"));\n";
				break;
			case CPPBase::_LONGDOUBLE:
				out << "memset(szTemp, \'\\0\', 64);\n";
				out << "sprintf(szTemp, \"%Lf\", " << mapName(attribute) << ");\n";
				if((i+1)!=ulLen)
					out << strName_ << ".append(strcat(szTemp, \", \"));\n";
				else
					out << strName_ << ".append(strcat(szTemp, \" \"));\n";
				break;
			case CPPBase::_STRING:
				strContent_ = "\\'";
				out << genSQLLine(strName_, strContent_, false, false, false);
				strContent_ = mapName(attribute);
				out << genSQLLine(strName_, strContent_, false, false, false, true);
				strContent_ = "\\'";
				out << genSQLLine(strName_, strContent_, false, ((i+1)!=ulLen), true);
				break;
			case CPPBase::_BOOL:
				strContent_ = "convertBool2String(" + mapName(attribute) + ")";
				out << genSQLLine(strName_, strContent_, false, ((i+1)!=ulLen), false, true);
				strContent_ = "";
				out << genSQLLine(strName_, strContent_, false, false, true);
				break;
			}
		}
	}
	strContent_ = ");";
	out << genSQLLine(strName_, strContent_, false, false, false);
	//++++++++++++++++++++++++++++++++++++++++++++++++++
	// end of INSERT sentence for _create in storagehome
	//++++++++++++++++++++++++++++++++++++++++++++++++++
	
	out << "\nif(pCatalogBaseImpl->ExecuteSQL(" << strName_ << ".c_str()))\n";
	out << "{\n";
	out.indent();
	
	out << "//use factory to create a storage object\n";
	out << "#ifdef ORBACUS_ORB\n";
	out << "StorageObjectFactory factory = new OBNative_CosPersistentState::StorageObjectFactory_pre();\n";
	out << "#endif\n";
	out << "#ifdef MICO_ORB\n";
	out << "StorageObjectFactory factory = new CosPersistentState::StorageObjectFactory_pre();\n";
	out << "#endif\n";
	out << "factory = pCatalogBaseImpl->getConnector()->register_storage_object_factory(\"\", factory);\n";
	out << "StorageObjectImpl* pObjectImpl = factory->create();\n";
	out << "factory->_remove_ref();\n";
	out << "lObjectes_.push_back(pObjectImpl);\n";
	if(!isRef)
		out << szRetType << " pActObject = dynamic_cast <" << szRetType << "> (pObjectImpl);\n";
	else
		out << szOriginalType << " pActObject = dynamic_cast <" << szOriginalType << "> (pObjectImpl);\n";
	out << "\n//set values to current storageobject incarnation\n";
	out << "//How to handle with pid and spid?\n";
	for(CORBA::ULong i=0; i<ulLen; i++)
	{
		attribute = IR__::AttributeDef::_narrow(state_members[i]);
		out << "pActObject->" << mapName(attribute) << "(";
		if( attribute->type_def()->type()->kind() == CORBA::tk_value )
			out << "*"; // special for valuetype :-(
		out << mapName(attribute) << ");\n";
	}
	if(!isRef)
	{
		out << "\nreturn pActObject;\n";
	}
	else
	{
		out << szRetType << " ref = pActObject;\n";
		out << "\nreturn ref;\n";
	}
	
	out.unindent();
	out << "}\n";
	out << "else\n";
	out.indent();
	out << "throw CORBA::BAD_PARAM();\n";
	out.unindent();
	out.unindent();
	out << "\n// BEGIN USER INSERT SECTION " << strClassname_ << "::_create()\n";
	out << "// END USER INSERT SECTION " << strClassname_ << "::_create()\n}\n\n";
}

void 
GeneratorPersistenceC::doAbstractStorageHome(IR__::AbstractStorageHomeDef_ptr abs_storagehome)
{
	strActBasename_ = std::string(abs_storagehome->name());
	/*out << "\n\n";
	open_module(out, abs_storagehome, "");
	out << "\n\n";
	genDuplAndDown(strActBasename_);
	out << "\n\n";
	close_module(out, abs_storagehome);*/
}

void
GeneratorPersistenceC::doStorageHome(IR__::StorageHomeDef_ptr storagehome)
{
	strClassname_ = std::string(storagehome->name());
	strActBasename_ = strClassname_;

	IR__::StorageHomeDef_var base_storagehome = storagehome->base_storagehome();
	IR__::InterfaceDefSeq_var supported_infs = storagehome->supported_interfaces();
	IR__::StorageTypeDef_var storagetype = storagehome->managed_storagetype();
	
	CORBA::ULong ulLenSupportedInf = supported_infs->length();
/*
	for(CORBA::ULong i = 0; i < ulLenSupportedInf; i++)
	{
		IR__::AbstractStorageHomeDef_var abs_storagehome = 
			IR__::AbstractStorageHomeDef::_narrow((*supported_infs)[i]);
		IR__::AbstractStorageTypeDef_var abs_storagetype = 
			abs_storagehome->managed_abstract_storagetype();
		homeMap_.insert( Sth_Pair(abs_storagetype->name(), abs_storagehome->name()) );
	}
*/
	homeMap_.insert( Sth_Pair(storagetype->name(), storagehome->name()) );

	IR__::AttributeDefSeq state_members = collectStateMembers(storagetype, CORBA__::dk_Self);
	//IR__::InterfaceDefSeq_var base_abs_storagehomes = abs_storagehome->base_abstract_storagehomes();

	CORBA::ULong ulLen = state_members.length();
	//CORBA::ULong ulLenBaseAbsHomes = base_abs_storagehomes->length();
	IR__::AttributeDef_var attribute = 0;

	// achtung: wenn kein modul, sollte vielleicht PSS_ der prefix für alle pss sein?
	out << "\n\n";
	open_module(out, storagetype, "");
	out << "\n\n";

	out << "// BEGIN USER INSERT SECTION " << strClassname_ << "\n";
	out << "// END USER INSERT SECTION " << strClassname_ << "\n\n";
	out << strClassname_ << "::" << strClassname_ << "()\n";
	out << "{\n";
	out.indent();

	//++++++++++++++++++++++++++++++++++++++++
	// CREATE sentence 
	//++++++++++++++++++++++++++++++++++++++++
	/*strName_ = "strCreateTable_";
	strContent_ = "CREATE TABLE ";
	strContent_ += strClassname_;
	strContent_ += " (";
	out << genSQLLine(strName_, strContent_, true, false, true);

	if(ulLenSupportedInf==0 && CORBA::is_nil(base_storagehome))
	{
		strContent_ = "pid  VARCHAR(254)  NOT NULL  REFERENCES PID_CONTENT";
		out << genSQLLine(strName_, strContent_, false, true, true);
		strContent_ = "spid  VARCHAR(254)";
		out << genSQLLine(strName_, strContent_, false, true, true);
	}

	for( CORBA::ULong i=0; i<ulLen; i++)
	{
		attribute = IR__::AttributeDef::_narrow(state_members[i]);
		if( attribute->type_def()->type()->kind() == CORBA::tk_value )
		{
			std::list<IR__::ValueDef_ptr>::iterator valuetype_iter;
			for(valuetype_iter = lValueTypes_.begin();
				valuetype_iter != lValueTypes_.end();
				valuetype_iter++)
			{
				IR__::ValueDef_var value = IR__::ValueDef::_narrow(*valuetype_iter);
				std::string attr_type_name = map_attribute_type(attribute->type_def());
				if(attr_type_name.find(mapName(value))!=std::string::npos)
				{
					IR__::ContainedSeq_var contained_seq = value->contents(CORBA__::dk_ValueMember, true);
					for(CORBA::ULong j = 0; j < contained_seq->length(); j++)
					{
						IR__::ValueMemberDef_var vMember = IR__::ValueMemberDef::_narrow((*contained_seq)[j]);
						strContent_ = "value_";
						strContent_ += mapName(vMember);
						strContent_ += "  ";
						strContent_.append( map_psdl2sql_type(vMember->type_def()) );
						bool isComma = ((j+1)!=ulLen) || (ulLenSupportedInf==0);
						out << genSQLLine(strName_, strContent_, false, isComma, true);
					}
					break;
				}
			}
		}
		else
		{
			strContent_ = mapName(attribute);
			strContent_ += "  ";
			strContent_.append( map_psdl2sql_type(attribute->type_def()) );
			bool isComma = ((i+1)!=ulLen) || (ulLenSupportedInf==0);
			out << genSQLLine(strName_, strContent_, false, isComma, true);	
		}
	}
	
	if( !CORBA::is_nil(base_storagehome) || ulLenSupportedInf>0 )
	{
		strContent_ = ") INHERITS ( ";
		if(!CORBA::is_nil(base_storagehome))
		{
			strContent_.append(base_storagehome->name());
			(ulLenSupportedInf>0) ? strContent_ += ", " : strContent_ += " );";
			out << genSQLLine(strName_, strContent_, false, false, false);
			strContent_ = "";
		}
		
		for(CORBA::ULong j=0; j<ulLenSupportedInf; j++)
		{
			strContent_.append(((*supported_infs)[j])->name());
			((j+1)!=ulLenSupportedInf) ? strContent_ += ", " : strContent_ += " );";
			out << genSQLLine(strName_, strContent_, false, false, false);
			strContent_ = "";
		}
	}
	else
	{
		strContent_ = "CONSTRAINT PK_";
		strContent_ += strClassname_;
		strContent_ += " PRIMARY KEY (pid)";
		out << genSQLLine(strName_, strContent_, false, false, true);
		strContent_ = ");";
		out << genSQLLine(strName_, strContent_, false, false, false);
	}

	out << "\n";*/
	//++++++++++++++++++++++++++++++++++++++++
	// end of CREATE sentence !!!!!!!!!!!!!!!!
	//++++++++++++++++++++++++++++++++++++++++

	out.unindent();
	out << "// BEGIN USER INSERT SECTION " << strClassname_ << "::" << strClassname_ << "()\n";
	out << "// END USER INSERT SECTION " <<strClassname_ << "::" << strClassname_ << "()\n}\n\n";
	out << strClassname_ << "::~" << strClassname_ << "()\n";
	out << "{\n// BEGIN USER INSERT SECTION " << strClassname_ << "::~" << strClassname_ << "()\n";
	out << "// END USER INSERT SECTION " <<strClassname_ << "::~" << strClassname_ << "()\n}\n\n";
	
	genCreateOperation(storagehome, false);
	genCreateOperation(storagehome, true);

	bRef_ = false;
	for( CORBA::ULong i=0; i<ulLenSupportedInf; i++ )
	{
		IR__::AbstractStorageHomeDef_var abs_storagehome;
		abs_storagehome = IR__::AbstractStorageHomeDef::_narrow((*supported_infs)[i]);
		genAbstractObjsForConcreteHome(abs_storagehome);
	};

	bAbstract_ = false;
	handleAttribute(storagehome);
	handleOperation(storagehome);
	handleFactory(storagehome);
	handleKey(storagehome);
	//genDuplAndDown(strClassname_);
	//out << "\n\n";
	close_module(out, storagetype);
}

IR__::AttributeDefSeq 
GeneratorPersistenceC::collectStateMembers(IR__::InterfaceDef_ptr inf_def, CORBA__::CollectStyle style)
{
	IR__::AttributeDefSeq state_members;

	IR__::AbstractStorageTypeDef_var abs_storagetype =
		IR__::AbstractStorageTypeDef::_narrow(inf_def);
	if(!CORBA::is_nil(abs_storagetype))
		abs_storagetype->get_state_members(state_members, style);

	IR__::StorageTypeDef_var storagetype = 
		IR__::StorageTypeDef::_narrow(inf_def);
	if(!CORBA::is_nil(storagetype))
		storagetype->get_state_members(state_members, style);

	return state_members;
}

std::string
GeneratorPersistenceC::genSQLLine(std::string strName, std::string strContent, bool start, bool comma, bool space, bool func)
{
	std::string strRet = strName;

	start ? strRet += " = " : strRet += " += ";
	if(!func) strRet += "\"";
	strRet += strContent;
	if(comma) strRet += ",";
	if(space) strRet += " ";
	if(!func) strRet += "\"";
	strRet += ";\n";

	return strRet;
}

} // namespace
