include ../config/Makefile.conf

all : libCIDLRepository.a

libCIDLRepository.a : \
	CIDLRepository_impl.o CompositionDef_impl.o ExecutorDef_impl.o \
	HomeExecutorDef_impl.o SegmentDef_impl.o
	ar cr $@ $?
	ranlib $@

%.o : %.cpp
	g++ $(DEBUG) -c $< -I$(ORBACUS_INSTALL_DIR)/include -I. -I../ComponentRepositoryLib -I../IFRidl

clean:
	-rm libCIDLRepository.a
	-rm *.o
