//
// generated by Qedo
//

#include "HelloWorld_CallerImpl.h"


// BEGIN USER INSERT SECTION file
// END USER INSERT SECTION file


namespace HelloWorld {


// BEGIN USER INSERT SECTION CallerSessionImpl
// END USER INSERT SECTION CallerSessionImpl


CallerSessionImpl::CallerSessionImpl()
{
// BEGIN USER INSERT SECTION CallerSessionImpl::CallerSessionImpl
// END USER INSERT SECTION CallerSessionImpl::CallerSessionImpl
}


CallerSessionImpl::~CallerSessionImpl()
{
// BEGIN USER INSERT SECTION CallerSessionImpl::~CallerSessionImpl
// END USER INSERT SECTION CallerSessionImpl::~CallerSessionImpl

}


void
CallerSessionImpl::set_context(::HelloWorld::CCM_Caller_Context_ptr context)
    throw (CORBA::SystemException, Components::CCMException)
{
    context_ = ::HelloWorld::CCM_Caller_Context::_duplicate(context);
}


void
CallerSessionImpl::configuration_complete()
    throw (CORBA::SystemException, Components::InvalidConfiguration)
{
// BEGIN USER INSERT SECTION CallerSessionImpl::configuration_complete
// END USER INSERT SECTION CallerSessionImpl::configuration_complete
}


void
CallerSessionImpl::remove()
    throw (CORBA::SystemException)
{
// BEGIN USER INSERT SECTION CallerSessionImpl::remove
// END USER INSERT SECTION CallerSessionImpl::remove
}


// BEGIN USER INSERT SECTION CallerImpl
// END USER INSERT SECTION CallerImpl


CallerImpl::CallerImpl()
:component_(new CallerSessionImpl())
{
// BEGIN USER INSERT SECTION CallerImpl::CallerImpl
// END USER INSERT SECTION CallerImpl::CallerImpl
}


CallerImpl::~CallerImpl()
{
// BEGIN USER INSERT SECTION CallerImpl::~CallerImpl
// END USER INSERT SECTION CallerImpl::~CallerImpl

    component_->_remove_ref();
}


::CORBA::Object*
CallerImpl::obtain_executor(const char* name)
    throw (CORBA::SystemException)
{
    if (! strcmp ( name, "component" ) ) {
        return Components::EnterpriseComponent::_duplicate (component_);
    }
    
    return Components::EnterpriseComponent::_nil();
}


void
CallerImpl::release_executor(::CORBA::Object_ptr executor)
    throw (CORBA::SystemException)
{
    CORBA::release (executor);
}


void
CallerImpl::configuration_complete()
    throw (CORBA::SystemException, Components::InvalidConfiguration)
{
    component_->configuration_complete();

// BEGIN USER INSERT SECTION CallerImpl::configuration_complete
// END USER INSERT SECTION CallerImpl::configuration_complete
}


void
CallerImpl::set_session_context(::Components::SessionContext_ptr context)
    throw (CORBA::SystemException, Components::CCMException)
{
    #ifdef TAO_ORB
    ::HelloWorld::CCM_Caller_Context_ptr tmp_context;
    
    tmp_context = dynamic_cast<::HelloWorld::CCM_Caller_Context*>(context);
    
    if (tmp_context)
        context_ = ::HelloWorld::CCM_Caller_Context::_duplicate(tmp_context);
    else
        context_ = ::HelloWorld::CCM_Caller_Context::_nil();
        
    #else
    context_ = ::HelloWorld::CCM_Caller_Context::_narrow(context);
    
    #endif
    component_->set_context(context_);
}


void
CallerImpl::ccm_activate()
    throw (CORBA::SystemException, Components::CCMException)
{
// BEGIN USER INSERT SECTION CallerImpl::ccm_activate
// END USER INSERT SECTION CallerImpl::ccm_activate
}


void
CallerImpl::ccm_passivate()
    throw (CORBA::SystemException, Components::CCMException)
{
// BEGIN USER INSERT SECTION CallerImpl::ccm_passivate
// END USER INSERT SECTION CallerImpl::ccm_passivate
}


void
CallerImpl::ccm_remove()
    throw (CORBA::SystemException, Components::CCMException)
{
// BEGIN USER INSERT SECTION CallerImpl::ccm_remove
// END USER INSERT SECTION CallerImpl::ccm_remove
}


// BEGIN USER INSERT SECTION CallerHomeImpl
// END USER INSERT SECTION CallerHomeImpl


CallerHomeImpl::CallerHomeImpl()
{
// BEGIN USER INSERT SECTION CallerHomeImpl::CallerHomeImpl
// END USER INSERT SECTION CallerHomeImpl::CallerHomeImpl
}


CallerHomeImpl::~CallerHomeImpl()
{
// BEGIN USER INSERT SECTION CallerHomeImpl::~CallerHomeImpl
// END USER INSERT SECTION CallerHomeImpl::~CallerHomeImpl

}


void
CallerHomeImpl::set_context(Components::CCMContext_ptr ctx)
    throw (CORBA::SystemException, Components::CCMException)
{
    context_ = Components::CCMContext::_duplicate(ctx);
}


::Components::EnterpriseComponent_ptr
CallerHomeImpl::create ()
    throw (CORBA::SystemException, Components::CreateFailure)
{
// BEGIN USER INSERT SECTION CallerHomeImpl::create
// END USER INSERT SECTION CallerHomeImpl::create
    return new CallerImpl();
}


};


//
// entry point
//
::Components::HomeExecutorBase_ptr
create_CallerHomeE(void)
{
// BEGIN USER INSERT SECTION create_CallerHome
// END USER INSERT SECTION create_CallerHome

    return new ::HelloWorld::CallerHomeImpl();
}

