/***************************************************************************/
/*                                                                         */
/* Qedo - Qualitiy of Service Enabled Distributed Objects                  */
/*                                                                         */
/* Copyright (C) 2002 by the Qedo Team                                     */
/*                                                                         */
/* This library is free software; you can redistribute it and/or           */
/* modify it under the terms of the GNU Lesser General Public              */
/* License as published by the Free Software Foundation; either            */
/* version 2.1 of the License, or (at your option) any later version.      */
/*                                                                         */
/* This library is distributed in the hope that it will be useful,         */
/* but WITHOUT ANY WARRANTY; without even the implied warranty of          */
/* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU        */
/* Lesser General Public License for more details.                         */
/*                                                                         */
/* You should have received a copy of the GNU Lesser General Public        */
/* License along with this library; if not, write to the Free Software     */
/* Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA */
/***************************************************************************/

#ifndef __QEDO_COMPONENTS_IDL__
#define __QEDO_COMPONENTS_IDL__

#include "Components.idl"


module Qedo_Components {

	module Deployment {

		interface ServerActivator : Components::Deployment::ServerActivator
		{
			void notify_component_server (in Components::Deployment::ComponentServer server);
		};

		interface ComponentInstallation : Components::Deployment::ComponentInstallation
		{
			string upload(in Components::Deployment::UUID implUUID, in CORBA::OctetSeq package)
				raises(Components::Deployment::InstallationFailure);
		};

	};

};

#endif
